#
# Makefile for MStar mtlb 
#
EXTRA_CFLAGS      +=  -Idrivers/mstar2/include
EXTRA_CFLAGS      +=  -Idrivers/mstar2/drv/ipa_pool
EXTRA_CFLAGS      +=  -Iinclude/linux

# files
obj-y     += pa_space.o
