/* Copyright (C) 2014 Cadence Design Systems.  All rights reserved           */
/* THIS FILE IS AUTOMATICALLY GENERATED BY CADENCE BLUEPRINT, DO NOT EDIT    */
/*                                                                           */


#ifndef __REG_CDN_AXI_WRAPPER_OB_H__
#define __REG_CDN_AXI_WRAPPER_OB_H__

#include "cdn_axi_wrapper_ob_macro.h"

struct cdn_axi_wrapper_ob {
  volatile uint32_t addr0;                        /*        0x0 - 0x4        */
  volatile uint32_t addr1;                        /*        0x4 - 0x8        */
  volatile uint32_t desc0;                        /*        0x8 - 0xc        */
  volatile uint32_t desc1;                        /*        0xc - 0x10       */
  volatile uint32_t desc2;                        /*       0x10 - 0x14       */
  volatile uint32_t desc3;                        /*       0x14 - 0x18       */
  volatile uint32_t ctrl;                         /*       0x18 - 0x1c       */
};

#endif /* __REG_CDN_AXI_WRAPPER_OB_H__ */
