////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2008-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("; MStar; Confidential; Information;") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

//****************************************************
// TGEN Drive Chip           : Uranus4_DAC_Driver
// TGEN Excel CodeGen Version: 1.04
// TGEN Excel SW      Version: 1.01
// TGEN Excel update date    : 2013/10/14 11:34
//****************************************************

#ifndef _MHAL_TGEN_TBL_H_
#define _MHAL_TGEN_TBL_H_

#ifdef __cplusplus
extern "C"
{
#endif

#define DRV_TGEN_REG(reg)      ((reg>>8)&0xFF), (reg&0xFF)
#define REG_ADDR_SIZE          2
#define REG_MASK_SIZE          1
#define REG_DATA_SIZE          1
#define REG_TABLE_END          0xFFFF

#define _TGEN_PK_L_(bank, addr)     ((MS_U16)(bank << 8) | ((addr)*2))
#define _TGEN_PK_H_(bank, addr)     ((MS_U16)((bank|0x80) << 8) | ((addr)*2+1))

#define  REG_TGEN_CLK_GEN0_BASE     0x0B00
#define  REG_TGEN_SC1_VOP_BASE     0x2F00
#define  REG_TGEN_HDMITx_MISC_BASE     0x1400
#define  REG_TGEN_HDMITx_SYNTH_BASE     0x1400

#if 0
typedef enum
{
    TGEN_TABTYPE_GENERAL,
    TGEN_TABTYPE_GPIO,
    TGEN_TABTYPE_SCALER,
    TGEN_TABTYPE_MOD,
    TGEN_TABTYPE_HDGEN,
    TGEN_TABTYPE_PLLSET,
    TGEN_TABTYPE_GAMMA,
    TGEN_TABTYPE_POWER_SEQUENCE_ON,
    TGEN_TABTYPE_POWER_SEQUENCE_OFF,
} E_TGEN_TAB_TYPE;
#endif

typedef enum
{
    TGEN_TABTYPE_INIT_CLKGEN,
    TGEN_TABTYPE_INIT_SC1,
    TGEN_TABTYPE_INIT_HDMITx_MISC,
    TGEN_TABTYPE_INIT_HDMITx_SYNTH_10,
    TGEN_TABTYPE_INIT_HDMITx_SYNTH_8,
} E_TGEN_TAB_TYPE;

typedef enum
{
    TGEN_SIGNAL_POL,
    TGEN_SIGNAL_VGH,
    TGEN_SIGNAL_SOE,
    TGEN_SIGNAL_VST,
    TGEN_SIGNAL_GCLK,
    TGEN_SIGNAL_NUMS,
} E_TGEN_POWER_SEQUENCE_SIGNAL_TYPE;

typedef struct
{
    MS_U8           *pDacINIT_CLKGENTab;
    E_TGEN_TAB_TYPE   eINIT_CLKGENtype;
    MS_U8           *pDacINIT_SC1Tab;
    E_TGEN_TAB_TYPE   eINIT_SC1type;
    MS_U8           *pDacINIT_HDMITx_MISCTab;
    E_TGEN_TAB_TYPE   eINIT_HDMITx_MISCtype;
    MS_U8           *pDacINIT_HDMITx_SYNTH_10Tab;
    E_TGEN_TAB_TYPE   eINIT_HDMITx_SYNTH_10type;
    MS_U8           *pDacINIT_HDMITx_SYNTH_8Tab;
    E_TGEN_TAB_TYPE   eINIT_HDMITx_SYNTH_8type;
} TGEN_TAB_INFO;

typedef enum
{
    TGEN_PANEL_VE_480I_60,
    TGEN_PANEL_VE_576I_50,
    TGEN_PANEL_480I_60,
    TGEN_PANEL_576I_50,
    TGEN_PANEL_480P_60,
    TGEN_PANEL_576P_50,
    TGEN_PANEL_720P_50,
    TGEN_PANEL_720P_60,
    TGEN_PANEL_1080I_50,
    TGEN_PANEL_1080I_60,
    TGEN_PANEL_1080P_50,
    TGEN_PANEL_1080P_60,
    TGEN_PANEL_1080P_30,
    TGEN_PANEL_1080P_25,
    TGEN_PANEL_1080P_24,
    TGEN_PANEL_NUMS,
} E_TGEN_PANEL_INDEX;

extern TGEN_TAB_INFO DACMAP_Main[TGEN_PANEL_NUMS];

typedef enum
{
    TGEN_TAB_VE_480I_60_INIT_CLKGEN_ALL,
    TGEN_TAB_VE_480I_60_INIT_CLKGEN_NUMS
} E_TGEN_VE_480I_60_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_VE_480I_60_INIT_SC1_ALL,
    TGEN_TAB_VE_480I_60_INIT_SC1_NUMS
} E_TGEN_VE_480I_60_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_VE_480I_60_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_VE_480I_60_INIT_HDMITx_MISC_NUMS
} E_TGEN_VE_480I_60_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_VE_480I_60_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_VE_480I_60_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_VE_480I_60_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_VE_480I_60_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_VE_480I_60_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_VE_480I_60_INIT_HDMITx_SYNTH_8_TYPE;

typedef enum
{
    TGEN_TAB_VE_576I_50_INIT_CLKGEN_ALL,
    TGEN_TAB_VE_576I_50_INIT_CLKGEN_NUMS
} E_TGEN_VE_576I_50_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_VE_576I_50_INIT_SC1_ALL,
    TGEN_TAB_VE_576I_50_INIT_SC1_NUMS
} E_TGEN_VE_576I_50_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_VE_576I_50_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_VE_576I_50_INIT_HDMITx_MISC_NUMS
} E_TGEN_VE_576I_50_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_VE_576I_50_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_VE_576I_50_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_VE_576I_50_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_VE_576I_50_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_VE_576I_50_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_VE_576I_50_INIT_HDMITx_SYNTH_8_TYPE;

typedef enum
{
    TGEN_TAB_480I_60_INIT_CLKGEN_ALL,
    TGEN_TAB_480I_60_INIT_CLKGEN_NUMS
} E_TGEN_480I_60_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_480I_60_INIT_SC1_ALL,
    TGEN_TAB_480I_60_INIT_SC1_NUMS
} E_TGEN_480I_60_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_480I_60_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_480I_60_INIT_HDMITx_MISC_NUMS
} E_TGEN_480I_60_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_480I_60_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_480I_60_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_480I_60_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_480I_60_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_480I_60_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_480I_60_INIT_HDMITx_SYNTH_8_TYPE;

typedef enum
{
    TGEN_TAB_576I_50_INIT_CLKGEN_ALL,
    TGEN_TAB_576I_50_INIT_CLKGEN_NUMS
} E_TGEN_576I_50_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_576I_50_INIT_SC1_ALL,
    TGEN_TAB_576I_50_INIT_SC1_NUMS
} E_TGEN_576I_50_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_576I_50_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_576I_50_INIT_HDMITx_MISC_NUMS
} E_TGEN_576I_50_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_576I_50_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_576I_50_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_576I_50_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_576I_50_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_576I_50_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_576I_50_INIT_HDMITx_SYNTH_8_TYPE;

typedef enum
{
    TGEN_TAB_480P_60_INIT_CLKGEN_ALL,
    TGEN_TAB_480P_60_INIT_CLKGEN_NUMS
} E_TGEN_480P_60_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_480P_60_INIT_SC1_ALL,
    TGEN_TAB_480P_60_INIT_SC1_NUMS
} E_TGEN_480P_60_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_480P_60_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_480P_60_INIT_HDMITx_MISC_NUMS
} E_TGEN_480P_60_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_480P_60_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_480P_60_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_480P_60_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_480P_60_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_480P_60_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_480P_60_INIT_HDMITx_SYNTH_8_TYPE;

typedef enum
{
    TGEN_TAB_576P_50_INIT_CLKGEN_ALL,
    TGEN_TAB_576P_50_INIT_CLKGEN_NUMS
} E_TGEN_576P_50_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_576P_50_INIT_SC1_ALL,
    TGEN_TAB_576P_50_INIT_SC1_NUMS
} E_TGEN_576P_50_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_576P_50_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_576P_50_INIT_HDMITx_MISC_NUMS
} E_TGEN_576P_50_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_576P_50_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_576P_50_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_576P_50_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_576P_50_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_576P_50_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_576P_50_INIT_HDMITx_SYNTH_8_TYPE;

typedef enum
{
    TGEN_TAB_720P_50_INIT_CLKGEN_ALL,
    TGEN_TAB_720P_50_INIT_CLKGEN_NUMS
} E_TGEN_720P_50_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_720P_50_INIT_SC1_ALL,
    TGEN_TAB_720P_50_INIT_SC1_NUMS
} E_TGEN_720P_50_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_720P_50_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_720P_50_INIT_HDMITx_MISC_NUMS
} E_TGEN_720P_50_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_720P_50_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_720P_50_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_720P_50_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_720P_50_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_720P_50_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_720P_50_INIT_HDMITx_SYNTH_8_TYPE;

typedef enum
{
    TGEN_TAB_720P_60_INIT_CLKGEN_ALL,
    TGEN_TAB_720P_60_INIT_CLKGEN_NUMS
} E_TGEN_720P_60_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_720P_60_INIT_SC1_ALL,
    TGEN_TAB_720P_60_INIT_SC1_NUMS
} E_TGEN_720P_60_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_720P_60_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_720P_60_INIT_HDMITx_MISC_NUMS
} E_TGEN_720P_60_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_720P_60_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_720P_60_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_720P_60_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_720P_60_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_720P_60_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_720P_60_INIT_HDMITx_SYNTH_8_TYPE;

typedef enum
{
    TGEN_TAB_1080I_50_INIT_CLKGEN_ALL,
    TGEN_TAB_1080I_50_INIT_CLKGEN_NUMS
} E_TGEN_1080I_50_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_1080I_50_INIT_SC1_ALL,
    TGEN_TAB_1080I_50_INIT_SC1_NUMS
} E_TGEN_1080I_50_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_1080I_50_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_1080I_50_INIT_HDMITx_MISC_NUMS
} E_TGEN_1080I_50_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_1080I_50_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_1080I_50_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_1080I_50_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_1080I_50_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_1080I_50_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_1080I_50_INIT_HDMITx_SYNTH_8_TYPE;

typedef enum
{
    TGEN_TAB_1080I_60_INIT_CLKGEN_ALL,
    TGEN_TAB_1080I_60_INIT_CLKGEN_NUMS
} E_TGEN_1080I_60_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_1080I_60_INIT_SC1_ALL,
    TGEN_TAB_1080I_60_INIT_SC1_NUMS
} E_TGEN_1080I_60_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_1080I_60_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_1080I_60_INIT_HDMITx_MISC_NUMS
} E_TGEN_1080I_60_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_1080I_60_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_1080I_60_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_1080I_60_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_1080I_60_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_1080I_60_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_1080I_60_INIT_HDMITx_SYNTH_8_TYPE;

typedef enum
{
    TGEN_TAB_1080P_50_INIT_CLKGEN_ALL,
    TGEN_TAB_1080P_50_INIT_CLKGEN_NUMS
} E_TGEN_1080P_50_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_1080P_50_INIT_SC1_ALL,
    TGEN_TAB_1080P_50_INIT_SC1_NUMS
} E_TGEN_1080P_50_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_1080P_50_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_1080P_50_INIT_HDMITx_MISC_NUMS
} E_TGEN_1080P_50_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_1080P_50_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_1080P_50_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_1080P_50_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_1080P_50_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_1080P_50_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_1080P_50_INIT_HDMITx_SYNTH_8_TYPE;

typedef enum
{
    TGEN_TAB_1080P_60_INIT_CLKGEN_ALL,
    TGEN_TAB_1080P_60_INIT_CLKGEN_NUMS
} E_TGEN_1080P_60_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_1080P_60_INIT_SC1_ALL,
    TGEN_TAB_1080P_60_INIT_SC1_NUMS
} E_TGEN_1080P_60_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_1080P_60_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_1080P_60_INIT_HDMITx_MISC_NUMS
} E_TGEN_1080P_60_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_1080P_60_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_1080P_60_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_1080P_60_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_1080P_60_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_1080P_60_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_1080P_60_INIT_HDMITx_SYNTH_8_TYPE;

typedef enum
{
    TGEN_TAB_1080P_30_INIT_CLKGEN_ALL,
    TGEN_TAB_1080P_30_INIT_CLKGEN_NUMS
} E_TGEN_1080P_30_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_1080P_30_INIT_SC1_ALL,
    TGEN_TAB_1080P_30_INIT_SC1_NUMS
} E_TGEN_1080P_30_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_1080P_30_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_1080P_30_INIT_HDMITx_MISC_NUMS
} E_TGEN_1080P_30_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_1080P_30_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_1080P_30_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_1080P_30_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_1080P_30_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_1080P_30_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_1080P_30_INIT_HDMITx_SYNTH_8_TYPE;

typedef enum
{
    TGEN_TAB_1080P_25_INIT_CLKGEN_ALL,
    TGEN_TAB_1080P_25_INIT_CLKGEN_NUMS
} E_TGEN_1080P_25_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_1080P_25_INIT_SC1_ALL,
    TGEN_TAB_1080P_25_INIT_SC1_NUMS
} E_TGEN_1080P_25_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_1080P_25_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_1080P_25_INIT_HDMITx_MISC_NUMS
} E_TGEN_1080P_25_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_1080P_25_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_1080P_25_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_1080P_25_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_1080P_25_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_1080P_25_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_1080P_25_INIT_HDMITx_SYNTH_8_TYPE;

typedef enum
{
    TGEN_TAB_1080P_24_INIT_CLKGEN_ALL,
    TGEN_TAB_1080P_24_INIT_CLKGEN_NUMS
} E_TGEN_1080P_24_INIT_CLKGEN_TYPE;

typedef enum
{
    TGEN_TAB_1080P_24_INIT_SC1_ALL,
    TGEN_TAB_1080P_24_INIT_SC1_NUMS
} E_TGEN_1080P_24_INIT_SC1_TYPE;

typedef enum
{
    TGEN_TAB_1080P_24_INIT_HDMITx_MISC_ALL,
    TGEN_TAB_1080P_24_INIT_HDMITx_MISC_NUMS
} E_TGEN_1080P_24_INIT_HDMITx_MISC_TYPE;

typedef enum
{
    TGEN_TAB_1080P_24_INIT_HDMITx_SYNTH_10_ALL,
    TGEN_TAB_1080P_24_INIT_HDMITx_SYNTH_10_NUMS
} E_TGEN_1080P_24_INIT_HDMITx_SYNTH_10_TYPE;

typedef enum
{
    TGEN_TAB_1080P_24_INIT_HDMITx_SYNTH_8_ALL,
    TGEN_TAB_1080P_24_INIT_HDMITx_SYNTH_8_NUMS
} E_TGEN_1080P_24_INIT_HDMITx_SYNTH_8_TYPE;

//-------------------------------------------------------------------------------------------------
// register define used for TCON table
//-------------------------------------------------------------------------------------------------

#define  REG_TGEN_CLK_GEN0_00_L       (REG_TGEN_CLK_GEN0_BASE + 0x00)
#define  REG_TGEN_CLK_GEN0_00_H       (REG_TGEN_CLK_GEN0_BASE + 0x01)
#define  REG_TGEN_CLK_GEN0_01_L       (REG_TGEN_CLK_GEN0_BASE + 0x02)
#define  REG_TGEN_CLK_GEN0_01_H       (REG_TGEN_CLK_GEN0_BASE + 0x03)
#define  REG_TGEN_CLK_GEN0_02_L       (REG_TGEN_CLK_GEN0_BASE + 0x04)
#define  REG_TGEN_CLK_GEN0_02_H       (REG_TGEN_CLK_GEN0_BASE + 0x05)
#define  REG_TGEN_CLK_GEN0_03_L       (REG_TGEN_CLK_GEN0_BASE + 0x06)
#define  REG_TGEN_CLK_GEN0_03_H       (REG_TGEN_CLK_GEN0_BASE + 0x07)
#define  REG_TGEN_CLK_GEN0_04_L       (REG_TGEN_CLK_GEN0_BASE + 0x08)
#define  REG_TGEN_CLK_GEN0_04_H       (REG_TGEN_CLK_GEN0_BASE + 0x09)
#define  REG_TGEN_CLK_GEN0_05_L       (REG_TGEN_CLK_GEN0_BASE + 0x0A)
#define  REG_TGEN_CLK_GEN0_05_H       (REG_TGEN_CLK_GEN0_BASE + 0x0B)
#define  REG_TGEN_CLK_GEN0_06_L       (REG_TGEN_CLK_GEN0_BASE + 0x0C)
#define  REG_TGEN_CLK_GEN0_06_H       (REG_TGEN_CLK_GEN0_BASE + 0x0D)
#define  REG_TGEN_CLK_GEN0_07_L       (REG_TGEN_CLK_GEN0_BASE + 0x0E)
#define  REG_TGEN_CLK_GEN0_07_H       (REG_TGEN_CLK_GEN0_BASE + 0x0F)
#define  REG_TGEN_CLK_GEN0_08_L       (REG_TGEN_CLK_GEN0_BASE + 0x10)
#define  REG_TGEN_CLK_GEN0_08_H       (REG_TGEN_CLK_GEN0_BASE + 0x11)
#define  REG_TGEN_CLK_GEN0_09_L       (REG_TGEN_CLK_GEN0_BASE + 0x12)
#define  REG_TGEN_CLK_GEN0_09_H       (REG_TGEN_CLK_GEN0_BASE + 0x13)
#define  REG_TGEN_CLK_GEN0_0A_L       (REG_TGEN_CLK_GEN0_BASE + 0x14)
#define  REG_TGEN_CLK_GEN0_0A_H       (REG_TGEN_CLK_GEN0_BASE + 0x15)
#define  REG_TGEN_CLK_GEN0_0B_L       (REG_TGEN_CLK_GEN0_BASE + 0x16)
#define  REG_TGEN_CLK_GEN0_0B_H       (REG_TGEN_CLK_GEN0_BASE + 0x17)
#define  REG_TGEN_CLK_GEN0_0C_L       (REG_TGEN_CLK_GEN0_BASE + 0x18)
#define  REG_TGEN_CLK_GEN0_0C_H       (REG_TGEN_CLK_GEN0_BASE + 0x19)
#define  REG_TGEN_CLK_GEN0_0D_L       (REG_TGEN_CLK_GEN0_BASE + 0x1A)
#define  REG_TGEN_CLK_GEN0_0D_H       (REG_TGEN_CLK_GEN0_BASE + 0x1B)
#define  REG_TGEN_CLK_GEN0_0E_L       (REG_TGEN_CLK_GEN0_BASE + 0x1C)
#define  REG_TGEN_CLK_GEN0_0E_H       (REG_TGEN_CLK_GEN0_BASE + 0x1D)
#define  REG_TGEN_CLK_GEN0_0F_L       (REG_TGEN_CLK_GEN0_BASE + 0x1E)
#define  REG_TGEN_CLK_GEN0_0F_H       (REG_TGEN_CLK_GEN0_BASE + 0x1F)
#define  REG_TGEN_CLK_GEN0_10_L       (REG_TGEN_CLK_GEN0_BASE + 0x20)
#define  REG_TGEN_CLK_GEN0_10_H       (REG_TGEN_CLK_GEN0_BASE + 0x21)
#define  REG_TGEN_CLK_GEN0_11_L       (REG_TGEN_CLK_GEN0_BASE + 0x22)
#define  REG_TGEN_CLK_GEN0_11_H       (REG_TGEN_CLK_GEN0_BASE + 0x23)
#define  REG_TGEN_CLK_GEN0_12_L       (REG_TGEN_CLK_GEN0_BASE + 0x24)
#define  REG_TGEN_CLK_GEN0_12_H       (REG_TGEN_CLK_GEN0_BASE + 0x25)
#define  REG_TGEN_CLK_GEN0_13_L       (REG_TGEN_CLK_GEN0_BASE + 0x26)
#define  REG_TGEN_CLK_GEN0_13_H       (REG_TGEN_CLK_GEN0_BASE + 0x27)
#define  REG_TGEN_CLK_GEN0_14_L       (REG_TGEN_CLK_GEN0_BASE + 0x28)
#define  REG_TGEN_CLK_GEN0_14_H       (REG_TGEN_CLK_GEN0_BASE + 0x29)
#define  REG_TGEN_CLK_GEN0_15_L       (REG_TGEN_CLK_GEN0_BASE + 0x2A)
#define  REG_TGEN_CLK_GEN0_15_H       (REG_TGEN_CLK_GEN0_BASE + 0x2B)
#define  REG_TGEN_CLK_GEN0_16_L       (REG_TGEN_CLK_GEN0_BASE + 0x2C)
#define  REG_TGEN_CLK_GEN0_16_H       (REG_TGEN_CLK_GEN0_BASE + 0x2D)
#define  REG_TGEN_CLK_GEN0_17_L       (REG_TGEN_CLK_GEN0_BASE + 0x2E)
#define  REG_TGEN_CLK_GEN0_17_H       (REG_TGEN_CLK_GEN0_BASE + 0x2F)
#define  REG_TGEN_CLK_GEN0_18_L       (REG_TGEN_CLK_GEN0_BASE + 0x30)
#define  REG_TGEN_CLK_GEN0_18_H       (REG_TGEN_CLK_GEN0_BASE + 0x31)
#define  REG_TGEN_CLK_GEN0_19_L       (REG_TGEN_CLK_GEN0_BASE + 0x32)
#define  REG_TGEN_CLK_GEN0_19_H       (REG_TGEN_CLK_GEN0_BASE + 0x33)
#define  REG_TGEN_CLK_GEN0_1A_L       (REG_TGEN_CLK_GEN0_BASE + 0x34)
#define  REG_TGEN_CLK_GEN0_1A_H       (REG_TGEN_CLK_GEN0_BASE + 0x35)
#define  REG_TGEN_CLK_GEN0_1B_L       (REG_TGEN_CLK_GEN0_BASE + 0x36)
#define  REG_TGEN_CLK_GEN0_1B_H       (REG_TGEN_CLK_GEN0_BASE + 0x37)
#define  REG_TGEN_CLK_GEN0_1C_L       (REG_TGEN_CLK_GEN0_BASE + 0x38)
#define  REG_TGEN_CLK_GEN0_1C_H       (REG_TGEN_CLK_GEN0_BASE + 0x39)
#define  REG_TGEN_CLK_GEN0_1D_L       (REG_TGEN_CLK_GEN0_BASE + 0x3A)
#define  REG_TGEN_CLK_GEN0_1D_H       (REG_TGEN_CLK_GEN0_BASE + 0x3B)
#define  REG_TGEN_CLK_GEN0_1E_L       (REG_TGEN_CLK_GEN0_BASE + 0x3C)
#define  REG_TGEN_CLK_GEN0_1E_H       (REG_TGEN_CLK_GEN0_BASE + 0x3D)
#define  REG_TGEN_CLK_GEN0_1F_L       (REG_TGEN_CLK_GEN0_BASE + 0x3E)
#define  REG_TGEN_CLK_GEN0_1F_H       (REG_TGEN_CLK_GEN0_BASE + 0x3F)
#define  REG_TGEN_CLK_GEN0_20_L       (REG_TGEN_CLK_GEN0_BASE + 0x40)
#define  REG_TGEN_CLK_GEN0_20_H       (REG_TGEN_CLK_GEN0_BASE + 0x41)
#define  REG_TGEN_CLK_GEN0_21_L       (REG_TGEN_CLK_GEN0_BASE + 0x42)
#define  REG_TGEN_CLK_GEN0_21_H       (REG_TGEN_CLK_GEN0_BASE + 0x43)
#define  REG_TGEN_CLK_GEN0_22_L       (REG_TGEN_CLK_GEN0_BASE + 0x44)
#define  REG_TGEN_CLK_GEN0_22_H       (REG_TGEN_CLK_GEN0_BASE + 0x45)
#define  REG_TGEN_CLK_GEN0_23_L       (REG_TGEN_CLK_GEN0_BASE + 0x46)
#define  REG_TGEN_CLK_GEN0_23_H       (REG_TGEN_CLK_GEN0_BASE + 0x47)
#define  REG_TGEN_CLK_GEN0_24_L       (REG_TGEN_CLK_GEN0_BASE + 0x48)
#define  REG_TGEN_CLK_GEN0_24_H       (REG_TGEN_CLK_GEN0_BASE + 0x49)
#define  REG_TGEN_CLK_GEN0_25_L       (REG_TGEN_CLK_GEN0_BASE + 0x4A)
#define  REG_TGEN_CLK_GEN0_25_H       (REG_TGEN_CLK_GEN0_BASE + 0x4B)
#define  REG_TGEN_CLK_GEN0_26_L       (REG_TGEN_CLK_GEN0_BASE + 0x4C)
#define  REG_TGEN_CLK_GEN0_26_H       (REG_TGEN_CLK_GEN0_BASE + 0x4D)
#define  REG_TGEN_CLK_GEN0_27_L       (REG_TGEN_CLK_GEN0_BASE + 0x4E)
#define  REG_TGEN_CLK_GEN0_27_H       (REG_TGEN_CLK_GEN0_BASE + 0x4F)
#define  REG_TGEN_CLK_GEN0_28_L       (REG_TGEN_CLK_GEN0_BASE + 0x50)
#define  REG_TGEN_CLK_GEN0_28_H       (REG_TGEN_CLK_GEN0_BASE + 0x51)
#define  REG_TGEN_CLK_GEN0_29_L       (REG_TGEN_CLK_GEN0_BASE + 0x52)
#define  REG_TGEN_CLK_GEN0_29_H       (REG_TGEN_CLK_GEN0_BASE + 0x53)
#define  REG_TGEN_CLK_GEN0_2A_L       (REG_TGEN_CLK_GEN0_BASE + 0x54)
#define  REG_TGEN_CLK_GEN0_2A_H       (REG_TGEN_CLK_GEN0_BASE + 0x55)
#define  REG_TGEN_CLK_GEN0_2B_L       (REG_TGEN_CLK_GEN0_BASE + 0x56)
#define  REG_TGEN_CLK_GEN0_2B_H       (REG_TGEN_CLK_GEN0_BASE + 0x57)
#define  REG_TGEN_CLK_GEN0_2C_L       (REG_TGEN_CLK_GEN0_BASE + 0x58)
#define  REG_TGEN_CLK_GEN0_2C_H       (REG_TGEN_CLK_GEN0_BASE + 0x59)
#define  REG_TGEN_CLK_GEN0_2D_L       (REG_TGEN_CLK_GEN0_BASE + 0x5A)
#define  REG_TGEN_CLK_GEN0_2D_H       (REG_TGEN_CLK_GEN0_BASE + 0x5B)
#define  REG_TGEN_CLK_GEN0_2E_L       (REG_TGEN_CLK_GEN0_BASE + 0x5C)
#define  REG_TGEN_CLK_GEN0_2E_H       (REG_TGEN_CLK_GEN0_BASE + 0x5D)
#define  REG_TGEN_CLK_GEN0_2F_L       (REG_TGEN_CLK_GEN0_BASE + 0x5E)
#define  REG_TGEN_CLK_GEN0_2F_H       (REG_TGEN_CLK_GEN0_BASE + 0x5F)
#define  REG_TGEN_CLK_GEN0_30_L       (REG_TGEN_CLK_GEN0_BASE + 0x60)
#define  REG_TGEN_CLK_GEN0_30_H       (REG_TGEN_CLK_GEN0_BASE + 0x61)
#define  REG_TGEN_CLK_GEN0_31_L       (REG_TGEN_CLK_GEN0_BASE + 0x62)
#define  REG_TGEN_CLK_GEN0_31_H       (REG_TGEN_CLK_GEN0_BASE + 0x63)
#define  REG_TGEN_CLK_GEN0_32_L       (REG_TGEN_CLK_GEN0_BASE + 0x64)
#define  REG_TGEN_CLK_GEN0_32_H       (REG_TGEN_CLK_GEN0_BASE + 0x65)
#define  REG_TGEN_CLK_GEN0_33_L       (REG_TGEN_CLK_GEN0_BASE + 0x66)
#define  REG_TGEN_CLK_GEN0_33_H       (REG_TGEN_CLK_GEN0_BASE + 0x67)
#define  REG_TGEN_CLK_GEN0_34_L       (REG_TGEN_CLK_GEN0_BASE + 0x68)
#define  REG_TGEN_CLK_GEN0_34_H       (REG_TGEN_CLK_GEN0_BASE + 0x69)
#define  REG_TGEN_CLK_GEN0_35_L       (REG_TGEN_CLK_GEN0_BASE + 0x6A)
#define  REG_TGEN_CLK_GEN0_35_H       (REG_TGEN_CLK_GEN0_BASE + 0x6B)
#define  REG_TGEN_CLK_GEN0_36_L       (REG_TGEN_CLK_GEN0_BASE + 0x6C)
#define  REG_TGEN_CLK_GEN0_36_H       (REG_TGEN_CLK_GEN0_BASE + 0x6D)
#define  REG_TGEN_CLK_GEN0_37_L       (REG_TGEN_CLK_GEN0_BASE + 0x6E)
#define  REG_TGEN_CLK_GEN0_37_H       (REG_TGEN_CLK_GEN0_BASE + 0x6F)
#define  REG_TGEN_CLK_GEN0_38_L       (REG_TGEN_CLK_GEN0_BASE + 0x70)
#define  REG_TGEN_CLK_GEN0_38_H       (REG_TGEN_CLK_GEN0_BASE + 0x71)
#define  REG_TGEN_CLK_GEN0_39_L       (REG_TGEN_CLK_GEN0_BASE + 0x72)
#define  REG_TGEN_CLK_GEN0_39_H       (REG_TGEN_CLK_GEN0_BASE + 0x73)
#define  REG_TGEN_CLK_GEN0_3A_L       (REG_TGEN_CLK_GEN0_BASE + 0x74)
#define  REG_TGEN_CLK_GEN0_3A_H       (REG_TGEN_CLK_GEN0_BASE + 0x75)
#define  REG_TGEN_CLK_GEN0_3B_L       (REG_TGEN_CLK_GEN0_BASE + 0x76)
#define  REG_TGEN_CLK_GEN0_3B_H       (REG_TGEN_CLK_GEN0_BASE + 0x77)
#define  REG_TGEN_CLK_GEN0_3C_L       (REG_TGEN_CLK_GEN0_BASE + 0x78)
#define  REG_TGEN_CLK_GEN0_3C_H       (REG_TGEN_CLK_GEN0_BASE + 0x79)
#define  REG_TGEN_CLK_GEN0_3D_L       (REG_TGEN_CLK_GEN0_BASE + 0x7A)
#define  REG_TGEN_CLK_GEN0_3D_H       (REG_TGEN_CLK_GEN0_BASE + 0x7B)
#define  REG_TGEN_CLK_GEN0_3E_L       (REG_TGEN_CLK_GEN0_BASE + 0x7C)
#define  REG_TGEN_CLK_GEN0_3E_H       (REG_TGEN_CLK_GEN0_BASE + 0x7D)
#define  REG_TGEN_CLK_GEN0_3F_L       (REG_TGEN_CLK_GEN0_BASE + 0x7E)
#define  REG_TGEN_CLK_GEN0_3F_H       (REG_TGEN_CLK_GEN0_BASE + 0x7F)
#define  REG_TGEN_CLK_GEN0_40_L       (REG_TGEN_CLK_GEN0_BASE + 0x80)
#define  REG_TGEN_CLK_GEN0_40_H       (REG_TGEN_CLK_GEN0_BASE + 0x81)
#define  REG_TGEN_CLK_GEN0_41_L       (REG_TGEN_CLK_GEN0_BASE + 0x82)
#define  REG_TGEN_CLK_GEN0_41_H       (REG_TGEN_CLK_GEN0_BASE + 0x83)
#define  REG_TGEN_CLK_GEN0_42_L       (REG_TGEN_CLK_GEN0_BASE + 0x84)
#define  REG_TGEN_CLK_GEN0_42_H       (REG_TGEN_CLK_GEN0_BASE + 0x85)
#define  REG_TGEN_CLK_GEN0_43_L       (REG_TGEN_CLK_GEN0_BASE + 0x86)
#define  REG_TGEN_CLK_GEN0_43_H       (REG_TGEN_CLK_GEN0_BASE + 0x87)
#define  REG_TGEN_CLK_GEN0_44_L       (REG_TGEN_CLK_GEN0_BASE + 0x88)
#define  REG_TGEN_CLK_GEN0_44_H       (REG_TGEN_CLK_GEN0_BASE + 0x89)
#define  REG_TGEN_CLK_GEN0_45_L       (REG_TGEN_CLK_GEN0_BASE + 0x8A)
#define  REG_TGEN_CLK_GEN0_45_H       (REG_TGEN_CLK_GEN0_BASE + 0x8B)
#define  REG_TGEN_CLK_GEN0_46_L       (REG_TGEN_CLK_GEN0_BASE + 0x8C)
#define  REG_TGEN_CLK_GEN0_46_H       (REG_TGEN_CLK_GEN0_BASE + 0x8D)
#define  REG_TGEN_CLK_GEN0_47_L       (REG_TGEN_CLK_GEN0_BASE + 0x8E)
#define  REG_TGEN_CLK_GEN0_47_H       (REG_TGEN_CLK_GEN0_BASE + 0x8F)
#define  REG_TGEN_CLK_GEN0_48_L       (REG_TGEN_CLK_GEN0_BASE + 0x90)
#define  REG_TGEN_CLK_GEN0_48_H       (REG_TGEN_CLK_GEN0_BASE + 0x91)
#define  REG_TGEN_CLK_GEN0_49_L       (REG_TGEN_CLK_GEN0_BASE + 0x92)
#define  REG_TGEN_CLK_GEN0_49_H       (REG_TGEN_CLK_GEN0_BASE + 0x93)
#define  REG_TGEN_CLK_GEN0_4A_L       (REG_TGEN_CLK_GEN0_BASE + 0x94)
#define  REG_TGEN_CLK_GEN0_4A_H       (REG_TGEN_CLK_GEN0_BASE + 0x95)
#define  REG_TGEN_CLK_GEN0_4B_L       (REG_TGEN_CLK_GEN0_BASE + 0x96)
#define  REG_TGEN_CLK_GEN0_4B_H       (REG_TGEN_CLK_GEN0_BASE + 0x97)
#define  REG_TGEN_CLK_GEN0_4C_L       (REG_TGEN_CLK_GEN0_BASE + 0x98)
#define  REG_TGEN_CLK_GEN0_4C_H       (REG_TGEN_CLK_GEN0_BASE + 0x99)
#define  REG_TGEN_CLK_GEN0_4D_L       (REG_TGEN_CLK_GEN0_BASE + 0x9A)
#define  REG_TGEN_CLK_GEN0_4D_H       (REG_TGEN_CLK_GEN0_BASE + 0x9B)
#define  REG_TGEN_CLK_GEN0_4E_L       (REG_TGEN_CLK_GEN0_BASE + 0x9C)
#define  REG_TGEN_CLK_GEN0_4E_H       (REG_TGEN_CLK_GEN0_BASE + 0x9D)
#define  REG_TGEN_CLK_GEN0_4F_L       (REG_TGEN_CLK_GEN0_BASE + 0x9E)
#define  REG_TGEN_CLK_GEN0_4F_H       (REG_TGEN_CLK_GEN0_BASE + 0x9F)
#define  REG_TGEN_CLK_GEN0_50_L       (REG_TGEN_CLK_GEN0_BASE + 0xA0)
#define  REG_TGEN_CLK_GEN0_50_H       (REG_TGEN_CLK_GEN0_BASE + 0xA1)
#define  REG_TGEN_CLK_GEN0_51_L       (REG_TGEN_CLK_GEN0_BASE + 0xA2)
#define  REG_TGEN_CLK_GEN0_51_H       (REG_TGEN_CLK_GEN0_BASE + 0xA3)
#define  REG_TGEN_CLK_GEN0_52_L       (REG_TGEN_CLK_GEN0_BASE + 0xA4)
#define  REG_TGEN_CLK_GEN0_52_H       (REG_TGEN_CLK_GEN0_BASE + 0xA5)
#define  REG_TGEN_CLK_GEN0_53_L       (REG_TGEN_CLK_GEN0_BASE + 0xA6)
#define  REG_TGEN_CLK_GEN0_53_H       (REG_TGEN_CLK_GEN0_BASE + 0xA7)
#define  REG_TGEN_CLK_GEN0_54_L       (REG_TGEN_CLK_GEN0_BASE + 0xA8)
#define  REG_TGEN_CLK_GEN0_54_H       (REG_TGEN_CLK_GEN0_BASE + 0xA9)
#define  REG_TGEN_CLK_GEN0_55_L       (REG_TGEN_CLK_GEN0_BASE + 0xAA)
#define  REG_TGEN_CLK_GEN0_55_H       (REG_TGEN_CLK_GEN0_BASE + 0xAB)
#define  REG_TGEN_CLK_GEN0_56_L       (REG_TGEN_CLK_GEN0_BASE + 0xAC)
#define  REG_TGEN_CLK_GEN0_56_H       (REG_TGEN_CLK_GEN0_BASE + 0xAD)
#define  REG_TGEN_CLK_GEN0_57_L       (REG_TGEN_CLK_GEN0_BASE + 0xAE)
#define  REG_TGEN_CLK_GEN0_57_H       (REG_TGEN_CLK_GEN0_BASE + 0xAF)
#define  REG_TGEN_CLK_GEN0_58_L       (REG_TGEN_CLK_GEN0_BASE + 0xB0)
#define  REG_TGEN_CLK_GEN0_58_H       (REG_TGEN_CLK_GEN0_BASE + 0xB1)
#define  REG_TGEN_CLK_GEN0_59_L       (REG_TGEN_CLK_GEN0_BASE + 0xB2)
#define  REG_TGEN_CLK_GEN0_59_H       (REG_TGEN_CLK_GEN0_BASE + 0xB3)
#define  REG_TGEN_CLK_GEN0_5A_L       (REG_TGEN_CLK_GEN0_BASE + 0xB4)
#define  REG_TGEN_CLK_GEN0_5A_H       (REG_TGEN_CLK_GEN0_BASE + 0xB5)
#define  REG_TGEN_CLK_GEN0_5B_L       (REG_TGEN_CLK_GEN0_BASE + 0xB6)
#define  REG_TGEN_CLK_GEN0_5B_H       (REG_TGEN_CLK_GEN0_BASE + 0xB7)
#define  REG_TGEN_CLK_GEN0_5C_L       (REG_TGEN_CLK_GEN0_BASE + 0xB8)
#define  REG_TGEN_CLK_GEN0_5C_H       (REG_TGEN_CLK_GEN0_BASE + 0xB9)
#define  REG_TGEN_CLK_GEN0_5D_L       (REG_TGEN_CLK_GEN0_BASE + 0xBA)
#define  REG_TGEN_CLK_GEN0_5D_H       (REG_TGEN_CLK_GEN0_BASE + 0xBB)
#define  REG_TGEN_CLK_GEN0_5E_L       (REG_TGEN_CLK_GEN0_BASE + 0xBC)
#define  REG_TGEN_CLK_GEN0_5E_H       (REG_TGEN_CLK_GEN0_BASE + 0xBD)
#define  REG_TGEN_CLK_GEN0_5F_L       (REG_TGEN_CLK_GEN0_BASE + 0xBE)
#define  REG_TGEN_CLK_GEN0_5F_H       (REG_TGEN_CLK_GEN0_BASE + 0xBF)
#define  REG_TGEN_CLK_GEN0_60_L       (REG_TGEN_CLK_GEN0_BASE + 0xC0)
#define  REG_TGEN_CLK_GEN0_60_H       (REG_TGEN_CLK_GEN0_BASE + 0xC1)
#define  REG_TGEN_CLK_GEN0_61_L       (REG_TGEN_CLK_GEN0_BASE + 0xC2)
#define  REG_TGEN_CLK_GEN0_61_H       (REG_TGEN_CLK_GEN0_BASE + 0xC3)
#define  REG_TGEN_CLK_GEN0_62_L       (REG_TGEN_CLK_GEN0_BASE + 0xC4)
#define  REG_TGEN_CLK_GEN0_62_H       (REG_TGEN_CLK_GEN0_BASE + 0xC5)
#define  REG_TGEN_CLK_GEN0_63_L       (REG_TGEN_CLK_GEN0_BASE + 0xC6)
#define  REG_TGEN_CLK_GEN0_63_H       (REG_TGEN_CLK_GEN0_BASE + 0xC7)
#define  REG_TGEN_CLK_GEN0_64_L       (REG_TGEN_CLK_GEN0_BASE + 0xC8)
#define  REG_TGEN_CLK_GEN0_64_H       (REG_TGEN_CLK_GEN0_BASE + 0xC9)
#define  REG_TGEN_CLK_GEN0_65_L       (REG_TGEN_CLK_GEN0_BASE + 0xCA)
#define  REG_TGEN_CLK_GEN0_65_H       (REG_TGEN_CLK_GEN0_BASE + 0xCB)
#define  REG_TGEN_CLK_GEN0_66_L       (REG_TGEN_CLK_GEN0_BASE + 0xCC)
#define  REG_TGEN_CLK_GEN0_66_H       (REG_TGEN_CLK_GEN0_BASE + 0xCD)
#define  REG_TGEN_CLK_GEN0_67_L       (REG_TGEN_CLK_GEN0_BASE + 0xCE)
#define  REG_TGEN_CLK_GEN0_67_H       (REG_TGEN_CLK_GEN0_BASE + 0xCF)
#define  REG_TGEN_CLK_GEN0_68_L       (REG_TGEN_CLK_GEN0_BASE + 0xD0)
#define  REG_TGEN_CLK_GEN0_68_H       (REG_TGEN_CLK_GEN0_BASE + 0xD1)
#define  REG_TGEN_CLK_GEN0_69_L       (REG_TGEN_CLK_GEN0_BASE + 0xD2)
#define  REG_TGEN_CLK_GEN0_69_H       (REG_TGEN_CLK_GEN0_BASE + 0xD3)
#define  REG_TGEN_CLK_GEN0_6A_L       (REG_TGEN_CLK_GEN0_BASE + 0xD4)
#define  REG_TGEN_CLK_GEN0_6A_H       (REG_TGEN_CLK_GEN0_BASE + 0xD5)
#define  REG_TGEN_CLK_GEN0_6B_L       (REG_TGEN_CLK_GEN0_BASE + 0xD6)
#define  REG_TGEN_CLK_GEN0_6B_H       (REG_TGEN_CLK_GEN0_BASE + 0xD7)
#define  REG_TGEN_CLK_GEN0_6C_L       (REG_TGEN_CLK_GEN0_BASE + 0xD8)
#define  REG_TGEN_CLK_GEN0_6C_H       (REG_TGEN_CLK_GEN0_BASE + 0xD9)
#define  REG_TGEN_CLK_GEN0_6D_L       (REG_TGEN_CLK_GEN0_BASE + 0xDA)
#define  REG_TGEN_CLK_GEN0_6D_H       (REG_TGEN_CLK_GEN0_BASE + 0xDB)
#define  REG_TGEN_CLK_GEN0_6E_L       (REG_TGEN_CLK_GEN0_BASE + 0xDC)
#define  REG_TGEN_CLK_GEN0_6E_H       (REG_TGEN_CLK_GEN0_BASE + 0xDD)
#define  REG_TGEN_CLK_GEN0_6F_L       (REG_TGEN_CLK_GEN0_BASE + 0xDE)
#define  REG_TGEN_CLK_GEN0_6F_H       (REG_TGEN_CLK_GEN0_BASE + 0xDF)
#define  REG_TGEN_CLK_GEN0_70_L       (REG_TGEN_CLK_GEN0_BASE + 0xE0)
#define  REG_TGEN_CLK_GEN0_70_H       (REG_TGEN_CLK_GEN0_BASE + 0xE1)
#define  REG_TGEN_CLK_GEN0_71_L       (REG_TGEN_CLK_GEN0_BASE + 0xE2)
#define  REG_TGEN_CLK_GEN0_71_H       (REG_TGEN_CLK_GEN0_BASE + 0xE3)
#define  REG_TGEN_CLK_GEN0_72_L       (REG_TGEN_CLK_GEN0_BASE + 0xE4)
#define  REG_TGEN_CLK_GEN0_72_H       (REG_TGEN_CLK_GEN0_BASE + 0xE5)
#define  REG_TGEN_CLK_GEN0_73_L       (REG_TGEN_CLK_GEN0_BASE + 0xE6)
#define  REG_TGEN_CLK_GEN0_73_H       (REG_TGEN_CLK_GEN0_BASE + 0xE7)
#define  REG_TGEN_CLK_GEN0_74_L       (REG_TGEN_CLK_GEN0_BASE + 0xE8)
#define  REG_TGEN_CLK_GEN0_74_H       (REG_TGEN_CLK_GEN0_BASE + 0xE9)
#define  REG_TGEN_CLK_GEN0_75_L       (REG_TGEN_CLK_GEN0_BASE + 0xEA)
#define  REG_TGEN_CLK_GEN0_75_H       (REG_TGEN_CLK_GEN0_BASE + 0xEB)
#define  REG_TGEN_CLK_GEN0_76_L       (REG_TGEN_CLK_GEN0_BASE + 0xEC)
#define  REG_TGEN_CLK_GEN0_76_H       (REG_TGEN_CLK_GEN0_BASE + 0xED)
#define  REG_TGEN_CLK_GEN0_77_L       (REG_TGEN_CLK_GEN0_BASE + 0xEE)
#define  REG_TGEN_CLK_GEN0_77_H       (REG_TGEN_CLK_GEN0_BASE + 0xEF)
#define  REG_TGEN_CLK_GEN0_78_L       (REG_TGEN_CLK_GEN0_BASE + 0xF0)
#define  REG_TGEN_CLK_GEN0_78_H       (REG_TGEN_CLK_GEN0_BASE + 0xF1)
#define  REG_TGEN_CLK_GEN0_79_L       (REG_TGEN_CLK_GEN0_BASE + 0xF2)
#define  REG_TGEN_CLK_GEN0_79_H       (REG_TGEN_CLK_GEN0_BASE + 0xF3)
#define  REG_TGEN_CLK_GEN0_7A_L       (REG_TGEN_CLK_GEN0_BASE + 0xF4)
#define  REG_TGEN_CLK_GEN0_7A_H       (REG_TGEN_CLK_GEN0_BASE + 0xF5)
#define  REG_TGEN_CLK_GEN0_7B_L       (REG_TGEN_CLK_GEN0_BASE + 0xF6)
#define  REG_TGEN_CLK_GEN0_7B_H       (REG_TGEN_CLK_GEN0_BASE + 0xF7)
#define  REG_TGEN_CLK_GEN0_7C_L       (REG_TGEN_CLK_GEN0_BASE + 0xF8)
#define  REG_TGEN_CLK_GEN0_7C_H       (REG_TGEN_CLK_GEN0_BASE + 0xF9)
#define  REG_TGEN_CLK_GEN0_7D_L       (REG_TGEN_CLK_GEN0_BASE + 0xFA)
#define  REG_TGEN_CLK_GEN0_7D_H       (REG_TGEN_CLK_GEN0_BASE + 0xFB)
#define  REG_TGEN_CLK_GEN0_7E_L       (REG_TGEN_CLK_GEN0_BASE + 0xFC)
#define  REG_TGEN_CLK_GEN0_7E_H       (REG_TGEN_CLK_GEN0_BASE + 0xFD)
#define  REG_TGEN_CLK_GEN0_7F_L       (REG_TGEN_CLK_GEN0_BASE + 0xFE)
#define  REG_TGEN_CLK_GEN0_7F_H       (REG_TGEN_CLK_GEN0_BASE + 0xFF)

#define  REG_TGEN_SC1_VOP_BK90_00_L       _TGEN_PK_L_(0x90, 0x00)
#define  REG_TGEN_SC1_VOP_BK90_00_H       _TGEN_PK_H_(0x90, 0x00)
#define  REG_TGEN_SC1_VOP_BK90_01_L       _TGEN_PK_L_(0x90, 0x01)
#define  REG_TGEN_SC1_VOP_BK90_01_H       _TGEN_PK_H_(0x90, 0x01)
#define  REG_TGEN_SC1_VOP_BK90_02_L       _TGEN_PK_L_(0x90, 0x02)
#define  REG_TGEN_SC1_VOP_BK90_02_H       _TGEN_PK_H_(0x90, 0x02)
#define  REG_TGEN_SC1_VOP_BK90_03_L       _TGEN_PK_L_(0x90, 0x03)
#define  REG_TGEN_SC1_VOP_BK90_03_H       _TGEN_PK_H_(0x90, 0x03)
#define  REG_TGEN_SC1_VOP_BK90_04_L       _TGEN_PK_L_(0x90, 0x04)
#define  REG_TGEN_SC1_VOP_BK90_04_H       _TGEN_PK_H_(0x90, 0x04)
#define  REG_TGEN_SC1_VOP_BK90_05_L       _TGEN_PK_L_(0x90, 0x05)
#define  REG_TGEN_SC1_VOP_BK90_05_H       _TGEN_PK_H_(0x90, 0x05)
#define  REG_TGEN_SC1_VOP_BK90_06_L       _TGEN_PK_L_(0x90, 0x06)
#define  REG_TGEN_SC1_VOP_BK90_06_H       _TGEN_PK_H_(0x90, 0x06)
#define  REG_TGEN_SC1_VOP_BK90_07_L       _TGEN_PK_L_(0x90, 0x07)
#define  REG_TGEN_SC1_VOP_BK90_07_H       _TGEN_PK_H_(0x90, 0x07)
#define  REG_TGEN_SC1_VOP_BK90_08_L       _TGEN_PK_L_(0x90, 0x08)
#define  REG_TGEN_SC1_VOP_BK90_08_H       _TGEN_PK_H_(0x90, 0x08)
#define  REG_TGEN_SC1_VOP_BK90_09_L       _TGEN_PK_L_(0x90, 0x09)
#define  REG_TGEN_SC1_VOP_BK90_09_H       _TGEN_PK_H_(0x90, 0x09)
#define  REG_TGEN_SC1_VOP_BK90_0A_L       _TGEN_PK_L_(0x90, 0x0A)
#define  REG_TGEN_SC1_VOP_BK90_0A_H       _TGEN_PK_H_(0x90, 0x0A)
#define  REG_TGEN_SC1_VOP_BK90_0B_L       _TGEN_PK_L_(0x90, 0x0B)
#define  REG_TGEN_SC1_VOP_BK90_0B_H       _TGEN_PK_H_(0x90, 0x0B)
#define  REG_TGEN_SC1_VOP_BK90_0C_L       _TGEN_PK_L_(0x90, 0x0C)
#define  REG_TGEN_SC1_VOP_BK90_0C_H       _TGEN_PK_H_(0x90, 0x0C)
#define  REG_TGEN_SC1_VOP_BK90_0D_L       _TGEN_PK_L_(0x90, 0x0D)
#define  REG_TGEN_SC1_VOP_BK90_0D_H       _TGEN_PK_H_(0x90, 0x0D)
#define  REG_TGEN_SC1_VOP_BK90_0E_L       _TGEN_PK_L_(0x90, 0x0E)
#define  REG_TGEN_SC1_VOP_BK90_0E_H       _TGEN_PK_H_(0x90, 0x0E)
#define  REG_TGEN_SC1_VOP_BK90_0F_L       _TGEN_PK_L_(0x90, 0x0F)
#define  REG_TGEN_SC1_VOP_BK90_0F_H       _TGEN_PK_H_(0x90, 0x0F)
#define  REG_TGEN_SC1_VOP_BK90_10_L       _TGEN_PK_L_(0x90, 0x10)
#define  REG_TGEN_SC1_VOP_BK90_10_H       _TGEN_PK_H_(0x90, 0x10)
#define  REG_TGEN_SC1_VOP_BK90_11_L       _TGEN_PK_L_(0x90, 0x11)
#define  REG_TGEN_SC1_VOP_BK90_11_H       _TGEN_PK_H_(0x90, 0x11)
#define  REG_TGEN_SC1_VOP_BK90_12_L       _TGEN_PK_L_(0x90, 0x12)
#define  REG_TGEN_SC1_VOP_BK90_12_H       _TGEN_PK_H_(0x90, 0x12)
#define  REG_TGEN_SC1_VOP_BK90_13_L       _TGEN_PK_L_(0x90, 0x13)
#define  REG_TGEN_SC1_VOP_BK90_13_H       _TGEN_PK_H_(0x90, 0x13)
#define  REG_TGEN_SC1_VOP_BK90_14_L       _TGEN_PK_L_(0x90, 0x14)
#define  REG_TGEN_SC1_VOP_BK90_14_H       _TGEN_PK_H_(0x90, 0x14)
#define  REG_TGEN_SC1_VOP_BK90_15_L       _TGEN_PK_L_(0x90, 0x15)
#define  REG_TGEN_SC1_VOP_BK90_15_H       _TGEN_PK_H_(0x90, 0x15)
#define  REG_TGEN_SC1_VOP_BK90_16_L       _TGEN_PK_L_(0x90, 0x16)
#define  REG_TGEN_SC1_VOP_BK90_16_H       _TGEN_PK_H_(0x90, 0x16)
#define  REG_TGEN_SC1_VOP_BK90_17_L       _TGEN_PK_L_(0x90, 0x17)
#define  REG_TGEN_SC1_VOP_BK90_17_H       _TGEN_PK_H_(0x90, 0x17)
#define  REG_TGEN_SC1_VOP_BK90_18_L       _TGEN_PK_L_(0x90, 0x18)
#define  REG_TGEN_SC1_VOP_BK90_18_H       _TGEN_PK_H_(0x90, 0x18)
#define  REG_TGEN_SC1_VOP_BK90_19_L       _TGEN_PK_L_(0x90, 0x19)
#define  REG_TGEN_SC1_VOP_BK90_19_H       _TGEN_PK_H_(0x90, 0x19)
#define  REG_TGEN_SC1_VOP_BK90_1A_L       _TGEN_PK_L_(0x90, 0x1A)
#define  REG_TGEN_SC1_VOP_BK90_1A_H       _TGEN_PK_H_(0x90, 0x1A)
#define  REG_TGEN_SC1_VOP_BK90_1B_L       _TGEN_PK_L_(0x90, 0x1B)
#define  REG_TGEN_SC1_VOP_BK90_1B_H       _TGEN_PK_H_(0x90, 0x1B)
#define  REG_TGEN_SC1_VOP_BK90_1C_L       _TGEN_PK_L_(0x90, 0x1C)
#define  REG_TGEN_SC1_VOP_BK90_1C_H       _TGEN_PK_H_(0x90, 0x1C)
#define  REG_TGEN_SC1_VOP_BK90_1D_L       _TGEN_PK_L_(0x90, 0x1D)
#define  REG_TGEN_SC1_VOP_BK90_1D_H       _TGEN_PK_H_(0x90, 0x1D)
#define  REG_TGEN_SC1_VOP_BK90_1E_L       _TGEN_PK_L_(0x90, 0x1E)
#define  REG_TGEN_SC1_VOP_BK90_1E_H       _TGEN_PK_H_(0x90, 0x1E)
#define  REG_TGEN_SC1_VOP_BK90_1F_L       _TGEN_PK_L_(0x90, 0x1F)
#define  REG_TGEN_SC1_VOP_BK90_1F_H       _TGEN_PK_H_(0x90, 0x1F)
#define  REG_TGEN_SC1_VOP_BK90_20_L       _TGEN_PK_L_(0x90, 0x20)
#define  REG_TGEN_SC1_VOP_BK90_20_H       _TGEN_PK_H_(0x90, 0x20)
#define  REG_TGEN_SC1_VOP_BK90_21_L       _TGEN_PK_L_(0x90, 0x21)
#define  REG_TGEN_SC1_VOP_BK90_21_H       _TGEN_PK_H_(0x90, 0x21)
#define  REG_TGEN_SC1_VOP_BK90_22_L       _TGEN_PK_L_(0x90, 0x22)
#define  REG_TGEN_SC1_VOP_BK90_22_H       _TGEN_PK_H_(0x90, 0x22)
#define  REG_TGEN_SC1_VOP_BK90_23_L       _TGEN_PK_L_(0x90, 0x23)
#define  REG_TGEN_SC1_VOP_BK90_23_H       _TGEN_PK_H_(0x90, 0x23)
#define  REG_TGEN_SC1_VOP_BK90_24_L       _TGEN_PK_L_(0x90, 0x24)
#define  REG_TGEN_SC1_VOP_BK90_24_H       _TGEN_PK_H_(0x90, 0x24)
#define  REG_TGEN_SC1_VOP_BK90_25_L       _TGEN_PK_L_(0x90, 0x25)
#define  REG_TGEN_SC1_VOP_BK90_25_H       _TGEN_PK_H_(0x90, 0x25)
#define  REG_TGEN_SC1_VOP_BK90_26_L       _TGEN_PK_L_(0x90, 0x26)
#define  REG_TGEN_SC1_VOP_BK90_26_H       _TGEN_PK_H_(0x90, 0x26)
#define  REG_TGEN_SC1_VOP_BK90_27_L       _TGEN_PK_L_(0x90, 0x27)
#define  REG_TGEN_SC1_VOP_BK90_27_H       _TGEN_PK_H_(0x90, 0x27)
#define  REG_TGEN_SC1_VOP_BK90_28_L       _TGEN_PK_L_(0x90, 0x28)
#define  REG_TGEN_SC1_VOP_BK90_28_H       _TGEN_PK_H_(0x90, 0x28)
#define  REG_TGEN_SC1_VOP_BK90_29_L       _TGEN_PK_L_(0x90, 0x29)
#define  REG_TGEN_SC1_VOP_BK90_29_H       _TGEN_PK_H_(0x90, 0x29)
#define  REG_TGEN_SC1_VOP_BK90_2A_L       _TGEN_PK_L_(0x90, 0x2A)
#define  REG_TGEN_SC1_VOP_BK90_2A_H       _TGEN_PK_H_(0x90, 0x2A)
#define  REG_TGEN_SC1_VOP_BK90_2B_L       _TGEN_PK_L_(0x90, 0x2B)
#define  REG_TGEN_SC1_VOP_BK90_2B_H       _TGEN_PK_H_(0x90, 0x2B)
#define  REG_TGEN_SC1_VOP_BK90_2C_L       _TGEN_PK_L_(0x90, 0x2C)
#define  REG_TGEN_SC1_VOP_BK90_2C_H       _TGEN_PK_H_(0x90, 0x2C)
#define  REG_TGEN_SC1_VOP_BK90_2D_L       _TGEN_PK_L_(0x90, 0x2D)
#define  REG_TGEN_SC1_VOP_BK90_2D_H       _TGEN_PK_H_(0x90, 0x2D)
#define  REG_TGEN_SC1_VOP_BK90_2E_L       _TGEN_PK_L_(0x90, 0x2E)
#define  REG_TGEN_SC1_VOP_BK90_2E_H       _TGEN_PK_H_(0x90, 0x2E)
#define  REG_TGEN_SC1_VOP_BK90_2F_L       _TGEN_PK_L_(0x90, 0x2F)
#define  REG_TGEN_SC1_VOP_BK90_2F_H       _TGEN_PK_H_(0x90, 0x2F)
#define  REG_TGEN_SC1_VOP_BK90_30_L       _TGEN_PK_L_(0x90, 0x30)
#define  REG_TGEN_SC1_VOP_BK90_30_H       _TGEN_PK_H_(0x90, 0x30)
#define  REG_TGEN_SC1_VOP_BK90_31_L       _TGEN_PK_L_(0x90, 0x31)
#define  REG_TGEN_SC1_VOP_BK90_31_H       _TGEN_PK_H_(0x90, 0x31)
#define  REG_TGEN_SC1_VOP_BK90_32_L       _TGEN_PK_L_(0x90, 0x32)
#define  REG_TGEN_SC1_VOP_BK90_32_H       _TGEN_PK_H_(0x90, 0x32)
#define  REG_TGEN_SC1_VOP_BK90_33_L       _TGEN_PK_L_(0x90, 0x33)
#define  REG_TGEN_SC1_VOP_BK90_33_H       _TGEN_PK_H_(0x90, 0x33)
#define  REG_TGEN_SC1_VOP_BK90_34_L       _TGEN_PK_L_(0x90, 0x34)
#define  REG_TGEN_SC1_VOP_BK90_34_H       _TGEN_PK_H_(0x90, 0x34)
#define  REG_TGEN_SC1_VOP_BK90_35_L       _TGEN_PK_L_(0x90, 0x35)
#define  REG_TGEN_SC1_VOP_BK90_35_H       _TGEN_PK_H_(0x90, 0x35)
#define  REG_TGEN_SC1_VOP_BK90_36_L       _TGEN_PK_L_(0x90, 0x36)
#define  REG_TGEN_SC1_VOP_BK90_36_H       _TGEN_PK_H_(0x90, 0x36)
#define  REG_TGEN_SC1_VOP_BK90_37_L       _TGEN_PK_L_(0x90, 0x37)
#define  REG_TGEN_SC1_VOP_BK90_37_H       _TGEN_PK_H_(0x90, 0x37)
#define  REG_TGEN_SC1_VOP_BK90_38_L       _TGEN_PK_L_(0x90, 0x38)
#define  REG_TGEN_SC1_VOP_BK90_38_H       _TGEN_PK_H_(0x90, 0x38)
#define  REG_TGEN_SC1_VOP_BK90_39_L       _TGEN_PK_L_(0x90, 0x39)
#define  REG_TGEN_SC1_VOP_BK90_39_H       _TGEN_PK_H_(0x90, 0x39)
#define  REG_TGEN_SC1_VOP_BK90_3A_L       _TGEN_PK_L_(0x90, 0x3A)
#define  REG_TGEN_SC1_VOP_BK90_3A_H       _TGEN_PK_H_(0x90, 0x3A)
#define  REG_TGEN_SC1_VOP_BK90_3B_L       _TGEN_PK_L_(0x90, 0x3B)
#define  REG_TGEN_SC1_VOP_BK90_3B_H       _TGEN_PK_H_(0x90, 0x3B)
#define  REG_TGEN_SC1_VOP_BK90_3C_L       _TGEN_PK_L_(0x90, 0x3C)
#define  REG_TGEN_SC1_VOP_BK90_3C_H       _TGEN_PK_H_(0x90, 0x3C)
#define  REG_TGEN_SC1_VOP_BK90_3D_L       _TGEN_PK_L_(0x90, 0x3D)
#define  REG_TGEN_SC1_VOP_BK90_3D_H       _TGEN_PK_H_(0x90, 0x3D)
#define  REG_TGEN_SC1_VOP_BK90_3E_L       _TGEN_PK_L_(0x90, 0x3E)
#define  REG_TGEN_SC1_VOP_BK90_3E_H       _TGEN_PK_H_(0x90, 0x3E)
#define  REG_TGEN_SC1_VOP_BK90_3F_L       _TGEN_PK_L_(0x90, 0x3F)
#define  REG_TGEN_SC1_VOP_BK90_3F_H       _TGEN_PK_H_(0x90, 0x3F)
#define  REG_TGEN_SC1_VOP_BK90_40_L       _TGEN_PK_L_(0x90, 0x40)
#define  REG_TGEN_SC1_VOP_BK90_40_H       _TGEN_PK_H_(0x90, 0x40)
#define  REG_TGEN_SC1_VOP_BK90_41_L       _TGEN_PK_L_(0x90, 0x41)
#define  REG_TGEN_SC1_VOP_BK90_41_H       _TGEN_PK_H_(0x90, 0x41)
#define  REG_TGEN_SC1_VOP_BK90_42_L       _TGEN_PK_L_(0x90, 0x42)
#define  REG_TGEN_SC1_VOP_BK90_42_H       _TGEN_PK_H_(0x90, 0x42)
#define  REG_TGEN_SC1_VOP_BK90_43_L       _TGEN_PK_L_(0x90, 0x43)
#define  REG_TGEN_SC1_VOP_BK90_43_H       _TGEN_PK_H_(0x90, 0x43)
#define  REG_TGEN_SC1_VOP_BK90_44_L       _TGEN_PK_L_(0x90, 0x44)
#define  REG_TGEN_SC1_VOP_BK90_44_H       _TGEN_PK_H_(0x90, 0x44)
#define  REG_TGEN_SC1_VOP_BK90_45_L       _TGEN_PK_L_(0x90, 0x45)
#define  REG_TGEN_SC1_VOP_BK90_45_H       _TGEN_PK_H_(0x90, 0x45)
#define  REG_TGEN_SC1_VOP_BK90_46_L       _TGEN_PK_L_(0x90, 0x46)
#define  REG_TGEN_SC1_VOP_BK90_46_H       _TGEN_PK_H_(0x90, 0x46)
#define  REG_TGEN_SC1_VOP_BK90_47_L       _TGEN_PK_L_(0x90, 0x47)
#define  REG_TGEN_SC1_VOP_BK90_47_H       _TGEN_PK_H_(0x90, 0x47)
#define  REG_TGEN_SC1_VOP_BK90_48_L       _TGEN_PK_L_(0x90, 0x48)
#define  REG_TGEN_SC1_VOP_BK90_48_H       _TGEN_PK_H_(0x90, 0x48)
#define  REG_TGEN_SC1_VOP_BK90_49_L       _TGEN_PK_L_(0x90, 0x49)
#define  REG_TGEN_SC1_VOP_BK90_49_H       _TGEN_PK_H_(0x90, 0x49)
#define  REG_TGEN_SC1_VOP_BK90_4A_L       _TGEN_PK_L_(0x90, 0x4A)
#define  REG_TGEN_SC1_VOP_BK90_4A_H       _TGEN_PK_H_(0x90, 0x4A)
#define  REG_TGEN_SC1_VOP_BK90_4B_L       _TGEN_PK_L_(0x90, 0x4B)
#define  REG_TGEN_SC1_VOP_BK90_4B_H       _TGEN_PK_H_(0x90, 0x4B)
#define  REG_TGEN_SC1_VOP_BK90_4C_L       _TGEN_PK_L_(0x90, 0x4C)
#define  REG_TGEN_SC1_VOP_BK90_4C_H       _TGEN_PK_H_(0x90, 0x4C)
#define  REG_TGEN_SC1_VOP_BK90_4D_L       _TGEN_PK_L_(0x90, 0x4D)
#define  REG_TGEN_SC1_VOP_BK90_4D_H       _TGEN_PK_H_(0x90, 0x4D)
#define  REG_TGEN_SC1_VOP_BK90_4E_L       _TGEN_PK_L_(0x90, 0x4E)
#define  REG_TGEN_SC1_VOP_BK90_4E_H       _TGEN_PK_H_(0x90, 0x4E)
#define  REG_TGEN_SC1_VOP_BK90_4F_L       _TGEN_PK_L_(0x90, 0x4F)
#define  REG_TGEN_SC1_VOP_BK90_4F_H       _TGEN_PK_H_(0x90, 0x4F)
#define  REG_TGEN_SC1_VOP_BK90_50_L       _TGEN_PK_L_(0x90, 0x50)
#define  REG_TGEN_SC1_VOP_BK90_50_H       _TGEN_PK_H_(0x90, 0x50)
#define  REG_TGEN_SC1_VOP_BK90_51_L       _TGEN_PK_L_(0x90, 0x51)
#define  REG_TGEN_SC1_VOP_BK90_51_H       _TGEN_PK_H_(0x90, 0x51)
#define  REG_TGEN_SC1_VOP_BK90_52_L       _TGEN_PK_L_(0x90, 0x52)
#define  REG_TGEN_SC1_VOP_BK90_52_H       _TGEN_PK_H_(0x90, 0x52)
#define  REG_TGEN_SC1_VOP_BK90_53_L       _TGEN_PK_L_(0x90, 0x53)
#define  REG_TGEN_SC1_VOP_BK90_53_H       _TGEN_PK_H_(0x90, 0x53)
#define  REG_TGEN_SC1_VOP_BK90_54_L       _TGEN_PK_L_(0x90, 0x54)
#define  REG_TGEN_SC1_VOP_BK90_54_H       _TGEN_PK_H_(0x90, 0x54)
#define  REG_TGEN_SC1_VOP_BK90_55_L       _TGEN_PK_L_(0x90, 0x55)
#define  REG_TGEN_SC1_VOP_BK90_55_H       _TGEN_PK_H_(0x90, 0x55)
#define  REG_TGEN_SC1_VOP_BK90_56_L       _TGEN_PK_L_(0x90, 0x56)
#define  REG_TGEN_SC1_VOP_BK90_56_H       _TGEN_PK_H_(0x90, 0x56)
#define  REG_TGEN_SC1_VOP_BK90_57_L       _TGEN_PK_L_(0x90, 0x57)
#define  REG_TGEN_SC1_VOP_BK90_57_H       _TGEN_PK_H_(0x90, 0x57)
#define  REG_TGEN_SC1_VOP_BK90_58_L       _TGEN_PK_L_(0x90, 0x58)
#define  REG_TGEN_SC1_VOP_BK90_58_H       _TGEN_PK_H_(0x90, 0x58)
#define  REG_TGEN_SC1_VOP_BK90_59_L       _TGEN_PK_L_(0x90, 0x59)
#define  REG_TGEN_SC1_VOP_BK90_59_H       _TGEN_PK_H_(0x90, 0x59)
#define  REG_TGEN_SC1_VOP_BK90_5A_L       _TGEN_PK_L_(0x90, 0x5A)
#define  REG_TGEN_SC1_VOP_BK90_5A_H       _TGEN_PK_H_(0x90, 0x5A)
#define  REG_TGEN_SC1_VOP_BK90_5B_L       _TGEN_PK_L_(0x90, 0x5B)
#define  REG_TGEN_SC1_VOP_BK90_5B_H       _TGEN_PK_H_(0x90, 0x5B)
#define  REG_TGEN_SC1_VOP_BK90_5C_L       _TGEN_PK_L_(0x90, 0x5C)
#define  REG_TGEN_SC1_VOP_BK90_5C_H       _TGEN_PK_H_(0x90, 0x5C)
#define  REG_TGEN_SC1_VOP_BK90_5D_L       _TGEN_PK_L_(0x90, 0x5D)
#define  REG_TGEN_SC1_VOP_BK90_5D_H       _TGEN_PK_H_(0x90, 0x5D)
#define  REG_TGEN_SC1_VOP_BK90_5E_L       _TGEN_PK_L_(0x90, 0x5E)
#define  REG_TGEN_SC1_VOP_BK90_5E_H       _TGEN_PK_H_(0x90, 0x5E)
#define  REG_TGEN_SC1_VOP_BK90_5F_L       _TGEN_PK_L_(0x90, 0x5F)
#define  REG_TGEN_SC1_VOP_BK90_5F_H       _TGEN_PK_H_(0x90, 0x5F)
#define  REG_TGEN_SC1_VOP_BK90_60_L       _TGEN_PK_L_(0x90, 0x60)
#define  REG_TGEN_SC1_VOP_BK90_60_H       _TGEN_PK_H_(0x90, 0x60)
#define  REG_TGEN_SC1_VOP_BK90_61_L       _TGEN_PK_L_(0x90, 0x61)
#define  REG_TGEN_SC1_VOP_BK90_61_H       _TGEN_PK_H_(0x90, 0x61)
#define  REG_TGEN_SC1_VOP_BK90_62_L       _TGEN_PK_L_(0x90, 0x62)
#define  REG_TGEN_SC1_VOP_BK90_62_H       _TGEN_PK_H_(0x90, 0x62)
#define  REG_TGEN_SC1_VOP_BK90_63_L       _TGEN_PK_L_(0x90, 0x63)
#define  REG_TGEN_SC1_VOP_BK90_63_H       _TGEN_PK_H_(0x90, 0x63)
#define  REG_TGEN_SC1_VOP_BK90_64_L       _TGEN_PK_L_(0x90, 0x64)
#define  REG_TGEN_SC1_VOP_BK90_64_H       _TGEN_PK_H_(0x90, 0x64)
#define  REG_TGEN_SC1_VOP_BK90_65_L       _TGEN_PK_L_(0x90, 0x65)
#define  REG_TGEN_SC1_VOP_BK90_65_H       _TGEN_PK_H_(0x90, 0x65)
#define  REG_TGEN_SC1_VOP_BK90_66_L       _TGEN_PK_L_(0x90, 0x66)
#define  REG_TGEN_SC1_VOP_BK90_66_H       _TGEN_PK_H_(0x90, 0x66)
#define  REG_TGEN_SC1_VOP_BK90_67_L       _TGEN_PK_L_(0x90, 0x67)
#define  REG_TGEN_SC1_VOP_BK90_67_H       _TGEN_PK_H_(0x90, 0x67)
#define  REG_TGEN_SC1_VOP_BK90_68_L       _TGEN_PK_L_(0x90, 0x68)
#define  REG_TGEN_SC1_VOP_BK90_68_H       _TGEN_PK_H_(0x90, 0x68)
#define  REG_TGEN_SC1_VOP_BK90_69_L       _TGEN_PK_L_(0x90, 0x69)
#define  REG_TGEN_SC1_VOP_BK90_69_H       _TGEN_PK_H_(0x90, 0x69)
#define  REG_TGEN_SC1_VOP_BK90_6A_L       _TGEN_PK_L_(0x90, 0x6A)
#define  REG_TGEN_SC1_VOP_BK90_6A_H       _TGEN_PK_H_(0x90, 0x6A)
#define  REG_TGEN_SC1_VOP_BK90_6B_L       _TGEN_PK_L_(0x90, 0x6B)
#define  REG_TGEN_SC1_VOP_BK90_6B_H       _TGEN_PK_H_(0x90, 0x6B)
#define  REG_TGEN_SC1_VOP_BK90_6C_L       _TGEN_PK_L_(0x90, 0x6C)
#define  REG_TGEN_SC1_VOP_BK90_6C_H       _TGEN_PK_H_(0x90, 0x6C)
#define  REG_TGEN_SC1_VOP_BK90_6D_L       _TGEN_PK_L_(0x90, 0x6D)
#define  REG_TGEN_SC1_VOP_BK90_6D_H       _TGEN_PK_H_(0x90, 0x6D)
#define  REG_TGEN_SC1_VOP_BK90_6E_L       _TGEN_PK_L_(0x90, 0x6E)
#define  REG_TGEN_SC1_VOP_BK90_6E_H       _TGEN_PK_H_(0x90, 0x6E)
#define  REG_TGEN_SC1_VOP_BK90_6F_L       _TGEN_PK_L_(0x90, 0x6F)
#define  REG_TGEN_SC1_VOP_BK90_6F_H       _TGEN_PK_H_(0x90, 0x6F)
#define  REG_TGEN_SC1_VOP_BK90_70_L       _TGEN_PK_L_(0x90, 0x70)
#define  REG_TGEN_SC1_VOP_BK90_70_H       _TGEN_PK_H_(0x90, 0x70)
#define  REG_TGEN_SC1_VOP_BK90_71_L       _TGEN_PK_L_(0x90, 0x71)
#define  REG_TGEN_SC1_VOP_BK90_71_H       _TGEN_PK_H_(0x90, 0x71)
#define  REG_TGEN_SC1_VOP_BK90_72_L       _TGEN_PK_L_(0x90, 0x72)
#define  REG_TGEN_SC1_VOP_BK90_72_H       _TGEN_PK_H_(0x90, 0x72)
#define  REG_TGEN_SC1_VOP_BK90_73_L       _TGEN_PK_L_(0x90, 0x73)
#define  REG_TGEN_SC1_VOP_BK90_73_H       _TGEN_PK_H_(0x90, 0x73)
#define  REG_TGEN_SC1_VOP_BK90_74_L       _TGEN_PK_L_(0x90, 0x74)
#define  REG_TGEN_SC1_VOP_BK90_74_H       _TGEN_PK_H_(0x90, 0x74)
#define  REG_TGEN_SC1_VOP_BK90_75_L       _TGEN_PK_L_(0x90, 0x75)
#define  REG_TGEN_SC1_VOP_BK90_75_H       _TGEN_PK_H_(0x90, 0x75)
#define  REG_TGEN_SC1_VOP_BK90_76_L       _TGEN_PK_L_(0x90, 0x76)
#define  REG_TGEN_SC1_VOP_BK90_76_H       _TGEN_PK_H_(0x90, 0x76)
#define  REG_TGEN_SC1_VOP_BK90_77_L       _TGEN_PK_L_(0x90, 0x77)
#define  REG_TGEN_SC1_VOP_BK90_77_H       _TGEN_PK_H_(0x90, 0x77)
#define  REG_TGEN_SC1_VOP_BK90_78_L       _TGEN_PK_L_(0x90, 0x78)
#define  REG_TGEN_SC1_VOP_BK90_78_H       _TGEN_PK_H_(0x90, 0x78)
#define  REG_TGEN_SC1_VOP_BK90_79_L       _TGEN_PK_L_(0x90, 0x79)
#define  REG_TGEN_SC1_VOP_BK90_79_H       _TGEN_PK_H_(0x90, 0x79)
#define  REG_TGEN_SC1_VOP_BK90_7A_L       _TGEN_PK_L_(0x90, 0x7A)
#define  REG_TGEN_SC1_VOP_BK90_7A_H       _TGEN_PK_H_(0x90, 0x7A)
#define  REG_TGEN_SC1_VOP_BK90_7B_L       _TGEN_PK_L_(0x90, 0x7B)
#define  REG_TGEN_SC1_VOP_BK90_7B_H       _TGEN_PK_H_(0x90, 0x7B)
#define  REG_TGEN_SC1_VOP_BK90_7C_L       _TGEN_PK_L_(0x90, 0x7C)
#define  REG_TGEN_SC1_VOP_BK90_7C_H       _TGEN_PK_H_(0x90, 0x7C)
#define  REG_TGEN_SC1_VOP_BK90_7D_L       _TGEN_PK_L_(0x90, 0x7D)
#define  REG_TGEN_SC1_VOP_BK90_7D_H       _TGEN_PK_H_(0x90, 0x7D)
#define  REG_TGEN_SC1_VOP_BK90_7E_L       _TGEN_PK_L_(0x90, 0x7E)
#define  REG_TGEN_SC1_VOP_BK90_7E_H       _TGEN_PK_H_(0x90, 0x7E)
#define  REG_TGEN_SC1_VOP_BK90_7F_L       _TGEN_PK_L_(0x90, 0x7F)
#define  REG_TGEN_SC1_VOP_BK90_7F_H       _TGEN_PK_H_(0x90, 0x7F)

#define  REG_TGEN_HDMITx_MISC_00_L       (REG_TGEN_HDMITx_MISC_BASE + 0x00)
#define  REG_TGEN_HDMITx_MISC_00_H       (REG_TGEN_HDMITx_MISC_BASE + 0x01)
#define  REG_TGEN_HDMITx_MISC_01_L       (REG_TGEN_HDMITx_MISC_BASE + 0x02)
#define  REG_TGEN_HDMITx_MISC_01_H       (REG_TGEN_HDMITx_MISC_BASE + 0x03)
#define  REG_TGEN_HDMITx_MISC_02_L       (REG_TGEN_HDMITx_MISC_BASE + 0x04)
#define  REG_TGEN_HDMITx_MISC_02_H       (REG_TGEN_HDMITx_MISC_BASE + 0x05)
#define  REG_TGEN_HDMITx_MISC_03_L       (REG_TGEN_HDMITx_MISC_BASE + 0x06)
#define  REG_TGEN_HDMITx_MISC_03_H       (REG_TGEN_HDMITx_MISC_BASE + 0x07)
#define  REG_TGEN_HDMITx_MISC_04_L       (REG_TGEN_HDMITx_MISC_BASE + 0x08)
#define  REG_TGEN_HDMITx_MISC_04_H       (REG_TGEN_HDMITx_MISC_BASE + 0x09)
#define  REG_TGEN_HDMITx_MISC_05_L       (REG_TGEN_HDMITx_MISC_BASE + 0x0A)
#define  REG_TGEN_HDMITx_MISC_05_H       (REG_TGEN_HDMITx_MISC_BASE + 0x0B)
#define  REG_TGEN_HDMITx_MISC_06_L       (REG_TGEN_HDMITx_MISC_BASE + 0x0C)
#define  REG_TGEN_HDMITx_MISC_06_H       (REG_TGEN_HDMITx_MISC_BASE + 0x0D)
#define  REG_TGEN_HDMITx_MISC_07_L       (REG_TGEN_HDMITx_MISC_BASE + 0x0E)
#define  REG_TGEN_HDMITx_MISC_07_H       (REG_TGEN_HDMITx_MISC_BASE + 0x0F)
#define  REG_TGEN_HDMITx_MISC_08_L       (REG_TGEN_HDMITx_MISC_BASE + 0x10)
#define  REG_TGEN_HDMITx_MISC_08_H       (REG_TGEN_HDMITx_MISC_BASE + 0x11)
#define  REG_TGEN_HDMITx_MISC_09_L       (REG_TGEN_HDMITx_MISC_BASE + 0x12)
#define  REG_TGEN_HDMITx_MISC_09_H       (REG_TGEN_HDMITx_MISC_BASE + 0x13)
#define  REG_TGEN_HDMITx_MISC_0A_L       (REG_TGEN_HDMITx_MISC_BASE + 0x14)
#define  REG_TGEN_HDMITx_MISC_0A_H       (REG_TGEN_HDMITx_MISC_BASE + 0x15)
#define  REG_TGEN_HDMITx_MISC_0B_L       (REG_TGEN_HDMITx_MISC_BASE + 0x16)
#define  REG_TGEN_HDMITx_MISC_0B_H       (REG_TGEN_HDMITx_MISC_BASE + 0x17)
#define  REG_TGEN_HDMITx_MISC_0C_L       (REG_TGEN_HDMITx_MISC_BASE + 0x18)
#define  REG_TGEN_HDMITx_MISC_0C_H       (REG_TGEN_HDMITx_MISC_BASE + 0x19)
#define  REG_TGEN_HDMITx_MISC_0D_L       (REG_TGEN_HDMITx_MISC_BASE + 0x1A)
#define  REG_TGEN_HDMITx_MISC_0D_H       (REG_TGEN_HDMITx_MISC_BASE + 0x1B)
#define  REG_TGEN_HDMITx_MISC_0E_L       (REG_TGEN_HDMITx_MISC_BASE + 0x1C)
#define  REG_TGEN_HDMITx_MISC_0E_H       (REG_TGEN_HDMITx_MISC_BASE + 0x1D)
#define  REG_TGEN_HDMITx_MISC_0F_L       (REG_TGEN_HDMITx_MISC_BASE + 0x1E)
#define  REG_TGEN_HDMITx_MISC_0F_H       (REG_TGEN_HDMITx_MISC_BASE + 0x1F)
#define  REG_TGEN_HDMITx_MISC_10_L       (REG_TGEN_HDMITx_MISC_BASE + 0x20)
#define  REG_TGEN_HDMITx_MISC_10_H       (REG_TGEN_HDMITx_MISC_BASE + 0x21)
#define  REG_TGEN_HDMITx_MISC_11_L       (REG_TGEN_HDMITx_MISC_BASE + 0x22)
#define  REG_TGEN_HDMITx_MISC_11_H       (REG_TGEN_HDMITx_MISC_BASE + 0x23)
#define  REG_TGEN_HDMITx_MISC_12_L       (REG_TGEN_HDMITx_MISC_BASE + 0x24)
#define  REG_TGEN_HDMITx_MISC_12_H       (REG_TGEN_HDMITx_MISC_BASE + 0x25)
#define  REG_TGEN_HDMITx_MISC_13_L       (REG_TGEN_HDMITx_MISC_BASE + 0x26)
#define  REG_TGEN_HDMITx_MISC_13_H       (REG_TGEN_HDMITx_MISC_BASE + 0x27)
#define  REG_TGEN_HDMITx_MISC_14_L       (REG_TGEN_HDMITx_MISC_BASE + 0x28)
#define  REG_TGEN_HDMITx_MISC_14_H       (REG_TGEN_HDMITx_MISC_BASE + 0x29)
#define  REG_TGEN_HDMITx_MISC_15_L       (REG_TGEN_HDMITx_MISC_BASE + 0x2A)
#define  REG_TGEN_HDMITx_MISC_15_H       (REG_TGEN_HDMITx_MISC_BASE + 0x2B)
#define  REG_TGEN_HDMITx_MISC_16_L       (REG_TGEN_HDMITx_MISC_BASE + 0x2C)
#define  REG_TGEN_HDMITx_MISC_16_H       (REG_TGEN_HDMITx_MISC_BASE + 0x2D)
#define  REG_TGEN_HDMITx_MISC_17_L       (REG_TGEN_HDMITx_MISC_BASE + 0x2E)
#define  REG_TGEN_HDMITx_MISC_17_H       (REG_TGEN_HDMITx_MISC_BASE + 0x2F)
#define  REG_TGEN_HDMITx_MISC_18_L       (REG_TGEN_HDMITx_MISC_BASE + 0x30)
#define  REG_TGEN_HDMITx_MISC_18_H       (REG_TGEN_HDMITx_MISC_BASE + 0x31)
#define  REG_TGEN_HDMITx_MISC_19_L       (REG_TGEN_HDMITx_MISC_BASE + 0x32)
#define  REG_TGEN_HDMITx_MISC_19_H       (REG_TGEN_HDMITx_MISC_BASE + 0x33)
#define  REG_TGEN_HDMITx_MISC_1A_L       (REG_TGEN_HDMITx_MISC_BASE + 0x34)
#define  REG_TGEN_HDMITx_MISC_1A_H       (REG_TGEN_HDMITx_MISC_BASE + 0x35)
#define  REG_TGEN_HDMITx_MISC_1B_L       (REG_TGEN_HDMITx_MISC_BASE + 0x36)
#define  REG_TGEN_HDMITx_MISC_1B_H       (REG_TGEN_HDMITx_MISC_BASE + 0x37)
#define  REG_TGEN_HDMITx_MISC_1C_L       (REG_TGEN_HDMITx_MISC_BASE + 0x38)
#define  REG_TGEN_HDMITx_MISC_1C_H       (REG_TGEN_HDMITx_MISC_BASE + 0x39)
#define  REG_TGEN_HDMITx_MISC_1D_L       (REG_TGEN_HDMITx_MISC_BASE + 0x3A)
#define  REG_TGEN_HDMITx_MISC_1D_H       (REG_TGEN_HDMITx_MISC_BASE + 0x3B)
#define  REG_TGEN_HDMITx_MISC_1E_L       (REG_TGEN_HDMITx_MISC_BASE + 0x3C)
#define  REG_TGEN_HDMITx_MISC_1E_H       (REG_TGEN_HDMITx_MISC_BASE + 0x3D)
#define  REG_TGEN_HDMITx_MISC_1F_L       (REG_TGEN_HDMITx_MISC_BASE + 0x3E)
#define  REG_TGEN_HDMITx_MISC_1F_H       (REG_TGEN_HDMITx_MISC_BASE + 0x3F)
#define  REG_TGEN_HDMITx_MISC_20_L       (REG_TGEN_HDMITx_MISC_BASE + 0x40)
#define  REG_TGEN_HDMITx_MISC_20_H       (REG_TGEN_HDMITx_MISC_BASE + 0x41)
#define  REG_TGEN_HDMITx_MISC_21_L       (REG_TGEN_HDMITx_MISC_BASE + 0x42)
#define  REG_TGEN_HDMITx_MISC_21_H       (REG_TGEN_HDMITx_MISC_BASE + 0x43)
#define  REG_TGEN_HDMITx_MISC_22_L       (REG_TGEN_HDMITx_MISC_BASE + 0x44)
#define  REG_TGEN_HDMITx_MISC_22_H       (REG_TGEN_HDMITx_MISC_BASE + 0x45)
#define  REG_TGEN_HDMITx_MISC_23_L       (REG_TGEN_HDMITx_MISC_BASE + 0x46)
#define  REG_TGEN_HDMITx_MISC_23_H       (REG_TGEN_HDMITx_MISC_BASE + 0x47)
#define  REG_TGEN_HDMITx_MISC_24_L       (REG_TGEN_HDMITx_MISC_BASE + 0x48)
#define  REG_TGEN_HDMITx_MISC_24_H       (REG_TGEN_HDMITx_MISC_BASE + 0x49)
#define  REG_TGEN_HDMITx_MISC_25_L       (REG_TGEN_HDMITx_MISC_BASE + 0x4A)
#define  REG_TGEN_HDMITx_MISC_25_H       (REG_TGEN_HDMITx_MISC_BASE + 0x4B)
#define  REG_TGEN_HDMITx_MISC_26_L       (REG_TGEN_HDMITx_MISC_BASE + 0x4C)
#define  REG_TGEN_HDMITx_MISC_26_H       (REG_TGEN_HDMITx_MISC_BASE + 0x4D)
#define  REG_TGEN_HDMITx_MISC_27_L       (REG_TGEN_HDMITx_MISC_BASE + 0x4E)
#define  REG_TGEN_HDMITx_MISC_27_H       (REG_TGEN_HDMITx_MISC_BASE + 0x4F)
#define  REG_TGEN_HDMITx_MISC_28_L       (REG_TGEN_HDMITx_MISC_BASE + 0x50)
#define  REG_TGEN_HDMITx_MISC_28_H       (REG_TGEN_HDMITx_MISC_BASE + 0x51)
#define  REG_TGEN_HDMITx_MISC_29_L       (REG_TGEN_HDMITx_MISC_BASE + 0x52)
#define  REG_TGEN_HDMITx_MISC_29_H       (REG_TGEN_HDMITx_MISC_BASE + 0x53)
#define  REG_TGEN_HDMITx_MISC_2A_L       (REG_TGEN_HDMITx_MISC_BASE + 0x54)
#define  REG_TGEN_HDMITx_MISC_2A_H       (REG_TGEN_HDMITx_MISC_BASE + 0x55)
#define  REG_TGEN_HDMITx_MISC_2B_L       (REG_TGEN_HDMITx_MISC_BASE + 0x56)
#define  REG_TGEN_HDMITx_MISC_2B_H       (REG_TGEN_HDMITx_MISC_BASE + 0x57)
#define  REG_TGEN_HDMITx_MISC_2C_L       (REG_TGEN_HDMITx_MISC_BASE + 0x58)
#define  REG_TGEN_HDMITx_MISC_2C_H       (REG_TGEN_HDMITx_MISC_BASE + 0x59)
#define  REG_TGEN_HDMITx_MISC_2D_L       (REG_TGEN_HDMITx_MISC_BASE + 0x5A)
#define  REG_TGEN_HDMITx_MISC_2D_H       (REG_TGEN_HDMITx_MISC_BASE + 0x5B)
#define  REG_TGEN_HDMITx_MISC_2E_L       (REG_TGEN_HDMITx_MISC_BASE + 0x5C)
#define  REG_TGEN_HDMITx_MISC_2E_H       (REG_TGEN_HDMITx_MISC_BASE + 0x5D)
#define  REG_TGEN_HDMITx_MISC_2F_L       (REG_TGEN_HDMITx_MISC_BASE + 0x5E)
#define  REG_TGEN_HDMITx_MISC_2F_H       (REG_TGEN_HDMITx_MISC_BASE + 0x5F)
#define  REG_TGEN_HDMITx_MISC_30_L       (REG_TGEN_HDMITx_MISC_BASE + 0x60)
#define  REG_TGEN_HDMITx_MISC_30_H       (REG_TGEN_HDMITx_MISC_BASE + 0x61)
#define  REG_TGEN_HDMITx_MISC_31_L       (REG_TGEN_HDMITx_MISC_BASE + 0x62)
#define  REG_TGEN_HDMITx_MISC_31_H       (REG_TGEN_HDMITx_MISC_BASE + 0x63)
#define  REG_TGEN_HDMITx_MISC_32_L       (REG_TGEN_HDMITx_MISC_BASE + 0x64)
#define  REG_TGEN_HDMITx_MISC_32_H       (REG_TGEN_HDMITx_MISC_BASE + 0x65)
#define  REG_TGEN_HDMITx_MISC_33_L       (REG_TGEN_HDMITx_MISC_BASE + 0x66)
#define  REG_TGEN_HDMITx_MISC_33_H       (REG_TGEN_HDMITx_MISC_BASE + 0x67)
#define  REG_TGEN_HDMITx_MISC_34_L       (REG_TGEN_HDMITx_MISC_BASE + 0x68)
#define  REG_TGEN_HDMITx_MISC_34_H       (REG_TGEN_HDMITx_MISC_BASE + 0x69)
#define  REG_TGEN_HDMITx_MISC_35_L       (REG_TGEN_HDMITx_MISC_BASE + 0x6A)
#define  REG_TGEN_HDMITx_MISC_35_H       (REG_TGEN_HDMITx_MISC_BASE + 0x6B)
#define  REG_TGEN_HDMITx_MISC_36_L       (REG_TGEN_HDMITx_MISC_BASE + 0x6C)
#define  REG_TGEN_HDMITx_MISC_36_H       (REG_TGEN_HDMITx_MISC_BASE + 0x6D)
#define  REG_TGEN_HDMITx_MISC_37_L       (REG_TGEN_HDMITx_MISC_BASE + 0x6E)
#define  REG_TGEN_HDMITx_MISC_37_H       (REG_TGEN_HDMITx_MISC_BASE + 0x6F)
#define  REG_TGEN_HDMITx_MISC_38_L       (REG_TGEN_HDMITx_MISC_BASE + 0x70)
#define  REG_TGEN_HDMITx_MISC_38_H       (REG_TGEN_HDMITx_MISC_BASE + 0x71)
#define  REG_TGEN_HDMITx_MISC_39_L       (REG_TGEN_HDMITx_MISC_BASE + 0x72)
#define  REG_TGEN_HDMITx_MISC_39_H       (REG_TGEN_HDMITx_MISC_BASE + 0x73)
#define  REG_TGEN_HDMITx_MISC_3A_L       (REG_TGEN_HDMITx_MISC_BASE + 0x74)
#define  REG_TGEN_HDMITx_MISC_3A_H       (REG_TGEN_HDMITx_MISC_BASE + 0x75)
#define  REG_TGEN_HDMITx_MISC_3B_L       (REG_TGEN_HDMITx_MISC_BASE + 0x76)
#define  REG_TGEN_HDMITx_MISC_3B_H       (REG_TGEN_HDMITx_MISC_BASE + 0x77)
#define  REG_TGEN_HDMITx_MISC_3C_L       (REG_TGEN_HDMITx_MISC_BASE + 0x78)
#define  REG_TGEN_HDMITx_MISC_3C_H       (REG_TGEN_HDMITx_MISC_BASE + 0x79)
#define  REG_TGEN_HDMITx_MISC_3D_L       (REG_TGEN_HDMITx_MISC_BASE + 0x7A)
#define  REG_TGEN_HDMITx_MISC_3D_H       (REG_TGEN_HDMITx_MISC_BASE + 0x7B)
#define  REG_TGEN_HDMITx_MISC_3E_L       (REG_TGEN_HDMITx_MISC_BASE + 0x7C)
#define  REG_TGEN_HDMITx_MISC_3E_H       (REG_TGEN_HDMITx_MISC_BASE + 0x7D)
#define  REG_TGEN_HDMITx_MISC_3F_L       (REG_TGEN_HDMITx_MISC_BASE + 0x7E)
#define  REG_TGEN_HDMITx_MISC_3F_H       (REG_TGEN_HDMITx_MISC_BASE + 0x7F)
#define  REG_TGEN_HDMITx_MISC_40_L       (REG_TGEN_HDMITx_MISC_BASE + 0x80)
#define  REG_TGEN_HDMITx_MISC_40_H       (REG_TGEN_HDMITx_MISC_BASE + 0x81)
#define  REG_TGEN_HDMITx_MISC_41_L       (REG_TGEN_HDMITx_MISC_BASE + 0x82)
#define  REG_TGEN_HDMITx_MISC_41_H       (REG_TGEN_HDMITx_MISC_BASE + 0x83)
#define  REG_TGEN_HDMITx_MISC_42_L       (REG_TGEN_HDMITx_MISC_BASE + 0x84)
#define  REG_TGEN_HDMITx_MISC_42_H       (REG_TGEN_HDMITx_MISC_BASE + 0x85)
#define  REG_TGEN_HDMITx_MISC_43_L       (REG_TGEN_HDMITx_MISC_BASE + 0x86)
#define  REG_TGEN_HDMITx_MISC_43_H       (REG_TGEN_HDMITx_MISC_BASE + 0x87)
#define  REG_TGEN_HDMITx_MISC_44_L       (REG_TGEN_HDMITx_MISC_BASE + 0x88)
#define  REG_TGEN_HDMITx_MISC_44_H       (REG_TGEN_HDMITx_MISC_BASE + 0x89)
#define  REG_TGEN_HDMITx_MISC_45_L       (REG_TGEN_HDMITx_MISC_BASE + 0x8A)
#define  REG_TGEN_HDMITx_MISC_45_H       (REG_TGEN_HDMITx_MISC_BASE + 0x8B)
#define  REG_TGEN_HDMITx_MISC_46_L       (REG_TGEN_HDMITx_MISC_BASE + 0x8C)
#define  REG_TGEN_HDMITx_MISC_46_H       (REG_TGEN_HDMITx_MISC_BASE + 0x8D)
#define  REG_TGEN_HDMITx_MISC_47_L       (REG_TGEN_HDMITx_MISC_BASE + 0x8E)
#define  REG_TGEN_HDMITx_MISC_47_H       (REG_TGEN_HDMITx_MISC_BASE + 0x8F)
#define  REG_TGEN_HDMITx_MISC_48_L       (REG_TGEN_HDMITx_MISC_BASE + 0x90)
#define  REG_TGEN_HDMITx_MISC_48_H       (REG_TGEN_HDMITx_MISC_BASE + 0x91)
#define  REG_TGEN_HDMITx_MISC_49_L       (REG_TGEN_HDMITx_MISC_BASE + 0x92)
#define  REG_TGEN_HDMITx_MISC_49_H       (REG_TGEN_HDMITx_MISC_BASE + 0x93)
#define  REG_TGEN_HDMITx_MISC_4A_L       (REG_TGEN_HDMITx_MISC_BASE + 0x94)
#define  REG_TGEN_HDMITx_MISC_4A_H       (REG_TGEN_HDMITx_MISC_BASE + 0x95)
#define  REG_TGEN_HDMITx_MISC_4B_L       (REG_TGEN_HDMITx_MISC_BASE + 0x96)
#define  REG_TGEN_HDMITx_MISC_4B_H       (REG_TGEN_HDMITx_MISC_BASE + 0x97)
#define  REG_TGEN_HDMITx_MISC_4C_L       (REG_TGEN_HDMITx_MISC_BASE + 0x98)
#define  REG_TGEN_HDMITx_MISC_4C_H       (REG_TGEN_HDMITx_MISC_BASE + 0x99)
#define  REG_TGEN_HDMITx_MISC_4D_L       (REG_TGEN_HDMITx_MISC_BASE + 0x9A)
#define  REG_TGEN_HDMITx_MISC_4D_H       (REG_TGEN_HDMITx_MISC_BASE + 0x9B)
#define  REG_TGEN_HDMITx_MISC_4E_L       (REG_TGEN_HDMITx_MISC_BASE + 0x9C)
#define  REG_TGEN_HDMITx_MISC_4E_H       (REG_TGEN_HDMITx_MISC_BASE + 0x9D)
#define  REG_TGEN_HDMITx_MISC_4F_L       (REG_TGEN_HDMITx_MISC_BASE + 0x9E)
#define  REG_TGEN_HDMITx_MISC_4F_H       (REG_TGEN_HDMITx_MISC_BASE + 0x9F)
#define  REG_TGEN_HDMITx_MISC_50_L       (REG_TGEN_HDMITx_MISC_BASE + 0xA0)
#define  REG_TGEN_HDMITx_MISC_50_H       (REG_TGEN_HDMITx_MISC_BASE + 0xA1)
#define  REG_TGEN_HDMITx_MISC_51_L       (REG_TGEN_HDMITx_MISC_BASE + 0xA2)
#define  REG_TGEN_HDMITx_MISC_51_H       (REG_TGEN_HDMITx_MISC_BASE + 0xA3)
#define  REG_TGEN_HDMITx_MISC_52_L       (REG_TGEN_HDMITx_MISC_BASE + 0xA4)
#define  REG_TGEN_HDMITx_MISC_52_H       (REG_TGEN_HDMITx_MISC_BASE + 0xA5)
#define  REG_TGEN_HDMITx_MISC_53_L       (REG_TGEN_HDMITx_MISC_BASE + 0xA6)
#define  REG_TGEN_HDMITx_MISC_53_H       (REG_TGEN_HDMITx_MISC_BASE + 0xA7)
#define  REG_TGEN_HDMITx_MISC_54_L       (REG_TGEN_HDMITx_MISC_BASE + 0xA8)
#define  REG_TGEN_HDMITx_MISC_54_H       (REG_TGEN_HDMITx_MISC_BASE + 0xA9)
#define  REG_TGEN_HDMITx_MISC_55_L       (REG_TGEN_HDMITx_MISC_BASE + 0xAA)
#define  REG_TGEN_HDMITx_MISC_55_H       (REG_TGEN_HDMITx_MISC_BASE + 0xAB)
#define  REG_TGEN_HDMITx_MISC_56_L       (REG_TGEN_HDMITx_MISC_BASE + 0xAC)
#define  REG_TGEN_HDMITx_MISC_56_H       (REG_TGEN_HDMITx_MISC_BASE + 0xAD)
#define  REG_TGEN_HDMITx_MISC_57_L       (REG_TGEN_HDMITx_MISC_BASE + 0xAE)
#define  REG_TGEN_HDMITx_MISC_57_H       (REG_TGEN_HDMITx_MISC_BASE + 0xAF)
#define  REG_TGEN_HDMITx_MISC_58_L       (REG_TGEN_HDMITx_MISC_BASE + 0xB0)
#define  REG_TGEN_HDMITx_MISC_58_H       (REG_TGEN_HDMITx_MISC_BASE + 0xB1)
#define  REG_TGEN_HDMITx_MISC_59_L       (REG_TGEN_HDMITx_MISC_BASE + 0xB2)
#define  REG_TGEN_HDMITx_MISC_59_H       (REG_TGEN_HDMITx_MISC_BASE + 0xB3)
#define  REG_TGEN_HDMITx_MISC_5A_L       (REG_TGEN_HDMITx_MISC_BASE + 0xB4)
#define  REG_TGEN_HDMITx_MISC_5A_H       (REG_TGEN_HDMITx_MISC_BASE + 0xB5)
#define  REG_TGEN_HDMITx_MISC_5B_L       (REG_TGEN_HDMITx_MISC_BASE + 0xB6)
#define  REG_TGEN_HDMITx_MISC_5B_H       (REG_TGEN_HDMITx_MISC_BASE + 0xB7)
#define  REG_TGEN_HDMITx_MISC_5C_L       (REG_TGEN_HDMITx_MISC_BASE + 0xB8)
#define  REG_TGEN_HDMITx_MISC_5C_H       (REG_TGEN_HDMITx_MISC_BASE + 0xB9)
#define  REG_TGEN_HDMITx_MISC_5D_L       (REG_TGEN_HDMITx_MISC_BASE + 0xBA)
#define  REG_TGEN_HDMITx_MISC_5D_H       (REG_TGEN_HDMITx_MISC_BASE + 0xBB)
#define  REG_TGEN_HDMITx_MISC_5E_L       (REG_TGEN_HDMITx_MISC_BASE + 0xBC)
#define  REG_TGEN_HDMITx_MISC_5E_H       (REG_TGEN_HDMITx_MISC_BASE + 0xBD)
#define  REG_TGEN_HDMITx_MISC_5F_L       (REG_TGEN_HDMITx_MISC_BASE + 0xBE)
#define  REG_TGEN_HDMITx_MISC_5F_H       (REG_TGEN_HDMITx_MISC_BASE + 0xBF)
#define  REG_TGEN_HDMITx_MISC_60_L       (REG_TGEN_HDMITx_MISC_BASE + 0xC0)
#define  REG_TGEN_HDMITx_MISC_60_H       (REG_TGEN_HDMITx_MISC_BASE + 0xC1)
#define  REG_TGEN_HDMITx_MISC_61_L       (REG_TGEN_HDMITx_MISC_BASE + 0xC2)
#define  REG_TGEN_HDMITx_MISC_61_H       (REG_TGEN_HDMITx_MISC_BASE + 0xC3)
#define  REG_TGEN_HDMITx_MISC_62_L       (REG_TGEN_HDMITx_MISC_BASE + 0xC4)
#define  REG_TGEN_HDMITx_MISC_62_H       (REG_TGEN_HDMITx_MISC_BASE + 0xC5)
#define  REG_TGEN_HDMITx_MISC_63_L       (REG_TGEN_HDMITx_MISC_BASE + 0xC6)
#define  REG_TGEN_HDMITx_MISC_63_H       (REG_TGEN_HDMITx_MISC_BASE + 0xC7)
#define  REG_TGEN_HDMITx_MISC_64_L       (REG_TGEN_HDMITx_MISC_BASE + 0xC8)
#define  REG_TGEN_HDMITx_MISC_64_H       (REG_TGEN_HDMITx_MISC_BASE + 0xC9)
#define  REG_TGEN_HDMITx_MISC_65_L       (REG_TGEN_HDMITx_MISC_BASE + 0xCA)
#define  REG_TGEN_HDMITx_MISC_65_H       (REG_TGEN_HDMITx_MISC_BASE + 0xCB)
#define  REG_TGEN_HDMITx_MISC_66_L       (REG_TGEN_HDMITx_MISC_BASE + 0xCC)
#define  REG_TGEN_HDMITx_MISC_66_H       (REG_TGEN_HDMITx_MISC_BASE + 0xCD)
#define  REG_TGEN_HDMITx_MISC_67_L       (REG_TGEN_HDMITx_MISC_BASE + 0xCE)
#define  REG_TGEN_HDMITx_MISC_67_H       (REG_TGEN_HDMITx_MISC_BASE + 0xCF)
#define  REG_TGEN_HDMITx_MISC_68_L       (REG_TGEN_HDMITx_MISC_BASE + 0xD0)
#define  REG_TGEN_HDMITx_MISC_68_H       (REG_TGEN_HDMITx_MISC_BASE + 0xD1)
#define  REG_TGEN_HDMITx_MISC_69_L       (REG_TGEN_HDMITx_MISC_BASE + 0xD2)
#define  REG_TGEN_HDMITx_MISC_69_H       (REG_TGEN_HDMITx_MISC_BASE + 0xD3)
#define  REG_TGEN_HDMITx_MISC_6A_L       (REG_TGEN_HDMITx_MISC_BASE + 0xD4)
#define  REG_TGEN_HDMITx_MISC_6A_H       (REG_TGEN_HDMITx_MISC_BASE + 0xD5)
#define  REG_TGEN_HDMITx_MISC_6B_L       (REG_TGEN_HDMITx_MISC_BASE + 0xD6)
#define  REG_TGEN_HDMITx_MISC_6B_H       (REG_TGEN_HDMITx_MISC_BASE + 0xD7)
#define  REG_TGEN_HDMITx_MISC_6C_L       (REG_TGEN_HDMITx_MISC_BASE + 0xD8)
#define  REG_TGEN_HDMITx_MISC_6C_H       (REG_TGEN_HDMITx_MISC_BASE + 0xD9)
#define  REG_TGEN_HDMITx_MISC_6D_L       (REG_TGEN_HDMITx_MISC_BASE + 0xDA)
#define  REG_TGEN_HDMITx_MISC_6D_H       (REG_TGEN_HDMITx_MISC_BASE + 0xDB)
#define  REG_TGEN_HDMITx_MISC_6E_L       (REG_TGEN_HDMITx_MISC_BASE + 0xDC)
#define  REG_TGEN_HDMITx_MISC_6E_H       (REG_TGEN_HDMITx_MISC_BASE + 0xDD)
#define  REG_TGEN_HDMITx_MISC_6F_L       (REG_TGEN_HDMITx_MISC_BASE + 0xDE)
#define  REG_TGEN_HDMITx_MISC_6F_H       (REG_TGEN_HDMITx_MISC_BASE + 0xDF)
#define  REG_TGEN_HDMITx_MISC_70_L       (REG_TGEN_HDMITx_MISC_BASE + 0xE0)
#define  REG_TGEN_HDMITx_MISC_70_H       (REG_TGEN_HDMITx_MISC_BASE + 0xE1)
#define  REG_TGEN_HDMITx_MISC_71_L       (REG_TGEN_HDMITx_MISC_BASE + 0xE2)
#define  REG_TGEN_HDMITx_MISC_71_H       (REG_TGEN_HDMITx_MISC_BASE + 0xE3)
#define  REG_TGEN_HDMITx_MISC_72_L       (REG_TGEN_HDMITx_MISC_BASE + 0xE4)
#define  REG_TGEN_HDMITx_MISC_72_H       (REG_TGEN_HDMITx_MISC_BASE + 0xE5)
#define  REG_TGEN_HDMITx_MISC_73_L       (REG_TGEN_HDMITx_MISC_BASE + 0xE6)
#define  REG_TGEN_HDMITx_MISC_73_H       (REG_TGEN_HDMITx_MISC_BASE + 0xE7)
#define  REG_TGEN_HDMITx_MISC_74_L       (REG_TGEN_HDMITx_MISC_BASE + 0xE8)
#define  REG_TGEN_HDMITx_MISC_74_H       (REG_TGEN_HDMITx_MISC_BASE + 0xE9)
#define  REG_TGEN_HDMITx_MISC_75_L       (REG_TGEN_HDMITx_MISC_BASE + 0xEA)
#define  REG_TGEN_HDMITx_MISC_75_H       (REG_TGEN_HDMITx_MISC_BASE + 0xEB)
#define  REG_TGEN_HDMITx_MISC_76_L       (REG_TGEN_HDMITx_MISC_BASE + 0xEC)
#define  REG_TGEN_HDMITx_MISC_76_H       (REG_TGEN_HDMITx_MISC_BASE + 0xED)
#define  REG_TGEN_HDMITx_MISC_77_L       (REG_TGEN_HDMITx_MISC_BASE + 0xEE)
#define  REG_TGEN_HDMITx_MISC_77_H       (REG_TGEN_HDMITx_MISC_BASE + 0xEF)
#define  REG_TGEN_HDMITx_MISC_78_L       (REG_TGEN_HDMITx_MISC_BASE + 0xF0)
#define  REG_TGEN_HDMITx_MISC_78_H       (REG_TGEN_HDMITx_MISC_BASE + 0xF1)
#define  REG_TGEN_HDMITx_MISC_79_L       (REG_TGEN_HDMITx_MISC_BASE + 0xF2)
#define  REG_TGEN_HDMITx_MISC_79_H       (REG_TGEN_HDMITx_MISC_BASE + 0xF3)
#define  REG_TGEN_HDMITx_MISC_7A_L       (REG_TGEN_HDMITx_MISC_BASE + 0xF4)
#define  REG_TGEN_HDMITx_MISC_7A_H       (REG_TGEN_HDMITx_MISC_BASE + 0xF5)
#define  REG_TGEN_HDMITx_MISC_7B_L       (REG_TGEN_HDMITx_MISC_BASE + 0xF6)
#define  REG_TGEN_HDMITx_MISC_7B_H       (REG_TGEN_HDMITx_MISC_BASE + 0xF7)
#define  REG_TGEN_HDMITx_MISC_7C_L       (REG_TGEN_HDMITx_MISC_BASE + 0xF8)
#define  REG_TGEN_HDMITx_MISC_7C_H       (REG_TGEN_HDMITx_MISC_BASE + 0xF9)
#define  REG_TGEN_HDMITx_MISC_7D_L       (REG_TGEN_HDMITx_MISC_BASE + 0xFA)
#define  REG_TGEN_HDMITx_MISC_7D_H       (REG_TGEN_HDMITx_MISC_BASE + 0xFB)
#define  REG_TGEN_HDMITx_MISC_7E_L       (REG_TGEN_HDMITx_MISC_BASE + 0xFC)
#define  REG_TGEN_HDMITx_MISC_7E_H       (REG_TGEN_HDMITx_MISC_BASE + 0xFD)
#define  REG_TGEN_HDMITx_MISC_7F_L       (REG_TGEN_HDMITx_MISC_BASE + 0xFE)
#define  REG_TGEN_HDMITx_MISC_7F_H       (REG_TGEN_HDMITx_MISC_BASE + 0xFF)

#define  REG_TGEN_HDMITx_SYNTH_00_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x00)
#define  REG_TGEN_HDMITx_SYNTH_00_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x01)
#define  REG_TGEN_HDMITx_SYNTH_01_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x02)
#define  REG_TGEN_HDMITx_SYNTH_01_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x03)
#define  REG_TGEN_HDMITx_SYNTH_02_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x04)
#define  REG_TGEN_HDMITx_SYNTH_02_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x05)
#define  REG_TGEN_HDMITx_SYNTH_03_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x06)
#define  REG_TGEN_HDMITx_SYNTH_03_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x07)
#define  REG_TGEN_HDMITx_SYNTH_04_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x08)
#define  REG_TGEN_HDMITx_SYNTH_04_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x09)
#define  REG_TGEN_HDMITx_SYNTH_05_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x0A)
#define  REG_TGEN_HDMITx_SYNTH_05_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x0B)
#define  REG_TGEN_HDMITx_SYNTH_06_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x0C)
#define  REG_TGEN_HDMITx_SYNTH_06_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x0D)
#define  REG_TGEN_HDMITx_SYNTH_07_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x0E)
#define  REG_TGEN_HDMITx_SYNTH_07_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x0F)
#define  REG_TGEN_HDMITx_SYNTH_08_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x10)
#define  REG_TGEN_HDMITx_SYNTH_08_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x11)
#define  REG_TGEN_HDMITx_SYNTH_09_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x12)
#define  REG_TGEN_HDMITx_SYNTH_09_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x13)
#define  REG_TGEN_HDMITx_SYNTH_0A_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x14)
#define  REG_TGEN_HDMITx_SYNTH_0A_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x15)
#define  REG_TGEN_HDMITx_SYNTH_0B_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x16)
#define  REG_TGEN_HDMITx_SYNTH_0B_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x17)
#define  REG_TGEN_HDMITx_SYNTH_0C_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x18)
#define  REG_TGEN_HDMITx_SYNTH_0C_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x19)
#define  REG_TGEN_HDMITx_SYNTH_0D_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x1A)
#define  REG_TGEN_HDMITx_SYNTH_0D_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x1B)
#define  REG_TGEN_HDMITx_SYNTH_0E_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x1C)
#define  REG_TGEN_HDMITx_SYNTH_0E_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x1D)
#define  REG_TGEN_HDMITx_SYNTH_0F_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x1E)
#define  REG_TGEN_HDMITx_SYNTH_0F_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x1F)
#define  REG_TGEN_HDMITx_SYNTH_10_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x20)
#define  REG_TGEN_HDMITx_SYNTH_10_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x21)
#define  REG_TGEN_HDMITx_SYNTH_11_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x22)
#define  REG_TGEN_HDMITx_SYNTH_11_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x23)
#define  REG_TGEN_HDMITx_SYNTH_12_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x24)
#define  REG_TGEN_HDMITx_SYNTH_12_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x25)
#define  REG_TGEN_HDMITx_SYNTH_13_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x26)
#define  REG_TGEN_HDMITx_SYNTH_13_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x27)
#define  REG_TGEN_HDMITx_SYNTH_14_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x28)
#define  REG_TGEN_HDMITx_SYNTH_14_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x29)
#define  REG_TGEN_HDMITx_SYNTH_15_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x2A)
#define  REG_TGEN_HDMITx_SYNTH_15_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x2B)
#define  REG_TGEN_HDMITx_SYNTH_16_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x2C)
#define  REG_TGEN_HDMITx_SYNTH_16_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x2D)
#define  REG_TGEN_HDMITx_SYNTH_17_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x2E)
#define  REG_TGEN_HDMITx_SYNTH_17_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x2F)
#define  REG_TGEN_HDMITx_SYNTH_18_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x30)
#define  REG_TGEN_HDMITx_SYNTH_18_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x31)
#define  REG_TGEN_HDMITx_SYNTH_19_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x32)
#define  REG_TGEN_HDMITx_SYNTH_19_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x33)
#define  REG_TGEN_HDMITx_SYNTH_1A_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x34)
#define  REG_TGEN_HDMITx_SYNTH_1A_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x35)
#define  REG_TGEN_HDMITx_SYNTH_1B_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x36)
#define  REG_TGEN_HDMITx_SYNTH_1B_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x37)
#define  REG_TGEN_HDMITx_SYNTH_1C_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x38)
#define  REG_TGEN_HDMITx_SYNTH_1C_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x39)
#define  REG_TGEN_HDMITx_SYNTH_1D_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x3A)
#define  REG_TGEN_HDMITx_SYNTH_1D_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x3B)
#define  REG_TGEN_HDMITx_SYNTH_1E_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x3C)
#define  REG_TGEN_HDMITx_SYNTH_1E_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x3D)
#define  REG_TGEN_HDMITx_SYNTH_1F_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x3E)
#define  REG_TGEN_HDMITx_SYNTH_1F_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x3F)
#define  REG_TGEN_HDMITx_SYNTH_20_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x40)
#define  REG_TGEN_HDMITx_SYNTH_20_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x41)
#define  REG_TGEN_HDMITx_SYNTH_21_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x42)
#define  REG_TGEN_HDMITx_SYNTH_21_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x43)
#define  REG_TGEN_HDMITx_SYNTH_22_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x44)
#define  REG_TGEN_HDMITx_SYNTH_22_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x45)
#define  REG_TGEN_HDMITx_SYNTH_23_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x46)
#define  REG_TGEN_HDMITx_SYNTH_23_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x47)
#define  REG_TGEN_HDMITx_SYNTH_24_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x48)
#define  REG_TGEN_HDMITx_SYNTH_24_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x49)
#define  REG_TGEN_HDMITx_SYNTH_25_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x4A)
#define  REG_TGEN_HDMITx_SYNTH_25_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x4B)
#define  REG_TGEN_HDMITx_SYNTH_26_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x4C)
#define  REG_TGEN_HDMITx_SYNTH_26_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x4D)
#define  REG_TGEN_HDMITx_SYNTH_27_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x4E)
#define  REG_TGEN_HDMITx_SYNTH_27_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x4F)
#define  REG_TGEN_HDMITx_SYNTH_28_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x50)
#define  REG_TGEN_HDMITx_SYNTH_28_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x51)
#define  REG_TGEN_HDMITx_SYNTH_29_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x52)
#define  REG_TGEN_HDMITx_SYNTH_29_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x53)
#define  REG_TGEN_HDMITx_SYNTH_2A_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x54)
#define  REG_TGEN_HDMITx_SYNTH_2A_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x55)
#define  REG_TGEN_HDMITx_SYNTH_2B_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x56)
#define  REG_TGEN_HDMITx_SYNTH_2B_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x57)
#define  REG_TGEN_HDMITx_SYNTH_2C_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x58)
#define  REG_TGEN_HDMITx_SYNTH_2C_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x59)
#define  REG_TGEN_HDMITx_SYNTH_2D_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x5A)
#define  REG_TGEN_HDMITx_SYNTH_2D_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x5B)
#define  REG_TGEN_HDMITx_SYNTH_2E_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x5C)
#define  REG_TGEN_HDMITx_SYNTH_2E_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x5D)
#define  REG_TGEN_HDMITx_SYNTH_2F_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x5E)
#define  REG_TGEN_HDMITx_SYNTH_2F_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x5F)
#define  REG_TGEN_HDMITx_SYNTH_30_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x60)
#define  REG_TGEN_HDMITx_SYNTH_30_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x61)
#define  REG_TGEN_HDMITx_SYNTH_31_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x62)
#define  REG_TGEN_HDMITx_SYNTH_31_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x63)
#define  REG_TGEN_HDMITx_SYNTH_32_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x64)
#define  REG_TGEN_HDMITx_SYNTH_32_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x65)
#define  REG_TGEN_HDMITx_SYNTH_33_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x66)
#define  REG_TGEN_HDMITx_SYNTH_33_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x67)
#define  REG_TGEN_HDMITx_SYNTH_34_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x68)
#define  REG_TGEN_HDMITx_SYNTH_34_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x69)
#define  REG_TGEN_HDMITx_SYNTH_35_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x6A)
#define  REG_TGEN_HDMITx_SYNTH_35_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x6B)
#define  REG_TGEN_HDMITx_SYNTH_36_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x6C)
#define  REG_TGEN_HDMITx_SYNTH_36_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x6D)
#define  REG_TGEN_HDMITx_SYNTH_37_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x6E)
#define  REG_TGEN_HDMITx_SYNTH_37_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x6F)
#define  REG_TGEN_HDMITx_SYNTH_38_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x70)
#define  REG_TGEN_HDMITx_SYNTH_38_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x71)
#define  REG_TGEN_HDMITx_SYNTH_39_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x72)
#define  REG_TGEN_HDMITx_SYNTH_39_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x73)
#define  REG_TGEN_HDMITx_SYNTH_3A_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x74)
#define  REG_TGEN_HDMITx_SYNTH_3A_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x75)
#define  REG_TGEN_HDMITx_SYNTH_3B_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x76)
#define  REG_TGEN_HDMITx_SYNTH_3B_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x77)
#define  REG_TGEN_HDMITx_SYNTH_3C_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x78)
#define  REG_TGEN_HDMITx_SYNTH_3C_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x79)
#define  REG_TGEN_HDMITx_SYNTH_3D_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x7A)
#define  REG_TGEN_HDMITx_SYNTH_3D_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x7B)
#define  REG_TGEN_HDMITx_SYNTH_3E_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x7C)
#define  REG_TGEN_HDMITx_SYNTH_3E_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x7D)
#define  REG_TGEN_HDMITx_SYNTH_3F_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x7E)
#define  REG_TGEN_HDMITx_SYNTH_3F_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x7F)
#define  REG_TGEN_HDMITx_SYNTH_40_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x80)
#define  REG_TGEN_HDMITx_SYNTH_40_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x81)
#define  REG_TGEN_HDMITx_SYNTH_41_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x82)
#define  REG_TGEN_HDMITx_SYNTH_41_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x83)
#define  REG_TGEN_HDMITx_SYNTH_42_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x84)
#define  REG_TGEN_HDMITx_SYNTH_42_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x85)
#define  REG_TGEN_HDMITx_SYNTH_43_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x86)
#define  REG_TGEN_HDMITx_SYNTH_43_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x87)
#define  REG_TGEN_HDMITx_SYNTH_44_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x88)
#define  REG_TGEN_HDMITx_SYNTH_44_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x89)
#define  REG_TGEN_HDMITx_SYNTH_45_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x8A)
#define  REG_TGEN_HDMITx_SYNTH_45_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x8B)
#define  REG_TGEN_HDMITx_SYNTH_46_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x8C)
#define  REG_TGEN_HDMITx_SYNTH_46_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x8D)
#define  REG_TGEN_HDMITx_SYNTH_47_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x8E)
#define  REG_TGEN_HDMITx_SYNTH_47_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x8F)
#define  REG_TGEN_HDMITx_SYNTH_48_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x90)
#define  REG_TGEN_HDMITx_SYNTH_48_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x91)
#define  REG_TGEN_HDMITx_SYNTH_49_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x92)
#define  REG_TGEN_HDMITx_SYNTH_49_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x93)
#define  REG_TGEN_HDMITx_SYNTH_4A_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x94)
#define  REG_TGEN_HDMITx_SYNTH_4A_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x95)
#define  REG_TGEN_HDMITx_SYNTH_4B_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x96)
#define  REG_TGEN_HDMITx_SYNTH_4B_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x97)
#define  REG_TGEN_HDMITx_SYNTH_4C_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x98)
#define  REG_TGEN_HDMITx_SYNTH_4C_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x99)
#define  REG_TGEN_HDMITx_SYNTH_4D_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x9A)
#define  REG_TGEN_HDMITx_SYNTH_4D_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x9B)
#define  REG_TGEN_HDMITx_SYNTH_4E_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x9C)
#define  REG_TGEN_HDMITx_SYNTH_4E_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x9D)
#define  REG_TGEN_HDMITx_SYNTH_4F_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0x9E)
#define  REG_TGEN_HDMITx_SYNTH_4F_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0x9F)
#define  REG_TGEN_HDMITx_SYNTH_50_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xA0)
#define  REG_TGEN_HDMITx_SYNTH_50_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xA1)
#define  REG_TGEN_HDMITx_SYNTH_51_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xA2)
#define  REG_TGEN_HDMITx_SYNTH_51_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xA3)
#define  REG_TGEN_HDMITx_SYNTH_52_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xA4)
#define  REG_TGEN_HDMITx_SYNTH_52_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xA5)
#define  REG_TGEN_HDMITx_SYNTH_53_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xA6)
#define  REG_TGEN_HDMITx_SYNTH_53_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xA7)
#define  REG_TGEN_HDMITx_SYNTH_54_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xA8)
#define  REG_TGEN_HDMITx_SYNTH_54_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xA9)
#define  REG_TGEN_HDMITx_SYNTH_55_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xAA)
#define  REG_TGEN_HDMITx_SYNTH_55_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xAB)
#define  REG_TGEN_HDMITx_SYNTH_56_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xAC)
#define  REG_TGEN_HDMITx_SYNTH_56_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xAD)
#define  REG_TGEN_HDMITx_SYNTH_57_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xAE)
#define  REG_TGEN_HDMITx_SYNTH_57_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xAF)
#define  REG_TGEN_HDMITx_SYNTH_58_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xB0)
#define  REG_TGEN_HDMITx_SYNTH_58_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xB1)
#define  REG_TGEN_HDMITx_SYNTH_59_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xB2)
#define  REG_TGEN_HDMITx_SYNTH_59_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xB3)
#define  REG_TGEN_HDMITx_SYNTH_5A_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xB4)
#define  REG_TGEN_HDMITx_SYNTH_5A_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xB5)
#define  REG_TGEN_HDMITx_SYNTH_5B_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xB6)
#define  REG_TGEN_HDMITx_SYNTH_5B_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xB7)
#define  REG_TGEN_HDMITx_SYNTH_5C_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xB8)
#define  REG_TGEN_HDMITx_SYNTH_5C_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xB9)
#define  REG_TGEN_HDMITx_SYNTH_5D_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xBA)
#define  REG_TGEN_HDMITx_SYNTH_5D_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xBB)
#define  REG_TGEN_HDMITx_SYNTH_5E_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xBC)
#define  REG_TGEN_HDMITx_SYNTH_5E_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xBD)
#define  REG_TGEN_HDMITx_SYNTH_5F_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xBE)
#define  REG_TGEN_HDMITx_SYNTH_5F_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xBF)
#define  REG_TGEN_HDMITx_SYNTH_60_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xC0)
#define  REG_TGEN_HDMITx_SYNTH_60_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xC1)
#define  REG_TGEN_HDMITx_SYNTH_61_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xC2)
#define  REG_TGEN_HDMITx_SYNTH_61_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xC3)
#define  REG_TGEN_HDMITx_SYNTH_62_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xC4)
#define  REG_TGEN_HDMITx_SYNTH_62_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xC5)
#define  REG_TGEN_HDMITx_SYNTH_63_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xC6)
#define  REG_TGEN_HDMITx_SYNTH_63_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xC7)
#define  REG_TGEN_HDMITx_SYNTH_64_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xC8)
#define  REG_TGEN_HDMITx_SYNTH_64_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xC9)
#define  REG_TGEN_HDMITx_SYNTH_65_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xCA)
#define  REG_TGEN_HDMITx_SYNTH_65_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xCB)
#define  REG_TGEN_HDMITx_SYNTH_66_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xCC)
#define  REG_TGEN_HDMITx_SYNTH_66_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xCD)
#define  REG_TGEN_HDMITx_SYNTH_67_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xCE)
#define  REG_TGEN_HDMITx_SYNTH_67_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xCF)
#define  REG_TGEN_HDMITx_SYNTH_68_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xD0)
#define  REG_TGEN_HDMITx_SYNTH_68_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xD1)
#define  REG_TGEN_HDMITx_SYNTH_69_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xD2)
#define  REG_TGEN_HDMITx_SYNTH_69_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xD3)
#define  REG_TGEN_HDMITx_SYNTH_6A_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xD4)
#define  REG_TGEN_HDMITx_SYNTH_6A_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xD5)
#define  REG_TGEN_HDMITx_SYNTH_6B_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xD6)
#define  REG_TGEN_HDMITx_SYNTH_6B_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xD7)
#define  REG_TGEN_HDMITx_SYNTH_6C_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xD8)
#define  REG_TGEN_HDMITx_SYNTH_6C_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xD9)
#define  REG_TGEN_HDMITx_SYNTH_6D_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xDA)
#define  REG_TGEN_HDMITx_SYNTH_6D_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xDB)
#define  REG_TGEN_HDMITx_SYNTH_6E_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xDC)
#define  REG_TGEN_HDMITx_SYNTH_6E_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xDD)
#define  REG_TGEN_HDMITx_SYNTH_6F_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xDE)
#define  REG_TGEN_HDMITx_SYNTH_6F_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xDF)
#define  REG_TGEN_HDMITx_SYNTH_70_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xE0)
#define  REG_TGEN_HDMITx_SYNTH_70_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xE1)
#define  REG_TGEN_HDMITx_SYNTH_71_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xE2)
#define  REG_TGEN_HDMITx_SYNTH_71_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xE3)
#define  REG_TGEN_HDMITx_SYNTH_72_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xE4)
#define  REG_TGEN_HDMITx_SYNTH_72_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xE5)
#define  REG_TGEN_HDMITx_SYNTH_73_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xE6)
#define  REG_TGEN_HDMITx_SYNTH_73_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xE7)
#define  REG_TGEN_HDMITx_SYNTH_74_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xE8)
#define  REG_TGEN_HDMITx_SYNTH_74_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xE9)
#define  REG_TGEN_HDMITx_SYNTH_75_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xEA)
#define  REG_TGEN_HDMITx_SYNTH_75_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xEB)
#define  REG_TGEN_HDMITx_SYNTH_76_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xEC)
#define  REG_TGEN_HDMITx_SYNTH_76_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xED)
#define  REG_TGEN_HDMITx_SYNTH_77_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xEE)
#define  REG_TGEN_HDMITx_SYNTH_77_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xEF)
#define  REG_TGEN_HDMITx_SYNTH_78_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xF0)
#define  REG_TGEN_HDMITx_SYNTH_78_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xF1)
#define  REG_TGEN_HDMITx_SYNTH_79_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xF2)
#define  REG_TGEN_HDMITx_SYNTH_79_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xF3)
#define  REG_TGEN_HDMITx_SYNTH_7A_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xF4)
#define  REG_TGEN_HDMITx_SYNTH_7A_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xF5)
#define  REG_TGEN_HDMITx_SYNTH_7B_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xF6)
#define  REG_TGEN_HDMITx_SYNTH_7B_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xF7)
#define  REG_TGEN_HDMITx_SYNTH_7C_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xF8)
#define  REG_TGEN_HDMITx_SYNTH_7C_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xF9)
#define  REG_TGEN_HDMITx_SYNTH_7D_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xFA)
#define  REG_TGEN_HDMITx_SYNTH_7D_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xFB)
#define  REG_TGEN_HDMITx_SYNTH_7E_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xFC)
#define  REG_TGEN_HDMITx_SYNTH_7E_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xFD)
#define  REG_TGEN_HDMITx_SYNTH_7F_L       (REG_TGEN_HDMITx_SYNTH_BASE + 0xFE)
#define  REG_TGEN_HDMITx_SYNTH_7F_H       (REG_TGEN_HDMITx_SYNTH_BASE + 0xFF)

#ifdef __cplusplus
}
#endif

#undef _DRVADCTBL_H_
#endif
