
#define A_RIU_PM_BASE   	(0x1F000000)

#define PMGPIO_BANK			GET_CARD_REG_ADDR(A_RIU_PM_BASE, 0x700)
#define RIU_BASE_FCIE		GET_CARD_REG_ADDR(A_RIU_BASE, 0x8800)

#define CHIPTOP6			GET_CARD_REG_ADDR(A_CHIPTOP_BANK, 0x06)
#define CHIPTOP25			GET_CARD_REG_ADDR(A_CHIPTOP_BANK, 0x25)
#define CHIPTOP35			GET_CARD_REG_ADDR(A_CHIPTOP_BANK, 0x35)
#define ALL_PAD_IN			GET_CARD_REG_ADDR(A_CHIPTOP_BANK, 0x50)

#define PMGPIO_CTL			GET_CARD_REG_ADDR(PMGPIO_BANK, 0x35)
#define PMGPIO_OE			GET_CARD_REG_ADDR(PMGPIO_BANK, 0x0F)
#define PMGPIO_MASK			GET_CARD_REG_ADDR(PMGPIO_BANK, 0x00)
#define PMGPIO_RAWST		GET_CARD_REG_ADDR(PMGPIO_BANK, 0x0C)
#define PMGPIO_FINALST		GET_CARD_REG_ADDR(PMGPIO_BANK, 0x0A)
#define PMGPIO_CLR			GET_CARD_REG_ADDR(PMGPIO_BANK, 0x04)
#define PMGPIO_POL			GET_CARD_REG_ADDR(PMGPIO_BANK, 0x06)

#define MIE_PATH_CTL		GET_CARD_REG_ADDR(RIU_BASE_FCIE, 0x0A)
#define SD_MODE				GET_CARD_REG_ADDR(RIU_BASE_FCIE, 0x10)
#define NC_REORDER			GET_CARD_REG_ADDR(RIU_BASE_FCIE, 0x2D)




#define BIT_GPIO_IN         BIT02
#define BIT_GPIO_FIQ_MASK   BIT04
#define BIT_GPIO_FIQ_CLR    BIT06
#define BIT_GPIO_FIQ_POL    BIT07
#define BIT_GPIO_FIQ_FINAL  BIT08

#define   CLOCK_GEN_REG		0x69
#define   _48M					(15<<2)
#define   _43M					(6<<2)
#define   _36M					(4<<2)
#define   _32M					(3<<2)
#define   _27M					(2<<2)
#define   _18M					(0<<2)
#define   _300K					(13<<2)


