#
# Makefile for CPU LX size   drivers.
#

# general options
EXTRA_CFLAGS      +=  -Idrivers/mstar/include
EXTRA_CFLAGS      +=  -Idrivers/mstar/cpu

# files
obj-y     += mem-ory.o
mem-ory-objs                       += memory.o
