/*!
*********************************************************************************************************
* This product contains one or more programs protected under international and U.S. copyright laws
* as unpublished works.  They are confidential and proprietary to Dolby Laboratories.
* Their reproduction or disclosure, in whole or in part, or the production of derivative works therefrom
* without the express permission of Dolby Laboratories is prohibited.


* Copyright 2011 - 2013 by Dolby Laboratories.  All rights reserved.
*********************************************************************************************************
*/


// Generated by Matlab do not change directly
#ifndef _DM_FXPT_Q_H_
#define _DM_FXPT_Q_H_


#define QLOG2OUT        26
#define QPOW2IN         24
#define QSLOPEIN        30
#define QB02DATAIN      31
#define QSLOPEROLLOFF   28
#define QTCLUT          12
#define QSCREEN_RATIO   27
#define QTRIMS          28     // Not to exceed 28


#endif

