/*!
*********************************************************************************************************
* This product contains one or more programs protected under international and U.S. copyright laws
* as unpublished works.  They are confidential and proprietary to Dolby Laboratories.
* Their reproduction or disclosure, in whole or in part, or the production of derivative works therefrom
* without the express permission of Dolby Laboratories is prohibited.


* Copyright 2011 - 2013 by Dolby Laboratories.  All rights reserved.
*********************************************************************************************************
*/


// Generated by Matlab do not change directly


//LPFilter - xf
const U32 lpf_xf[11] = {36,111,267,498,725,822,725,498,267,111,36};

//LPFilter - yf
const U32 lpf_yf[5] = {223,1000,1650,1000,223};

//Edge - xd
const S32 edge_xd[11] = {180,445,800,997,725,0,-725,-997,-800,-445,-180};

//Edge - yd
const S32 edge_yd[5] = {446,1000,0,-1000,-446};
