EXTRA_CFLAGS      +=  -Idrivers/mstar/include

# Cedric Platform Support
obj-$(CONFIG_MS_SOUND_CEDRIC) += bach_pcm.o bach_soc.o bach_codec.o bach.o
obj-$(CONFIG_MS_SOUND_CHICAGO) += haydn_pcm.o haydn_dai.o haydn_soc.o haydn_codec.o haydn.o
obj-$(CONFIG_MS_SOUND_INFINITY) += infinity_dai.o infinity_pcm.o infinity_soc.o infinity_codec.o infinity.o


