/*
 * mdrv_sound_io.h
 *
 *  Created on: Jul 12, 2016
 *      Author: trevor.wu
 */

#ifndef DRV_AUDIO_IO_H_
#define DRV_AUDIO_IO_H_


#define AUDIO_IOCTL_MAGIC               'S'


#define AUDRV_PCM_TEST _IOW(AUDIO_IOCTL_MAGIC, 0x0, struct AUD_PcmCfg_s)
#define AUDRV_ADC_MUX  _IOW(AUDIO_IOCTL_MAGIC, 0x1,  int)
#define AUDRV_LINEIN_GAIN  _IOW(AUDIO_IOCTL_MAGIC, 0x2,  int)
#define AUDRV_MIC_GAIN  _IOW(AUDIO_IOCTL_MAGIC, 0x3,  int)
#define AUDRV_MICPRE_GAIN  _IOW(AUDIO_IOCTL_MAGIC, 0x4,  int)
/*#define AUDRV_PCM_IOCTL_HW_PARAMS _IOWR(AUDIO_IOCTL_MAGIC, 0x0, struct AUD_PcmCfg_s)
#define AUDRV_PCM_IOCTL_OPEN _IO(AUDIO_IOCTL_MAGIC, 0x1)
#define AUDRV_PCM_IOCTL_START _IO(AUDIO_IOCTL_MAGIC, 0x2)
#define AUDRV_PCM_IOCTL_STOP _IO(AUDIO_IOCTL_MAGIC, 0x3)
#define AUDRV_PCM_IOCTL_PAUSE _IO(AUDIO_IOCTL_MAGIC, 0x4)
#define AUDRV_PCM_IOCTL_RESUME _IO(AUDIO_IOCTL_MAGIC, 0x5)
#define AUDRV_PCM_IOCTL_XRUN _IO(AUDIO_IOCTL_MAGIC, 0x6)
#define AUDRV_PCM_IOCTL_WRITE_FRAMES _IOW(AUDIO_IOCTL_MAGIC, 0x7, struct AUD_Xfer_s)
#define AUDRV_PCM_IOCTL_READ_FRAMES _IOR(AUDIO_IOCTL_MAGIC, 0x8, struct AUD_Xfer_s)
#define AUDRV_I2S_IOCTL_HW_PARAMS _IOWR(AUDIO_IOCTL_MAGIC, 0x9, struct AUD_I2sCfg_s)
*/
#define IOCTL_AUDIO_MAXNR 0x4

#endif /* DRV_AUDIO_IO_H_ */
