/* Copyright (C) 2014 Cadence Design Systems.  All rights reserved           */
/* THIS FILE IS AUTOMATICALLY GENERATED BY CADENCE BLUEPRINT, DO NOT EDIT    */
/*                                                                           */


#ifndef __REG_CDN_AXI_WRAPPER_IB_MACRO_H__
#define __REG_CDN_AXI_WRAPPER_IB_MACRO_H__


/* macros for BlueprintGlobalNameSpace::cdn_axi_wrapper_ib::axiw_ib_region_ad0 */
#ifndef __CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0_MACRO__
#define __CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0_MACRO__

/* macros for field num_bits */
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__NUM_BITS__SHIFT               0
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__NUM_BITS__WIDTH               6
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__NUM_BITS__MASK      0x0000003fU
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__NUM_BITS__READ(src) \
                    (uint32_t)(src)\
                    & 0x0000003fU
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__NUM_BITS__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0x0000003fU)
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__NUM_BITS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x0000003fU) | ((uint32_t)(src) &\
                    0x0000003fU)
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__NUM_BITS__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0x0000003fU)))

/* macros for field rsvd0 */
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__RSVD0__SHIFT                  6
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__RSVD0__WIDTH                  2
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__RSVD0__MASK         0x000000c0U
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__RSVD0__READ(src) \
                    (((uint32_t)(src)\
                    & 0x000000c0U) >> 6)

/* macros for field data */
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__DATA__SHIFT                   8
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__DATA__WIDTH                  24
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__DATA__MASK          0xffffff00U
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__DATA__READ(src) \
                    (((uint32_t)(src)\
                    & 0xffffff00U) >> 8)
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__DATA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 8) & 0xffffff00U)
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__DATA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0xffffff00U) | (((uint32_t)(src) <<\
                    8) & 0xffffff00U)
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__DATA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 8) & ~0xffffff00U)))
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__TYPE                   uint32_t
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__READ                0xffffffffU
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0__WRITE               0xffffffffU

#endif /* __CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD0_MACRO__ */


/* macros for addr0 */
#define INST_ADDR0__NUM                                                       1

/* macros for BlueprintGlobalNameSpace::cdn_axi_wrapper_ib::axiw_ib_region_ad1 */
#ifndef __CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD1_MACRO__
#define __CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD1_MACRO__

/* macros for field data */
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD1__DATA__SHIFT                   0
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD1__DATA__WIDTH                  32
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD1__DATA__MASK          0xffffffffU
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD1__DATA__READ(src) \
                    (uint32_t)(src)\
                    & 0xffffffffU
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD1__DATA__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0xffffffffU)
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD1__DATA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0xffffffffU) | ((uint32_t)(src) &\
                    0xffffffffU)
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD1__DATA__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0xffffffffU)))
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD1__TYPE                   uint32_t
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD1__READ                0xffffffffU
#define CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD1__WRITE               0xffffffffU

#endif /* __CDN_AXI_WRAPPER_IB__AXIW_IB_REGION_AD1_MACRO__ */


/* macros for addr1 */
#define INST_ADDR1__NUM                                                       1

#endif /* __REG_CDN_AXI_WRAPPER_IB_MACRO_H__ */
