# general options
EXTRA_CFLAGS                +=  -Idrivers/mstar/include
EXTRA_CFLAGS                +=  -Idrivers/mstar/include/cedric
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/include
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/api
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3
#-------------- msos --------------
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/msos
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/irq
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/irq
#-------------- mmio --------------
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/mmio
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/mmio
#-------------- PNL --------------
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/api/pnl
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/pnl
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/pnl/include
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/pnl
#-------------- XC --------------
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/api/xc
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/xc
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/xc/include
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/xc
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/xc/include
#EXTRA_CFLAGS		    	+=  -Wno-declaration-after-statement
#-------------- ACE --------------
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/api/ace
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/ace
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/ace/include
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/ace
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/ace/include
#-------------- ve --------------
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/ve
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/ve/include
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/ve
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/ve/include
#-------------- pq --------------
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/pq
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/pq/include
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/pq/hal/c3/
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/pq/hal/c3/include
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/pq/hal/c3/include/SC0
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/pq/hal/c3/include/SC1
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/pq/hal/c3/include/SC2

#-------------- mvop --------------
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/mvop
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/mvop

#-------------- miu --------------
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/miu
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/miu

#-------------- avd --------------
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/avd
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/avd
#-------------- dlc --------------
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/dlc
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/dlc/include
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/dlc
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/dlc/include
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/api/dlc
#-------------- HDMITx --------------
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/hdmitx
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/hdmitx/include
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/hdmitx
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/hdmitx/include
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/api/hdmitx
#-------------- CEC --------------
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/hal/c3/cec/include
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/cec
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/drv/cec/include
EXTRA_CFLAGS                +=  -Idrivers/mstar/sca/drv/api/cec


ccflags-y  := -DMSOS_TYPE_LINUX_KERNEL -DCHIP_C3 -DMULTI_SCALER_SUPPORTED -DSCA_ENABLE_DLC -DSCA_ENABLE_HDMITX_HPD


ccflags-$(CONFIG_MS_DUAL_SCREEN) += -D__DUAL_SCREEN__
ccflags-$(CONFIG_MS_SCALER_BOOT_PNL) += -D__BOOT_PNL__
ccflags-$(CONFIG_MS_DUAL_SCREEN_HDMITX) += -D__DUAL_SCREEN_HDMITX__

# files
obj-$(CONFIG_MS_SCALER)  := kdrv_sca.o 
kdrv_sca-y   += mdrv_sca_io.o
kdrv_sca-y   += mdrv_sca.o
kdrv_sca-y   += mdrv_sca_modeparse.o
kdrv_sca-y   += mdrv_sca_color.o
kdrv_sca-y   += mdrv_sca_inputsource.o
kdrv_sca-y   += msapi_vd.o
kdrv_sca-y   += mdrv_sca_avd.o
#kdrv_sca-y   += sgm6502.o
#obj-$(CONFIG_MS_MST701)   += mdrv_sca_mst701.o
kdrv_sca-y   += mdrv_sca_hdmitx.o
kdrv_sca-y   += dev_info.o

#-------------- utopia --------------
kdrv_sca-y   += drv/msos/MsOS.o
kdrv_sca-y   += drv/drv/mmio/drvMMIO.o
kdrv_sca-y   += drv/hal/c3/mmio/halMMIO.o
#-------------- PNL --------------
kdrv_sca-y   += drv/api/pnl/apiPNL.o
kdrv_sca-y   += drv/drv/pnl/drvPNL.o
kdrv_sca-y   += drv/hal/c3/pnl/halPNL.o

#-------------- XC --------------
kdrv_sca-y   += drv/hal/c3/xc/mhal_adc.o
kdrv_sca-y   += drv/hal/c3/xc/mhal_dip.o
kdrv_sca-y   += drv/hal/c3/xc/mhal_frc.o
kdrv_sca-y   += drv/hal/c3/xc/mhal_hdmi.o
kdrv_sca-y   += drv/hal/c3/xc/mhal_idac.o
kdrv_sca-y   += drv/hal/c3/xc/mhal_ip.o
kdrv_sca-y   += drv/hal/c3/xc/mhal_menuload.o
kdrv_sca-y   += drv/hal/c3/xc/mhal_mux.o
kdrv_sca-y   += drv/hal/c3/xc/mhal_offline.o
kdrv_sca-y   += drv/hal/c3/xc/mhal_pip.o
kdrv_sca-y   += drv/hal/c3/xc/mhal_rotate.o
kdrv_sca-y   += drv/hal/c3/xc/mhal_sc.o
kdrv_sca-y   += drv/hal/c3/xc/mhal_tgen.o
kdrv_sca-y   += drv/drv/xc/apiXC_Adc.o
kdrv_sca-y   += drv/drv/xc/drvScaler_NR.o
kdrv_sca-y   += drv/drv/xc/dynamic_scale.o
kdrv_sca-y   += drv/drv/xc/mdrv_adc.o
kdrv_sca-y   += drv/drv/xc/mdrv_frc.o
kdrv_sca-y   += drv/drv/xc/mdrv_hdmi.o
kdrv_sca-y   += drv/drv/xc/mdrv_idac.o
kdrv_sca-y   += drv/drv/xc/mdrv_mux.o
kdrv_sca-y   += drv/drv/xc/mdrv_offline.o
kdrv_sca-y   += drv/drv/xc/mdrv_rotate.o
kdrv_sca-y   += drv/drv/xc/mdrv_sc_3d.o
kdrv_sca-y   += drv/drv/xc/mdrv_sc_display.o
kdrv_sca-y   += drv/drv/xc/mdrv_sc_ip.o
kdrv_sca-y   += drv/drv/xc/mdrv_sc_isr.o
kdrv_sca-y   += drv/drv/xc/mdrv_sc1_isr.o
kdrv_sca-y   += drv/drv/xc/mdrv_sc2_isr.o
kdrv_sca-y   += drv/drv/xc/mdrv_dipw_isr.o
kdrv_sca-y   += drv/drv/xc/mdrv_sc_menuload.o
kdrv_sca-y   += drv/drv/xc/mdrv_sc_pip.o
kdrv_sca-y   += drv/drv/xc/mdrv_sc_scaling.o
kdrv_sca-y   += drv/drv/xc/mdrv_xc_calibration.o
kdrv_sca-y   += drv/drv/xc/mvideo.o
kdrv_sca-y   += drv/drv/xc/mvideo_context.o
kdrv_sca-y   += drv/api/xc/apiXC_Auto.o
kdrv_sca-y   += drv/api/xc/apiXC_ModeParse.o
kdrv_sca-y   += drv/api/xc/apiXC_PCMonitor.o

#-------------- ACE --------------
kdrv_sca-y   += drv/hal/c3/ace/mhal_ace.o
kdrv_sca-y   += drv/drv/ace/drvACE.o
kdrv_sca-y   += drv/drv/ace/MsAce.o
kdrv_sca-y   += drv/api/ace/apiXC_Ace.o

#-------------- ve --------------
kdrv_sca-y   += drv/hal/c3/ve/mhal_tvencoder.o
kdrv_sca-y   += drv/drv/ve/drvTVEncoder.o

#-------------- pq --------------
kdrv_sca-y   += drv/pq/drvPQ.o
kdrv_sca-y   += drv/pq/drvPQ_Bin.o
kdrv_sca-y   += drv/pq/drvPQ_Text.o
kdrv_sca-y   += drv/pq/drvbw.o
kdrv_sca-y   += drv/pq/hal/c3/mhal_pq.o
kdrv_sca-y   += drv/pq/hal/c3/QualityMap_Main.o
kdrv_sca-y   += drv/pq/hal/c3/QualityMap_MainEx.o
kdrv_sca-y   += drv/pq/hal/c3/QualityMap_SC1_Main.o
kdrv_sca-y   += drv/pq/hal/c3/QualityMap_SC1_MainEx.o
kdrv_sca-y   += drv/pq/hal/c3/QualityMap_SC2_Main.o
kdrv_sca-y   += drv/pq/hal/c3/QualityMap_SC2_MainEx.o
kdrv_sca-y   += drv/pq/hal/c3/QualityMap_SC2_Sub.o
kdrv_sca-y   += drv/pq/hal/c3/QualityMap_SC2_SubEx.o
kdrv_sca-y   += drv/pq/hal/c3/QualityMap_Sub.o
kdrv_sca-y   += drv/pq/hal/c3/QualityMap_SubEx.o

#-------------- mvop --------------
kdrv_sca-y   += drv/hal/c3/mvop/halMVOP.o
kdrv_sca-y   += drv/drv/mvop/drvMVOP.o

#-------------- miu --------------
kdrv_sca-y   += drv/hal/c3/miu/halMIU.o
kdrv_sca-y   += drv/drv/miu/drvMIU.o

#-------------- avd --------------
kdrv_sca-y   += drv/hal/c3/avd/halAVD.o
kdrv_sca-y   += drv/drv/avd/drvAVD.o

#-------------- dlc --------------
kdrv_sca-y   += drv/hal/c3/dlc/MsDlc.o
kdrv_sca-y   += drv/hal/c3/dlc/mhal_dlc.o
kdrv_sca-y   += drv/drv/dlc/MsDBC.o
kdrv_sca-y   += drv/drv/dlc/drvDLC.o
kdrv_sca-y   += drv/api/dlc/apiXC_Dlc.o

#-------------- HDMITx --------------
kdrv_sca-y   += drv/hal/c3/hdmitx/halHDMIUtilTx.o
kdrv_sca-y   += drv/hal/c3/hdmitx/halHDMITx.o
kdrv_sca-y   += drv/hal/c3/hdmitx/halHDCPTx.o
kdrv_sca-y   += drv/drv/hdmitx/drvHDMITx.o
#kdrv_sca-y   += drv/drv/hdmitx/bigd.o
#kdrv_sca-y   += drv/drv/hdmitx/bigdigits.o
#kdrv_sca-y   += drv/drv/hdmitx/bigdigitsRand.o
#kdrv_sca-y   += drv/drv/hdmitx/bigdRand.o
#kdrv_sca-y   += drv/drv/hdmitx/spExtras.o
kdrv_sca-y   += drv/api/hdmitx/apiHDMITx.o

#-------------- CEC --------------
kdrv_sca-y   += drv/hal/c3/cec/mhal_cec.o
kdrv_sca-y   += drv/drv/cec/drvCEC.o
kdrv_sca-y   += drv/api/cec/apiCEC.o
