/*!
*********************************************************************************************************
* This product contains one or more programs protected under international and U.S. copyright laws 
* as unpublished works.  They are confidential and proprietary to Dolby Laboratories.  
* Their reproduction or disclosure, in whole or in part, or the production of derivative works therefrom 
* without the express permission of Dolby Laboratories is prohibited.  


* Copyright 2011 - 2015 by Dolby Laboratories.  All rights reserved.
*********************************************************************************************************
*/


 // Generated by Matlab do not change directly

 #define MULTISCALE_LPF_SCALE     12
 #define MULTISCALE_EDGE_SCALE    12

 #define SATURATION_CVDR_SCALE    12
 #define SATURATION_CINV_SCALE    20
 #define SATURATION_VINV_SCALE    14
