
#if PQ_GRULE_NR_ENABLE
code U8 MST_GRule_NR_IP_Index_Sub[PQ_GRULE_NR_IP_NUM_Sub]=
{
    PQ_IP_DNR_Sub,
    PQ_IP_DNR_Y_Sub,
    PQ_IP_DNR_C_Sub,
};
#endif


#if PQ_GRULE_NR_ENABLE
code U8 MST_GRule_NR_Sub[QM_INPUTTYPE_NUM_Sub][PQ_GRULE_NR_NUM_Sub][PQ_GRULE_NR_IP_NUM_Sub]=
{
    #if PQ_QM_CVBS
    {//RF_NTSC_44, 0
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//RF_NTSC_M, 1
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//RF_PAL_BGHI, 2
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//RF_PAL_60, 3
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//RF_PAL_M, 4
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//RF_PAL_N, 5
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//RF_SECAM, 6
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//VIF_NTSC_44, 7
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//VIF_NTSC_M, 8
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//VIF_PAL_BGHI, 9
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//VIF_PAL_60, 10
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//VIF_PAL_M, 11
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//VIF_PAL_N, 12
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//VIF_SECAM, 13
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SV_NTSC_44, 14
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SV_NTSC_M, 15
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SV_PAL_BGHI, 16
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SV_PAL_60, 17
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SV_PAL_M, 18
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SV_PAL_N, 19
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SV_SECAM, 20
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//AV_NTSC_44, 21
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//AV_NTSC_M, 22
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//AV_PAL_BGHI, 23
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//AV_PAL_60, 24
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//AV_PAL_M, 25
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//AV_PAL_N, 26
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//AV_SECAM, 27
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_AV_NTSC_44, 28
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_AV_NTSC_M, 29
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_AV_PAL_BGHI, 30
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_AV_PAL_60, 31
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_AV_PAL_M, 32
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_AV_PAL_N, 33
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_AV_SECAM, 34
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_SV_NTSC_44, 35
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_SV_NTSC_M, 36
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_SV_PAL_BGHI, 37
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_SV_PAL_60, 38
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_SV_PAL_M, 39
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_SV_PAL_N, 40
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_SV_SECAM, 41
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_RGB_NTSC, 42
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_CVBS
    {//SCART_RGB_PAL, 43
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_YPBPR
    {//YPbPr_480i, 44
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_YPBPR
    {//YPbPr_576i, 45
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_YPBPR
    {//YPbPr_480p, 46
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_YPBPR
    {//YPbPr_576p, 47
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_YPBPR
    {//YPbPr_720p_24hz, 48
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_YPBPR
    {//YPbPr_720p_50hz, 49
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_YPBPR
    {//YPbPr_720p_60hz, 50
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_YPBPR
    {//YPbPr_1080i_50hz, 51
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_YPBPR
    {//YPbPr_1080i_60hz, 52
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_YPBPR
    {//YPbPr_1080p_24hz, 53
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_YPBPR
    {//YPbPr_1080p_50hz, 54
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_YPBPR
    {//YPbPr_1080p_60hz, 55
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//HDMI_480i, 56
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//HDMI_576i, 57
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//HDMI_480p, 58
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//HDMI_576p, 59
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//HDMI_720p_24hz, 60
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//HDMI_720p_50hz, 61
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//HDMI_720p_60hz, 62
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//HDMI_1080i_50hz, 63
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//HDMI_1080i_60hz, 64
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//HDMI_1080p_24hz, 65
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//HDMI_1080p_60hz, 66
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//HDMI_1080p_50hz, 67
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_444_PC_Hup_Vup, 68
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_444_PC_Hup_Vdown, 69
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_444_PC_Hup_Vno, 70
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_444_PC_Hdown_Vup, 71
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_444_PC_Hdown_Vdown, 72
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_444_PC_Hdown_Vno, 73
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_444_PC_Hno_Vup, 74
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_444_PC_Hno_Vdown, 75
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_444_PC_Hno_Vno, 76
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_422_PC_Hup_Vup, 77
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_422_PC_Hup_Vdown, 78
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_422_PC_Hup_Vno, 79
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_422_PC_Hdown_Vup, 80
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_422_PC_Hdown_Vdown, 81
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_422_PC_Hdown_Vno, 82
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_422_PC_Hno_Vup, 83
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_422_PC_Hno_Vdown, 84
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_HDMI_PC
    {//HDMI_422_PC_Hno_Vno, 85
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_PC
    {//DVI_Dsub_HDMI_RGB_PC_Hup_Vup, 86
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_PC
    {//DVI_Dsub_HDMI_RGB_PC_Hup_Vdown, 87
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_PC
    {//DVI_Dsub_HDMI_RGB_PC_Hup_Vno, 88
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_PC
    {//DVI_Dsub_HDMI_RGB_PC_Hdown_Vup, 89
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_PC
    {//DVI_Dsub_HDMI_RGB_PC_Hdown_Vdown, 90
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_PC
    {//DVI_Dsub_HDMI_RGB_PC_Hdown_Vno, 91
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_PC
    {//DVI_Dsub_HDMI_RGB_PC_Hno_Vup, 92
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_PC
    {//DVI_Dsub_HDMI_RGB_PC_Hno_Vdown, 93
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_PC
    {//DVI_Dsub_HDMI_RGB_PC_Hno_Vno, 94
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_480i_352x480_MPEG2, 95
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_480i_MPEG2, 96
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_576i_MPEG2, 97
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_480p_MPEG2, 98
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_576p_MPEG2, 99
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_720p_24hz_MPEG2, 100
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_720p_50hz_MPEG2, 101
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_720p_60hz_MPEG2, 102
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_1080i_50hz_MPEG2, 103
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_1080i_60hz_MPEG2, 104
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_1080p_24hz_MPEG2, 105
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_1080p_50hz_MPEG2, 106
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_1080p_60hz_MPEG2, 107
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_480i_352x480_H264, 108
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_480i_H264, 109
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_576i_H264, 110
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_480p_H264, 111
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_576p_H264, 112
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_720p_24hz_H264, 113
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_720p_50hz_H264, 114
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_720p_60hz_H264, 115
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_1080i_50hz_H264, 116
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_1080i_60hz_H264, 117
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_1080p_24hz_H264, 118
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_1080p_50hz_H264, 119
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_1080p_60hz_H264, 120
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_MM_VIDEO
    {//Multimedia_video_SD_interlace, 121
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_MM_VIDEO
    {//Multimedia_video_SD_progressive, 122
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_MM_VIDEO
    {//Multimedia_video_HD_interlace, 123
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_MM_VIDEO
    {//Multimedia_video_HD_progressive, 124
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_MM_PHOTO
    {//Multimedia_photo_SD_progressive, 125
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_MM_PHOTO
    {//Multimedia_photo_HD_progressive, 126
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_iFrame_SD_interlace, 127
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_iFrame_SD_progressive, 128
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_iFrame_HD_interlace, 129
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_DTV
    {//DTV_iFrame_HD_progressive, 130
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_1_Sub,
            PQ_IP_DNR_C_DC_1_Sub,
        },
        {//Middle
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_5_Sub,
            PQ_IP_DNR_C_DC_3_Sub,
        },
        {//High
            PQ_IP_DNR_ON_Sub,
            PQ_IP_DNR_Y_DY_7_Sub,
            PQ_IP_DNR_C_DC_5_Sub,
        },
    },
    #endif
    #if PQ_QM_3D
    {//3D_Video_interlace, 131
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Middle
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//High
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
    },
    #endif
    #if PQ_QM_3D
    {//3D_Video_progressive, 132
        {//Off
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Low
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//Middle
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
        {//High
            PQ_IP_DNR_NR_OFF_Sub,
            PQ_IP_DNR_Y_OFF_Sub,
            PQ_IP_DNR_C_OFF_Sub,
        },
    },
    #endif
};
#endif

