#
# Makefile for MStar mtlb 
#
EXTRA_CFLAGS      +=  -Idrivers/mstar2/include/sys/common
EXTRA_CFLAGS      +=  -Idrivers/mstar2/include
EXTRA_CFLAGS      +=  -Idrivers/mstar2/drv/ipa_pool
EXTRA_CFLAGS      +=  -Idrivers/mstar2/drv/miu
EXTRA_CFLAGS      +=  -Idrivers/staging/android/ion
EXTRA_CFLAGS      +=  -Iinclude/linux

# files
obj-y     += ipa_cma.o
