#
# Makefile for MStar Semutex device drivers.
#

# general options
EXTRA_CFLAGS      +=  -Idrivers/mstar2/include
EXTRA_CFLAGS      +=  -Idrivers/mstar2/drv/semutex
# specific options
EXTRA_CFLAGS      +=

# files
obj-$(CONFIG_MSTAR_SEMUTEX)	+= mdrv-semutex.o
mdrv-semutex-objs			+= mdrv_semutex.o
