//=========================== Module:PLATFORM=======================================
#ifdef CONFIG_MP_PLATFORM_ARCH_GENERAL
#define MP_PLATFORM_ARCH_GENERAL 1
#else
#define MP_PLATFORM_ARCH_GENERAL 0
#endif

#ifdef CONFIG_MP_PLATFORM_ARCH_GENERAL_DEBUG
#define MP_PLATFORM_ARCH_GENERAL_DEBUG 1
#else
#define MP_PLATFORM_ARCH_GENERAL_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_ARM
#define MP_PLATFORM_ARM 1
#else
#define MP_PLATFORM_ARM 0
#endif

#ifdef CONFIG_MP_PLATFORM_ARM_DEBUG
#define MP_PLATFORM_ARM_DEBUG 1
#else
#define MP_PLATFORM_ARM_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_MIPS
#define MP_PLATFORM_MIPS 1
#else
#define MP_PLATFORM_MIPS 0
#endif

#ifdef CONFIG_MP_PLATFORM_MIPS_DEBUG
#define MP_PLATFORM_MIPS_DEBUG 1
#else
#define MP_PLATFORM_MIPS_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_PM
#define MP_PLATFORM_PM 1
#else
#define MP_PLATFORM_PM 0
#endif

#ifdef CONFIG_MP_PLATFORM_PM_DEBUG
#define MP_PLATFORM_PM_DEBUG 1
#else
#define MP_PLATFORM_PM_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_ARM_ERRATA_775420
#define MP_PLATFORM_ARM_ERRATA_775420 1
#else
#define MP_PLATFORM_ARM_ERRATA_775420 0
#endif

#ifdef CONFIG_MP_PLATFORM_ARM_ERRATA_775420_DEBUG
#define MP_PLATFORM_ARM_ERRATA_775420_DEBUG 1
#else
#define MP_PLATFORM_ARM_ERRATA_775420_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_ARM_ERRATA_835769
#define MP_PLATFORM_ARM_ERRATA_835769 1
#else
#define MP_PLATFORM_ARM_ERRATA_835769 0
#endif

#ifdef CONFIG_MP_PLATFORM_ARM_ERRATA_835769_DEBUG
#define MP_PLATFORM_ARM_ERRATA_835769_DEBUG 1
#else
#define MP_PLATFORM_ARM_ERRATA_835769_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_ARM_64bit_POARTING
#define MP_PLATFORM_ARM_64bit_POARTING 1
#else
#define MP_PLATFORM_ARM_64bit_POARTING 0
#endif

#ifdef CONFIG_MP_PLATFORM_ARM_64bit_POARTING_DEBUG
#define MP_PLATFORM_ARM_64bit_POARTING_DEBUG 1
#else
#define MP_PLATFORM_ARM_64bit_POARTING_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_ARM_64bit_BOOTARGS_NODTB
#define MP_PLATFORM_ARM_64bit_BOOTARGS_NODTB 1
#else
#define MP_PLATFORM_ARM_64bit_BOOTARGS_NODTB 0
#endif

#ifdef CONFIG_MP_PLATFORM_ARM_64bit_BOOTARGS_NODTB_DEBUG
#define MP_PLATFORM_ARM_64bit_BOOTARGS_NODTB_DEBUG 1
#else
#define MP_PLATFORM_ARM_64bit_BOOTARGS_NODTB_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_MSTAR_LEGANCY_INTR
#define MP_PLATFORM_MSTAR_LEGANCY_INTR 1
#else
#define MP_PLATFORM_MSTAR_LEGANCY_INTR 0
#endif

#ifdef CONFIG_MP_PLATFORM_MSTAR_LEGANCY_INTR_DEBUG
#define MP_PLATFORM_MSTAR_LEGANCY_INTR_DEBUG 1
#else
#define MP_PLATFORM_MSTAR_LEGANCY_INTR_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_SW_PATCH_L2_SRAM_RMA
#define MP_PLATFORM_SW_PATCH_L2_SRAM_RMA 1
#else
#define MP_PLATFORM_SW_PATCH_L2_SRAM_RMA 0
#endif

#ifdef CONFIG_MP_PLATFORM_SW_PATCH_L2_SRAM_RMA_DEBUG
#define MP_PLATFORM_SW_PATCH_L2_SRAM_RMA_DEBUG 1
#else
#define MP_PLATFORM_SW_PATCH_L2_SRAM_RMA_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_MIPS74K_TIMER
#define MP_PLATFORM_MIPS74K_TIMER 1
#else
#define MP_PLATFORM_MIPS74K_TIMER 0
#endif

#ifdef CONFIG_MP_PLATFORM_MIPS74K_TIMER_DEBUG
#define MP_PLATFORM_MIPS74K_TIMER_DEBUG 1
#else
#define MP_PLATFORM_MIPS74K_TIMER_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_ARM_MSTAR_ETM
#define MP_PLATFORM_ARM_MSTAR_ETM 1
#else
#define MP_PLATFORM_ARM_MSTAR_ETM 0
#endif

#ifdef CONFIG_MP_PLATFORM_ARM_MSTAR_ETM_DEBUG
#define MP_PLATFORM_ARM_MSTAR_ETM_DEBUG 1
#else
#define MP_PLATFORM_ARM_MSTAR_ETM_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_INT_1_to_1_SPI
#define MP_PLATFORM_INT_1_to_1_SPI 1
#else
#define MP_PLATFORM_INT_1_to_1_SPI 0
#endif

#ifdef CONFIG_MP_PLATFORM_INT_1_to_1_SPI_DEBUG
#define MP_PLATFORM_INT_1_to_1_SPI_DEBUG 1
#else
#define MP_PLATFORM_INT_1_to_1_SPI_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_ARM_PMU
#define MP_PLATFORM_ARM_PMU 1
#else
#define MP_PLATFORM_ARM_PMU 0
#endif

#ifdef CONFIG_MP_PLATFORM_ARM_PMU_DEBUG
#define MP_PLATFORM_ARM_PMU_DEBUG 1
#else
#define MP_PLATFORM_ARM_PMU_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_LZMA_BIN_COMPRESSED
#define MP_PLATFORM_LZMA_BIN_COMPRESSED 1
#else
#define MP_PLATFORM_LZMA_BIN_COMPRESSED 0
#endif

#ifdef CONFIG_MP_PLATFORM_LZMA_BIN_COMPRESSED_DEBUG
#define MP_PLATFORM_LZMA_BIN_COMPRESSED_DEBUG 1
#else
#define MP_PLATFORM_LZMA_BIN_COMPRESSED_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_CPU_SETTING
#define MP_PLATFORM_CPU_SETTING 1
#else
#define MP_PLATFORM_CPU_SETTING 0
#endif

#ifdef CONFIG_MP_PLATFORM_CPU_SETTING_DEBUG
#define MP_PLATFORM_CPU_SETTING_DEBUG 1
#else
#define MP_PLATFORM_CPU_SETTING_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_T_SENSOR_OBSERVATION
#define MP_PLATFORM_T_SENSOR_OBSERVATION 1
#else
#define MP_PLATFORM_T_SENSOR_OBSERVATION 0
#endif

#ifdef CONFIG_MP_PLATFORM_T_SENSOR_OBSERVATION_DEBUG
#define MP_PLATFORM_T_SENSOR_OBSERVATION_DEBUG 1
#else
#define MP_PLATFORM_T_SENSOR_OBSERVATION_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_FIXME
#define MP_PLATFORM_FIXME 1
#else
#define MP_PLATFORM_FIXME 0
#endif

#ifdef CONFIG_MP_PLATFORM_FIXME_DEBUG
#define MP_PLATFORM_FIXME_DEBUG 1
#else
#define MP_PLATFORM_FIXME_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_FIQ_IRQ_HYP
#define MP_PLATFORM_FIQ_IRQ_HYP 1
#else
#define MP_PLATFORM_FIQ_IRQ_HYP 0
#endif

#ifdef CONFIG_MP_PLATFORM_FIQ_IRQ_HYP_DEBUG
#define MP_PLATFORM_FIQ_IRQ_HYP_DEBUG 1
#else
#define MP_PLATFORM_FIQ_IRQ_HYP_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_UTOPIA2_INTERRUPT
#define MP_PLATFORM_UTOPIA2_INTERRUPT 1
#else
#define MP_PLATFORM_UTOPIA2_INTERRUPT 0
#endif

#ifdef CONFIG_MP_PLATFORM_UTOPIA2_INTERRUPT_DEBUG
#define MP_PLATFORM_UTOPIA2_INTERRUPT_DEBUG 1
#else
#define MP_PLATFORM_UTOPIA2_INTERRUPT_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_UTOPIA2K_EXPORT_SYMBOL
#define MP_PLATFORM_UTOPIA2K_EXPORT_SYMBOL 1
#else
#define MP_PLATFORM_UTOPIA2K_EXPORT_SYMBOL 0
#endif

#ifdef CONFIG_MP_PLATFORM_UTOPIA2K_EXPORT_SYMBOL_DEBUG
#define MP_PLATFORM_UTOPIA2K_EXPORT_SYMBOL_DEBUG 1
#else
#define MP_PLATFORM_UTOPIA2K_EXPORT_SYMBOL_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_ARM_MEMORY_HOTPLUG
#define MP_PLATFORM_ARM_MEMORY_HOTPLUG 1
#else
#define MP_PLATFORM_ARM_MEMORY_HOTPLUG 0
#endif

#ifdef CONFIG_MP_PLATFORM_ARM_MEMORY_HOTPLUG_DEBUG
#define MP_PLATFORM_ARM_MEMORY_HOTPLUG_DEBUG 1
#else
#define MP_PLATFORM_ARM_MEMORY_HOTPLUG_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_ARM64_DTB_IRQNUM_CHECK_OFF
#define MP_PLATFORM_ARM64_DTB_IRQNUM_CHECK_OFF 1
#else
#define MP_PLATFORM_ARM64_DTB_IRQNUM_CHECK_OFF 0
#endif

#ifdef CONFIG_MP_PLATFORM_ARM64_DTB_IRQNUM_CHECK_OFF_DEBUG
#define MP_PLATFORM_ARM64_DTB_IRQNUM_CHECK_OFF_DEBUG 1
#else
#define MP_PLATFORM_ARM64_DTB_IRQNUM_CHECK_OFF_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_FRC_MAPPING
#define MP_PLATFORM_FRC_MAPPING 1
#else
#define MP_PLATFORM_FRC_MAPPING 0
#endif

#ifdef CONFIG_MP_PLATFORM_FRC_MAPPING_DEBUG
#define MP_PLATFORM_FRC_MAPPING_DEBUG 1
#else
#define MP_PLATFORM_FRC_MAPPING_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_GIC_SET_MULTIPLE_CPUS
#define MP_PLATFORM_GIC_SET_MULTIPLE_CPUS 1
#else
#define MP_PLATFORM_GIC_SET_MULTIPLE_CPUS 0
#endif

#ifdef CONFIG_MP_PLATFORM_GIC_SET_MULTIPLE_CPUS_DEBUG
#define MP_PLATFORM_GIC_SET_MULTIPLE_CPUS_DEBUG 1
#else
#define MP_PLATFORM_GIC_SET_MULTIPLE_CPUS_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_DVFS_GET_ERR_STATE_FROM_CPUHOTPLG_DISABLE
#define MP_PLATFORM_DVFS_GET_ERR_STATE_FROM_CPUHOTPLG_DISABLE 1
#else
#define MP_PLATFORM_DVFS_GET_ERR_STATE_FROM_CPUHOTPLG_DISABLE 0
#endif

#ifdef CONFIG_MP_PLATFORM_DVFS_GET_ERR_STATE_FROM_CPUHOTPLG_DISABLE_DEBUG
#define MP_PLATFORM_DVFS_GET_ERR_STATE_FROM_CPUHOTPLG_DISABLE_DEBUG 1
#else
#define MP_PLATFORM_DVFS_GET_ERR_STATE_FROM_CPUHOTPLG_DISABLE_DEBUG 0
#endif


#ifdef CONFIG_MP_PLATFORM_PIPE_FLUSH_DOUBLE_CHECK
#define MP_PLATFORM_PIPE_FLUSH_DOUBLE_CHECK 1
#else
#define MP_PLATFORM_PIPE_FLUSH_DOUBLE_CHECK 0
#endif

#ifdef CONFIG_MP_PLATFORM_PIPE_FLUSH_DOUBLE_CHECK_DEBUG
#define MP_PLATFORM_PIPE_FLUSH_DOUBLE_CHECK_DEBUG 1
#else
#define MP_PLATFORM_PIPE_FLUSH_DOUBLE_CHECK_DEBUG 0
#endif


//=========================== Module:NAND=======================================
#ifdef CONFIG_MP_NAND_UBI
#define MP_NAND_UBI 1
#else
#define MP_NAND_UBI 0
#endif

#ifdef CONFIG_MP_NAND_UBI_DEBUG
#define MP_NAND_UBI_DEBUG 1
#else
#define MP_NAND_UBI_DEBUG 0
#endif


#ifdef CONFIG_MP_NAND_MTD
#define MP_NAND_MTD 1
#else
#define MP_NAND_MTD 0
#endif

#ifdef CONFIG_MP_NAND_MTD_DEBUG
#define MP_NAND_MTD_DEBUG 1
#else
#define MP_NAND_MTD_DEBUG 0
#endif


#ifdef CONFIG_MP_NAND_UBIFS
#define MP_NAND_UBIFS 1
#else
#define MP_NAND_UBIFS 0
#endif

#ifdef CONFIG_MP_NAND_UBIFS_DEBUG
#define MP_NAND_UBIFS_DEBUG 1
#else
#define MP_NAND_UBIFS_DEBUG 0
#endif


#ifdef CONFIG_MP_NAND_Spansion
#define MP_NAND_Spansion 1
#else
#define MP_NAND_Spansion 0
#endif

#ifdef CONFIG_MP_NAND_Spansion_DEBUG
#define MP_NAND_Spansion_DEBUG 1
#else
#define MP_NAND_Spansion_DEBUG 0
#endif


#ifdef CONFIG_MP_NAND_BBT
#define MP_NAND_BBT 1
#else
#define MP_NAND_BBT 0
#endif

#ifdef CONFIG_MP_NAND_BBT_DEBUG
#define MP_NAND_BBT_DEBUG 1
#else
#define MP_NAND_BBT_DEBUG 0
#endif


#ifdef CONFIG_MP_NAND_BBT_SIZE
#define MP_NAND_BBT_SIZE 1
#else
#define MP_NAND_BBT_SIZE 0
#endif

#ifdef CONFIG_MP_NAND_BBT_SIZE_DEBUG
#define MP_NAND_BBT_SIZE_DEBUG 1
#else
#define MP_NAND_BBT_SIZE_DEBUG 0
#endif


//=========================== Module:USB=======================================
#ifdef CONFIG_MP_USB_MSTAR
#define MP_USB_MSTAR 1
#else
#define MP_USB_MSTAR 0
#endif

#ifdef CONFIG_MP_USB_MSTAR_DEBUG
#define MP_USB_MSTAR_DEBUG 1
#else
#define MP_USB_MSTAR_DEBUG 0
#endif


//=========================== Module:USB=======================================
#ifdef CONFIG_MP_USB_STR_PATCH
#define MP_USB_STR_PATCH 1
#else
#define MP_USB_STR_PATCH 0
#endif

#ifdef CONFIG_MP_USB_STR_PATCH_DEBUG
#define MP_USB_STR_PATCH_DEBUG 1
#else
#define MP_USB_STR_PATCH_DEBUG 0
#endif


//=========================== Module:EMMC=======================================
#ifdef CONFIG_MP_EMMC_TRIM
#define MP_EMMC_TRIM 1
#else
#define MP_EMMC_TRIM 0
#endif

#ifdef CONFIG_MP_EMMC_TRIM_DEBUG
#define MP_EMMC_TRIM_DEBUG 1
#else
#define MP_EMMC_TRIM_DEBUG 0
#endif


//=========================== Module:CHECKPT=======================================
#ifdef CONFIG_MP_CHECKPT_BOOT
#define MP_CHECKPT_BOOT 1
#else
#define MP_CHECKPT_BOOT 0
#endif

#ifdef CONFIG_MP_CHECKPT_BOOT_DEBUG
#define MP_CHECKPT_BOOT_DEBUG 1
#else
#define MP_CHECKPT_BOOT_DEBUG 0
#endif


//=========================== Module:COMPILER=======================================
#ifdef CONFIG_MP_COMPILER_ERROR
#define MP_COMPILER_ERROR 1
#else
#define MP_COMPILER_ERROR 0
#endif

#ifdef CONFIG_MP_COMPILER_ERROR_DEBUG
#define MP_COMPILER_ERROR_DEBUG 1
#else
#define MP_COMPILER_ERROR_DEBUG 0
#endif


//=========================== Module:Android=======================================
#ifdef CONFIG_MP_Android_DUMMY_MSTAR_RTC
#define MP_Android_DUMMY_MSTAR_RTC 1
#else
#define MP_Android_DUMMY_MSTAR_RTC 0
#endif

#ifdef CONFIG_MP_Android_DUMMY_MSTAR_RTC_DEBUG
#define MP_Android_DUMMY_MSTAR_RTC_DEBUG 1
#else
#define MP_Android_DUMMY_MSTAR_RTC_DEBUG 0
#endif


#ifdef CONFIG_MP_Android_MSTAR_HARDCODE_LPJ
#define MP_Android_MSTAR_HARDCODE_LPJ 1
#else
#define MP_Android_MSTAR_HARDCODE_LPJ 0
#endif

#ifdef CONFIG_MP_Android_MSTAR_HARDCODE_LPJ_DEBUG
#define MP_Android_MSTAR_HARDCODE_LPJ_DEBUG 1
#else
#define MP_Android_MSTAR_HARDCODE_LPJ_DEBUG 0
#endif


#ifdef CONFIG_MP_Android_MSTAR_RC_MAP_DEFINE
#define MP_Android_MSTAR_RC_MAP_DEFINE 1
#else
#define MP_Android_MSTAR_RC_MAP_DEFINE 0
#endif

#ifdef CONFIG_MP_Android_MSTAR_RC_MAP_DEFINE_DEBUG
#define MP_Android_MSTAR_RC_MAP_DEFINE_DEBUG 1
#else
#define MP_Android_MSTAR_RC_MAP_DEFINE_DEBUG 0
#endif


#ifdef CONFIG_MP_Android_MSTAR_ADJUST_LOW_MEM_KILLER_POLICY
#define MP_Android_MSTAR_ADJUST_LOW_MEM_KILLER_POLICY 1
#else
#define MP_Android_MSTAR_ADJUST_LOW_MEM_KILLER_POLICY 0
#endif

#ifdef CONFIG_MP_Android_MSTAR_ADJUST_LOW_MEM_KILLER_POLICY_DEBUG
#define MP_Android_MSTAR_ADJUST_LOW_MEM_KILLER_POLICY_DEBUG 1
#else
#define MP_Android_MSTAR_ADJUST_LOW_MEM_KILLER_POLICY_DEBUG 0
#endif


#ifdef CONFIG_MP_Android_MSTAR_CHANGE_IRQ_FILE_PERMISSION
#define MP_Android_MSTAR_CHANGE_IRQ_FILE_PERMISSION 1
#else
#define MP_Android_MSTAR_CHANGE_IRQ_FILE_PERMISSION 0
#endif

#ifdef CONFIG_MP_Android_MSTAR_CHANGE_IRQ_FILE_PERMISSION_DEBUG
#define MP_Android_MSTAR_CHANGE_IRQ_FILE_PERMISSION_DEBUG 1
#else
#define MP_Android_MSTAR_CHANGE_IRQ_FILE_PERMISSION_DEBUG 0
#endif


//=========================== Module:DEBUG_TOOL=======================================
#ifdef CONFIG_MP_DEBUG_TOOL_COREDUMP
#define MP_DEBUG_TOOL_COREDUMP 1
#else
#define MP_DEBUG_TOOL_COREDUMP 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_COREDUMP_DEBUG
#define MP_DEBUG_TOOL_COREDUMP_DEBUG 1
#else
#define MP_DEBUG_TOOL_COREDUMP_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_KDEBUG
#define MP_DEBUG_TOOL_KDEBUG 1
#else
#define MP_DEBUG_TOOL_KDEBUG 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_KDEBUG_DEBUG
#define MP_DEBUG_TOOL_KDEBUG_DEBUG 1
#else
#define MP_DEBUG_TOOL_KDEBUG_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_COREDUMP_PATH_BOOTARGS_ONLY
#define MP_DEBUG_TOOL_COREDUMP_PATH_BOOTARGS_ONLY 1
#else
#define MP_DEBUG_TOOL_COREDUMP_PATH_BOOTARGS_ONLY 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_COREDUMP_PATH_BOOTARGS_ONLY_DEBUG
#define MP_DEBUG_TOOL_COREDUMP_PATH_BOOTARGS_ONLY_DEBUG 1
#else
#define MP_DEBUG_TOOL_COREDUMP_PATH_BOOTARGS_ONLY_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_COREDUMP_USB_DEFAULT
#define MP_DEBUG_TOOL_COREDUMP_USB_DEFAULT 1
#else
#define MP_DEBUG_TOOL_COREDUMP_USB_DEFAULT 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_COREDUMP_USB_DEFAULT_DEBUG
#define MP_DEBUG_TOOL_COREDUMP_USB_DEFAULT_DEBUG 1
#else
#define MP_DEBUG_TOOL_COREDUMP_USB_DEFAULT_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_COREDUMP_PATH_BACKUP
#define MP_DEBUG_TOOL_COREDUMP_PATH_BACKUP 1
#else
#define MP_DEBUG_TOOL_COREDUMP_PATH_BACKUP 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_COREDUMP_PATH_BACKUP_DEBUG
#define MP_DEBUG_TOOL_COREDUMP_PATH_BACKUP_DEBUG 1
#else
#define MP_DEBUG_TOOL_COREDUMP_PATH_BACKUP_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_OPROFILE
#define MP_DEBUG_TOOL_OPROFILE 1
#else
#define MP_DEBUG_TOOL_OPROFILE 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_OPROFILE_DEBUG
#define MP_DEBUG_TOOL_OPROFILE_DEBUG 1
#else
#define MP_DEBUG_TOOL_OPROFILE_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_PMU_TIMER_MODE
#define MP_DEBUG_TOOL_PMU_TIMER_MODE 1
#else
#define MP_DEBUG_TOOL_PMU_TIMER_MODE 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_PMU_TIMER_MODE_DEBUG
#define MP_DEBUG_TOOL_PMU_TIMER_MODE_DEBUG 1
#else
#define MP_DEBUG_TOOL_PMU_TIMER_MODE_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_VM_USED_SIZE_CHECK
#define MP_DEBUG_TOOL_VM_USED_SIZE_CHECK 1
#else
#define MP_DEBUG_TOOL_VM_USED_SIZE_CHECK 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_VM_USED_SIZE_CHECK_DEBUG
#define MP_DEBUG_TOOL_VM_USED_SIZE_CHECK_DEBUG 1
#else
#define MP_DEBUG_TOOL_VM_USED_SIZE_CHECK_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_COREDUMP_BUILD_IN_USB
#define MP_DEBUG_TOOL_COREDUMP_BUILD_IN_USB 1
#else
#define MP_DEBUG_TOOL_COREDUMP_BUILD_IN_USB 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_COREDUMP_BUILD_IN_USB_DEBUG
#define MP_DEBUG_TOOL_COREDUMP_BUILD_IN_USB_DEBUG 1
#else
#define MP_DEBUG_TOOL_COREDUMP_BUILD_IN_USB_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_COREDUMP_WITHOUT_COMPRESS
#define MP_DEBUG_TOOL_COREDUMP_WITHOUT_COMPRESS 1
#else
#define MP_DEBUG_TOOL_COREDUMP_WITHOUT_COMPRESS 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_COREDUMP_WITHOUT_COMPRESS_DEBUG
#define MP_DEBUG_TOOL_COREDUMP_WITHOUT_COMPRESS_DEBUG 1
#else
#define MP_DEBUG_TOOL_COREDUMP_WITHOUT_COMPRESS_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_CHANGELIST
#define MP_DEBUG_TOOL_CHANGELIST 1
#else
#define MP_DEBUG_TOOL_CHANGELIST 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_CHANGELIST_DEBUG
#define MP_DEBUG_TOOL_CHANGELIST_DEBUG 1
#else
#define MP_DEBUG_TOOL_CHANGELIST_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_MEMORY_USAGE_MONITOR
#define MP_DEBUG_TOOL_MEMORY_USAGE_MONITOR 1
#else
#define MP_DEBUG_TOOL_MEMORY_USAGE_MONITOR 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_MEMORY_USAGE_MONITOR_DEBUG
#define MP_DEBUG_TOOL_MEMORY_USAGE_MONITOR_DEBUG 1
#else
#define MP_DEBUG_TOOL_MEMORY_USAGE_MONITOR_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_RAMLOG
#define MP_DEBUG_TOOL_RAMLOG 1
#else
#define MP_DEBUG_TOOL_RAMLOG 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_RAMLOG_DEBUG
#define MP_DEBUG_TOOL_RAMLOG_DEBUG 1
#else
#define MP_DEBUG_TOOL_RAMLOG_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_MEMORY_USAGE_TRACE
#define MP_DEBUG_TOOL_MEMORY_USAGE_TRACE 1
#else
#define MP_DEBUG_TOOL_MEMORY_USAGE_TRACE 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_MEMORY_USAGE_TRACE_DEBUG
#define MP_DEBUG_TOOL_MEMORY_USAGE_TRACE_DEBUG 1
#else
#define MP_DEBUG_TOOL_MEMORY_USAGE_TRACE_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_THREAD_CREATE_MONITOR
#define MP_DEBUG_TOOL_THREAD_CREATE_MONITOR 1
#else
#define MP_DEBUG_TOOL_THREAD_CREATE_MONITOR 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_THREAD_CREATE_MONITOR_DEBUG
#define MP_DEBUG_TOOL_THREAD_CREATE_MONITOR_DEBUG 1
#else
#define MP_DEBUG_TOOL_THREAD_CREATE_MONITOR_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_COREDUMP_KEEP_KICKING_WDT
#define MP_DEBUG_TOOL_COREDUMP_KEEP_KICKING_WDT 1
#else
#define MP_DEBUG_TOOL_COREDUMP_KEEP_KICKING_WDT 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_COREDUMP_KEEP_KICKING_WDT_DEBUG
#define MP_DEBUG_TOOL_COREDUMP_KEEP_KICKING_WDT_DEBUG 1
#else
#define MP_DEBUG_TOOL_COREDUMP_KEEP_KICKING_WDT_DEBUG 0
#endif


#ifdef CONFIG_MP_DEBUG_TOOL_DUMP_STACK_EACH_CPU
#define MP_DEBUG_TOOL_DUMP_STACK_EACH_CPU 1
#else
#define MP_DEBUG_TOOL_DUMP_STACK_EACH_CPU 0
#endif

#ifdef CONFIG_MP_DEBUG_TOOL_DUMP_STACK_EACH_CPU_DEBUG
#define MP_DEBUG_TOOL_DUMP_STACK_EACH_CPU_DEBUG 1
#else
#define MP_DEBUG_TOOL_DUMP_STACK_EACH_CPU_DEBUG 0
#endif


//=========================== Module:MIPS_L2=======================================
#ifdef CONFIG_MP_MIPS_L2_CACHE
#define MP_MIPS_L2_CACHE 1
#else
#define MP_MIPS_L2_CACHE 0
#endif

#ifdef CONFIG_MP_MIPS_L2_CACHE_DEBUG
#define MP_MIPS_L2_CACHE_DEBUG 1
#else
#define MP_MIPS_L2_CACHE_DEBUG 0
#endif


//=========================== Module:SMP=======================================
#ifdef CONFIG_MP_SMP_STARTUP
#define MP_SMP_STARTUP 1
#else
#define MP_SMP_STARTUP 0
#endif

#ifdef CONFIG_MP_SMP_STARTUP_DEBUG
#define MP_SMP_STARTUP_DEBUG 1
#else
#define MP_SMP_STARTUP_DEBUG 0
#endif


//=========================== Module:UART=======================================
#ifdef CONFIG_MP_UART_SERIAL_8250_RIU_BASE
#define MP_UART_SERIAL_8250_RIU_BASE 1
#else
#define MP_UART_SERIAL_8250_RIU_BASE 0
#endif

#ifdef CONFIG_MP_UART_SERIAL_8250_RIU_BASE_DEBUG
#define MP_UART_SERIAL_8250_RIU_BASE_DEBUG 1
#else
#define MP_UART_SERIAL_8250_RIU_BASE_DEBUG 0
#endif


//=========================== Module:NTFS3G=======================================
#ifdef CONFIG_MP_NTFS3G_WRAP
#define MP_NTFS3G_WRAP 1
#else
#define MP_NTFS3G_WRAP 0
#endif

#ifdef CONFIG_MP_NTFS3G_WRAP_DEBUG
#define MP_NTFS3G_WRAP_DEBUG 1
#else
#define MP_NTFS3G_WRAP_DEBUG 0
#endif


//=========================== Module:MSTAR_STR=======================================
#ifdef CONFIG_MP_MSTAR_STR_BASE
#define MP_MSTAR_STR_BASE 1
#else
#define MP_MSTAR_STR_BASE 0
#endif

#ifdef CONFIG_MP_MSTAR_STR_BASE_DEBUG
#define MP_MSTAR_STR_BASE_DEBUG 1
#else
#define MP_MSTAR_STR_BASE_DEBUG 0
#endif


//=========================== Module:CA7=======================================
#ifdef CONFIG_MP_CA7_QUAD_CORE_PATCH
#define MP_CA7_QUAD_CORE_PATCH 1
#else
#define MP_CA7_QUAD_CORE_PATCH 0
#endif

#ifdef CONFIG_MP_CA7_QUAD_CORE_PATCH_DEBUG
#define MP_CA7_QUAD_CORE_PATCH_DEBUG 1
#else
#define MP_CA7_QUAD_CORE_PATCH_DEBUG 0
#endif


//=========================== Module:security=======================================
#ifdef CONFIG_MP_security_dm_verity
#define MP_security_dm_verity 1
#else
#define MP_security_dm_verity 0
#endif

#ifdef CONFIG_MP_security_dm_verity_DEBUG
#define MP_security_dm_verity_DEBUG 1
#else
#define MP_security_dm_verity_DEBUG 0
#endif


//=========================== Module:SYNC_3_1_10_SETTING=======================================
#ifdef CONFIG_MP_SYNC_3_1_10_SETTING_VMALLOC_SETTING
#define MP_SYNC_3_1_10_SETTING_VMALLOC_SETTING 1
#else
#define MP_SYNC_3_1_10_SETTING_VMALLOC_SETTING 0
#endif

#ifdef CONFIG_MP_SYNC_3_1_10_SETTING_VMALLOC_SETTING_DEBUG
#define MP_SYNC_3_1_10_SETTING_VMALLOC_SETTING_DEBUG 1
#else
#define MP_SYNC_3_1_10_SETTING_VMALLOC_SETTING_DEBUG 0
#endif


//=========================== Module:CMA_PATCH=======================================
#ifdef CONFIG_MP_CMA_PATCH_LX_MEMORY_ALIGN_TO_8K_CHECK
#define MP_CMA_PATCH_LX_MEMORY_ALIGN_TO_8K_CHECK 1
#else
#define MP_CMA_PATCH_LX_MEMORY_ALIGN_TO_8K_CHECK 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_LX_MEMORY_ALIGN_TO_8K_CHECK_DEBUG
#define MP_CMA_PATCH_LX_MEMORY_ALIGN_TO_8K_CHECK_DEBUG 1
#else
#define MP_CMA_PATCH_LX_MEMORY_ALIGN_TO_8K_CHECK_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_CMA_MSTAR_DRIVER_BUFFER
#define MP_CMA_PATCH_CMA_MSTAR_DRIVER_BUFFER 1
#else
#define MP_CMA_PATCH_CMA_MSTAR_DRIVER_BUFFER 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_CMA_MSTAR_DRIVER_BUFFER_DEBUG
#define MP_CMA_PATCH_CMA_MSTAR_DRIVER_BUFFER_DEBUG 1
#else
#define MP_CMA_PATCH_CMA_MSTAR_DRIVER_BUFFER_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_CMA_AGGRESSIVE_ALLOC
#define MP_CMA_PATCH_CMA_AGGRESSIVE_ALLOC 1
#else
#define MP_CMA_PATCH_CMA_AGGRESSIVE_ALLOC 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_CMA_AGGRESSIVE_ALLOC_DEBUG
#define MP_CMA_PATCH_CMA_AGGRESSIVE_ALLOC_DEBUG 1
#else
#define MP_CMA_PATCH_CMA_AGGRESSIVE_ALLOC_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_CMA_MORE_AGGRESSIVE_ALLOC
#define MP_CMA_PATCH_CMA_MORE_AGGRESSIVE_ALLOC 1
#else
#define MP_CMA_PATCH_CMA_MORE_AGGRESSIVE_ALLOC 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_CMA_MORE_AGGRESSIVE_ALLOC_DEBUG
#define MP_CMA_PATCH_CMA_MORE_AGGRESSIVE_ALLOC_DEBUG 1
#else
#define MP_CMA_PATCH_CMA_MORE_AGGRESSIVE_ALLOC_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_CMA_DYNAMIC_STRATEGY
#define MP_CMA_PATCH_CMA_DYNAMIC_STRATEGY 1
#else
#define MP_CMA_PATCH_CMA_DYNAMIC_STRATEGY 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_CMA_DYNAMIC_STRATEGY_DEBUG
#define MP_CMA_PATCH_CMA_DYNAMIC_STRATEGY_DEBUG 1
#else
#define MP_CMA_PATCH_CMA_DYNAMIC_STRATEGY_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_CMA_64_BIT_TEMP_MODIFICATION
#define MP_CMA_PATCH_CMA_64_BIT_TEMP_MODIFICATION 1
#else
#define MP_CMA_PATCH_CMA_64_BIT_TEMP_MODIFICATION 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_CMA_64_BIT_TEMP_MODIFICATION_DEBUG
#define MP_CMA_PATCH_CMA_64_BIT_TEMP_MODIFICATION_DEBUG 1
#else
#define MP_CMA_PATCH_CMA_64_BIT_TEMP_MODIFICATION_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_CMA_DEFAULT_BUFFER_LIMITTED_TO_LX0
#define MP_CMA_PATCH_CMA_DEFAULT_BUFFER_LIMITTED_TO_LX0 1
#else
#define MP_CMA_PATCH_CMA_DEFAULT_BUFFER_LIMITTED_TO_LX0 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_CMA_DEFAULT_BUFFER_LIMITTED_TO_LX0_DEBUG
#define MP_CMA_PATCH_CMA_DEFAULT_BUFFER_LIMITTED_TO_LX0_DEBUG 1
#else
#define MP_CMA_PATCH_CMA_DEFAULT_BUFFER_LIMITTED_TO_LX0_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_FORCE_MIGRATION
#define MP_CMA_PATCH_FORCE_MIGRATION 1
#else
#define MP_CMA_PATCH_FORCE_MIGRATION 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_FORCE_MIGRATION_DEBUG
#define MP_CMA_PATCH_FORCE_MIGRATION_DEBUG 1
#else
#define MP_CMA_PATCH_FORCE_MIGRATION_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_FORCE_ALLOC_START_ADDR
#define MP_CMA_PATCH_FORCE_ALLOC_START_ADDR 1
#else
#define MP_CMA_PATCH_FORCE_ALLOC_START_ADDR 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_FORCE_ALLOC_START_ADDR_DEBUG
#define MP_CMA_PATCH_FORCE_ALLOC_START_ADDR_DEBUG 1
#else
#define MP_CMA_PATCH_FORCE_ALLOC_START_ADDR_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_COMPACTION_FROM_NONCMA_TO_CMA
#define MP_CMA_PATCH_COMPACTION_FROM_NONCMA_TO_CMA 1
#else
#define MP_CMA_PATCH_COMPACTION_FROM_NONCMA_TO_CMA 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_COMPACTION_FROM_NONCMA_TO_CMA_DEBUG
#define MP_CMA_PATCH_COMPACTION_FROM_NONCMA_TO_CMA_DEBUG 1
#else
#define MP_CMA_PATCH_COMPACTION_FROM_NONCMA_TO_CMA_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_DELAY_FREE
#define MP_CMA_PATCH_DELAY_FREE 1
#else
#define MP_CMA_PATCH_DELAY_FREE 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_DELAY_FREE_DEBUG
#define MP_CMA_PATCH_DELAY_FREE_DEBUG 1
#else
#define MP_CMA_PATCH_DELAY_FREE_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_MIGRATION_FILTER
#define MP_CMA_PATCH_MIGRATION_FILTER 1
#else
#define MP_CMA_PATCH_MIGRATION_FILTER 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_MIGRATION_FILTER_DEBUG
#define MP_CMA_PATCH_MIGRATION_FILTER_DEBUG 1
#else
#define MP_CMA_PATCH_MIGRATION_FILTER_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_FORBIDDEN_MOVABLE_FALLBACK_TO_CMA
#define MP_CMA_PATCH_FORBIDDEN_MOVABLE_FALLBACK_TO_CMA 1
#else
#define MP_CMA_PATCH_FORBIDDEN_MOVABLE_FALLBACK_TO_CMA 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_FORBIDDEN_MOVABLE_FALLBACK_TO_CMA_DEBUG
#define MP_CMA_PATCH_FORBIDDEN_MOVABLE_FALLBACK_TO_CMA_DEBUG 1
#else
#define MP_CMA_PATCH_FORBIDDEN_MOVABLE_FALLBACK_TO_CMA_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_DEBUG_STATIC_MIU_PROTECT
#define MP_CMA_PATCH_DEBUG_STATIC_MIU_PROTECT 1
#else
#define MP_CMA_PATCH_DEBUG_STATIC_MIU_PROTECT 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_DEBUG_STATIC_MIU_PROTECT_DEBUG
#define MP_CMA_PATCH_DEBUG_STATIC_MIU_PROTECT_DEBUG 1
#else
#define MP_CMA_PATCH_DEBUG_STATIC_MIU_PROTECT_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_OOM_KILLER
#define MP_CMA_PATCH_OOM_KILLER 1
#else
#define MP_CMA_PATCH_OOM_KILLER 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_OOM_KILLER_DEBUG
#define MP_CMA_PATCH_OOM_KILLER_DEBUG 1
#else
#define MP_CMA_PATCH_OOM_KILLER_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_SMALLER_SOCKET_BUFFER
#define MP_CMA_PATCH_SMALLER_SOCKET_BUFFER 1
#else
#define MP_CMA_PATCH_SMALLER_SOCKET_BUFFER 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_SMALLER_SOCKET_BUFFER_DEBUG
#define MP_CMA_PATCH_SMALLER_SOCKET_BUFFER_DEBUG 1
#else
#define MP_CMA_PATCH_SMALLER_SOCKET_BUFFER_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_DO_FORK_PAGE_POOL
#define MP_CMA_PATCH_DO_FORK_PAGE_POOL 1
#else
#define MP_CMA_PATCH_DO_FORK_PAGE_POOL 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_DO_FORK_PAGE_POOL_DEBUG
#define MP_CMA_PATCH_DO_FORK_PAGE_POOL_DEBUG 1
#else
#define MP_CMA_PATCH_DO_FORK_PAGE_POOL_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_SMALLER_SLAB_PAGE
#define MP_CMA_PATCH_SMALLER_SLAB_PAGE 1
#else
#define MP_CMA_PATCH_SMALLER_SLAB_PAGE 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_SMALLER_SLAB_PAGE_DEBUG
#define MP_CMA_PATCH_SMALLER_SLAB_PAGE_DEBUG 1
#else
#define MP_CMA_PATCH_SMALLER_SLAB_PAGE_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_ION_LOW_ORDER_ALLOC
#define MP_CMA_PATCH_ION_LOW_ORDER_ALLOC 1
#else
#define MP_CMA_PATCH_ION_LOW_ORDER_ALLOC 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_ION_LOW_ORDER_ALLOC_DEBUG
#define MP_CMA_PATCH_ION_LOW_ORDER_ALLOC_DEBUG 1
#else
#define MP_CMA_PATCH_ION_LOW_ORDER_ALLOC_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_DISABLE_HIORDER
#define MP_CMA_PATCH_DISABLE_HIORDER 1
#else
#define MP_CMA_PATCH_DISABLE_HIORDER 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_DISABLE_HIORDER_DEBUG
#define MP_CMA_PATCH_DISABLE_HIORDER_DEBUG 1
#else
#define MP_CMA_PATCH_DISABLE_HIORDER_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_MSTAR_KMALLOC
#define MP_CMA_PATCH_MSTAR_KMALLOC 1
#else
#define MP_CMA_PATCH_MSTAR_KMALLOC 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_MSTAR_KMALLOC_DEBUG
#define MP_CMA_PATCH_MSTAR_KMALLOC_DEBUG 1
#else
#define MP_CMA_PATCH_MSTAR_KMALLOC_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_AGRESSIVE_KILL_PROCESS_TO_FREE_CMA_PAGE
#define MP_CMA_PATCH_AGRESSIVE_KILL_PROCESS_TO_FREE_CMA_PAGE 1
#else
#define MP_CMA_PATCH_AGRESSIVE_KILL_PROCESS_TO_FREE_CMA_PAGE 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_AGRESSIVE_KILL_PROCESS_TO_FREE_CMA_PAGE_DEBUG
#define MP_CMA_PATCH_AGRESSIVE_KILL_PROCESS_TO_FREE_CMA_PAGE_DEBUG 1
#else
#define MP_CMA_PATCH_AGRESSIVE_KILL_PROCESS_TO_FREE_CMA_PAGE_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_KSM_MIGRATION_FAILURE
#define MP_CMA_PATCH_KSM_MIGRATION_FAILURE 1
#else
#define MP_CMA_PATCH_KSM_MIGRATION_FAILURE 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_KSM_MIGRATION_FAILURE_DEBUG
#define MP_CMA_PATCH_KSM_MIGRATION_FAILURE_DEBUG 1
#else
#define MP_CMA_PATCH_KSM_MIGRATION_FAILURE_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_VM_UNMAP
#define MP_CMA_PATCH_VM_UNMAP 1
#else
#define MP_CMA_PATCH_VM_UNMAP 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_VM_UNMAP_DEBUG
#define MP_CMA_PATCH_VM_UNMAP_DEBUG 1
#else
#define MP_CMA_PATCH_VM_UNMAP_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_EVDEV_USING_CMA_BUFFER
#define MP_CMA_PATCH_EVDEV_USING_CMA_BUFFER 1
#else
#define MP_CMA_PATCH_EVDEV_USING_CMA_BUFFER 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_EVDEV_USING_CMA_BUFFER_DEBUG
#define MP_CMA_PATCH_EVDEV_USING_CMA_BUFFER_DEBUG 1
#else
#define MP_CMA_PATCH_EVDEV_USING_CMA_BUFFER_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_SPARSEMEM_MAPPING_256MB
#define MP_CMA_PATCH_SPARSEMEM_MAPPING_256MB 1
#else
#define MP_CMA_PATCH_SPARSEMEM_MAPPING_256MB 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_SPARSEMEM_MAPPING_256MB_DEBUG
#define MP_CMA_PATCH_SPARSEMEM_MAPPING_256MB_DEBUG 1
#else
#define MP_CMA_PATCH_SPARSEMEM_MAPPING_256MB_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_MBOOT_STR_USE_CMA
#define MP_CMA_PATCH_MBOOT_STR_USE_CMA 1
#else
#define MP_CMA_PATCH_MBOOT_STR_USE_CMA 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_MBOOT_STR_USE_CMA_DEBUG
#define MP_CMA_PATCH_MBOOT_STR_USE_CMA_DEBUG 1
#else
#define MP_CMA_PATCH_MBOOT_STR_USE_CMA_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_LOW_MEMEROY_SOLUTION
#define MP_CMA_PATCH_LOW_MEMEROY_SOLUTION 1
#else
#define MP_CMA_PATCH_LOW_MEMEROY_SOLUTION 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_LOW_MEMEROY_SOLUTION_DEBUG
#define MP_CMA_PATCH_LOW_MEMEROY_SOLUTION_DEBUG 1
#else
#define MP_CMA_PATCH_LOW_MEMEROY_SOLUTION_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_COUNT_TIMECOST
#define MP_CMA_PATCH_COUNT_TIMECOST 1
#else
#define MP_CMA_PATCH_COUNT_TIMECOST 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_COUNT_TIMECOST_DEBUG
#define MP_CMA_PATCH_COUNT_TIMECOST_DEBUG 1
#else
#define MP_CMA_PATCH_COUNT_TIMECOST_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_POOL_UTOPIA_TO_KERNEL
#define MP_CMA_PATCH_POOL_UTOPIA_TO_KERNEL 1
#else
#define MP_CMA_PATCH_POOL_UTOPIA_TO_KERNEL 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_POOL_UTOPIA_TO_KERNEL_DEBUG
#define MP_CMA_PATCH_POOL_UTOPIA_TO_KERNEL_DEBUG 1
#else
#define MP_CMA_PATCH_POOL_UTOPIA_TO_KERNEL_DEBUG 0
#endif


#ifdef CONFIG_MP_CMA_PATCH_PCI_ALLOC_FREE_WITH_CMA
#define MP_CMA_PATCH_PCI_ALLOC_FREE_WITH_CMA 1
#else
#define MP_CMA_PATCH_PCI_ALLOC_FREE_WITH_CMA 0
#endif

#ifdef CONFIG_MP_CMA_PATCH_PCI_ALLOC_FREE_WITH_CMA_DEBUG
#define MP_CMA_PATCH_PCI_ALLOC_FREE_WITH_CMA_DEBUG 1
#else
#define MP_CMA_PATCH_PCI_ALLOC_FREE_WITH_CMA_DEBUG 0
#endif


//=========================== Module:GLOBAL_TIMER=======================================
#ifdef CONFIG_MP_GLOBAL_TIMER_12MHZ_PATCH
#define MP_GLOBAL_TIMER_12MHZ_PATCH 1
#else
#define MP_GLOBAL_TIMER_12MHZ_PATCH 0
#endif

#ifdef CONFIG_MP_GLOBAL_TIMER_12MHZ_PATCH_DEBUG
#define MP_GLOBAL_TIMER_12MHZ_PATCH_DEBUG 1
#else
#define MP_GLOBAL_TIMER_12MHZ_PATCH_DEBUG 0
#endif


//=========================== Module:ION_PATCH=======================================
#ifdef CONFIG_MP_ION_PATCH_MSTAR
#define MP_ION_PATCH_MSTAR 1
#else
#define MP_ION_PATCH_MSTAR 0
#endif

#ifdef CONFIG_MP_ION_PATCH_MSTAR_DEBUG
#define MP_ION_PATCH_MSTAR_DEBUG 1
#else
#define MP_ION_PATCH_MSTAR_DEBUG 0
#endif


#ifdef CONFIG_MP_ION_PATCH_CACHE_FLUSH_MOD
#define MP_ION_PATCH_CACHE_FLUSH_MOD 1
#else
#define MP_ION_PATCH_CACHE_FLUSH_MOD 0
#endif

#ifdef CONFIG_MP_ION_PATCH_CACHE_FLUSH_MOD_DEBUG
#define MP_ION_PATCH_CACHE_FLUSH_MOD_DEBUG 1
#else
#define MP_ION_PATCH_CACHE_FLUSH_MOD_DEBUG 0
#endif


//=========================== Module:STATIC_TIMER=======================================
#ifdef CONFIG_MP_STATIC_TIMER_CLOCK_SOURCE
#define MP_STATIC_TIMER_CLOCK_SOURCE 1
#else
#define MP_STATIC_TIMER_CLOCK_SOURCE 0
#endif

#ifdef CONFIG_MP_STATIC_TIMER_CLOCK_SOURCE_DEBUG
#define MP_STATIC_TIMER_CLOCK_SOURCE_DEBUG 1
#else
#define MP_STATIC_TIMER_CLOCK_SOURCE_DEBUG 0
#endif


//=========================== Module:SPARSE_MEM=======================================
#ifdef CONFIG_MP_SPARSE_MEM_ENABLE_HOLES_IN_ZONE_CHECK
#define MP_SPARSE_MEM_ENABLE_HOLES_IN_ZONE_CHECK 1
#else
#define MP_SPARSE_MEM_ENABLE_HOLES_IN_ZONE_CHECK 0
#endif

#ifdef CONFIG_MP_SPARSE_MEM_ENABLE_HOLES_IN_ZONE_CHECK_DEBUG
#define MP_SPARSE_MEM_ENABLE_HOLES_IN_ZONE_CHECK_DEBUG 1
#else
#define MP_SPARSE_MEM_ENABLE_HOLES_IN_ZONE_CHECK_DEBUG 0
#endif


//=========================== Module:FAT=======================================
#ifdef CONFIG_MP_FAT_VOLUME_LABEL
#define MP_FAT_VOLUME_LABEL 1
#else
#define MP_FAT_VOLUME_LABEL 0
#endif

#ifdef CONFIG_MP_FAT_VOLUME_LABEL_DEBUG
#define MP_FAT_VOLUME_LABEL_DEBUG 1
#else
#define MP_FAT_VOLUME_LABEL_DEBUG 0
#endif


#ifdef CONFIG_MP_FAT_DEBUG_MESSAGE_CONTROL
#define MP_FAT_DEBUG_MESSAGE_CONTROL 1
#else
#define MP_FAT_DEBUG_MESSAGE_CONTROL 0
#endif

#ifdef CONFIG_MP_FAT_DEBUG_MESSAGE_CONTROL_DEBUG
#define MP_FAT_DEBUG_MESSAGE_CONTROL_DEBUG 1
#else
#define MP_FAT_DEBUG_MESSAGE_CONTROL_DEBUG 0
#endif


//=========================== Module:NTFS=======================================
#ifdef CONFIG_MP_NTFS_IOCTL
#define MP_NTFS_IOCTL 1
#else
#define MP_NTFS_IOCTL 0
#endif

#ifdef CONFIG_MP_NTFS_IOCTL_DEBUG
#define MP_NTFS_IOCTL_DEBUG 1
#else
#define MP_NTFS_IOCTL_DEBUG 0
#endif


#ifdef CONFIG_MP_NTFS_VOLUME_LABEL
#define MP_NTFS_VOLUME_LABEL 1
#else
#define MP_NTFS_VOLUME_LABEL 0
#endif

#ifdef CONFIG_MP_NTFS_VOLUME_LABEL_DEBUG
#define MP_NTFS_VOLUME_LABEL_DEBUG 1
#else
#define MP_NTFS_VOLUME_LABEL_DEBUG 0
#endif


#ifdef CONFIG_MP_NTFS_VOLUME_ID
#define MP_NTFS_VOLUME_ID 1
#else
#define MP_NTFS_VOLUME_ID 0
#endif

#ifdef CONFIG_MP_NTFS_VOLUME_ID_DEBUG
#define MP_NTFS_VOLUME_ID_DEBUG 1
#else
#define MP_NTFS_VOLUME_ID_DEBUG 0
#endif


#ifdef CONFIG_MP_NTFS_READ_PAGES
#define MP_NTFS_READ_PAGES 1
#else
#define MP_NTFS_READ_PAGES 0
#endif

#ifdef CONFIG_MP_NTFS_READ_PAGES_DEBUG
#define MP_NTFS_READ_PAGES_DEBUG 1
#else
#define MP_NTFS_READ_PAGES_DEBUG 0
#endif


#ifdef CONFIG_MP_NTFS_2TB_PLUS_PARTITION_SUPPORT
#define MP_NTFS_2TB_PLUS_PARTITION_SUPPORT 1
#else
#define MP_NTFS_2TB_PLUS_PARTITION_SUPPORT 0
#endif

#ifdef CONFIG_MP_NTFS_2TB_PLUS_PARTITION_SUPPORT_DEBUG
#define MP_NTFS_2TB_PLUS_PARTITION_SUPPORT_DEBUG 1
#else
#define MP_NTFS_2TB_PLUS_PARTITION_SUPPORT_DEBUG 0
#endif


#ifdef CONFIG_MP_NTFS_PAGE_CACHE_READAHEAD
#define MP_NTFS_PAGE_CACHE_READAHEAD 1
#else
#define MP_NTFS_PAGE_CACHE_READAHEAD 0
#endif

#ifdef CONFIG_MP_NTFS_PAGE_CACHE_READAHEAD_DEBUG
#define MP_NTFS_PAGE_CACHE_READAHEAD_DEBUG 1
#else
#define MP_NTFS_PAGE_CACHE_READAHEAD_DEBUG 0
#endif


//=========================== Module:SCSI=======================================
#ifdef CONFIG_MP_SCSI_MSTAR_SD_CARD_HOTPLUG
#define MP_SCSI_MSTAR_SD_CARD_HOTPLUG 1
#else
#define MP_SCSI_MSTAR_SD_CARD_HOTPLUG 0
#endif

#ifdef CONFIG_MP_SCSI_MSTAR_SD_CARD_HOTPLUG_DEBUG
#define MP_SCSI_MSTAR_SD_CARD_HOTPLUG_DEBUG 1
#else
#define MP_SCSI_MSTAR_SD_CARD_HOTPLUG_DEBUG 0
#endif


#ifdef CONFIG_MP_SCSI_MSTAR_SD_CARD_IMMEDIATELY_UNPLUG
#define MP_SCSI_MSTAR_SD_CARD_IMMEDIATELY_UNPLUG 1
#else
#define MP_SCSI_MSTAR_SD_CARD_IMMEDIATELY_UNPLUG 0
#endif

#ifdef CONFIG_MP_SCSI_MSTAR_SD_CARD_IMMEDIATELY_UNPLUG_DEBUG
#define MP_SCSI_MSTAR_SD_CARD_IMMEDIATELY_UNPLUG_DEBUG 1
#else
#define MP_SCSI_MSTAR_SD_CARD_IMMEDIATELY_UNPLUG_DEBUG 0
#endif


#ifdef CONFIG_MP_SCSI_HD_SUSPEND
#define MP_SCSI_HD_SUSPEND 1
#else
#define MP_SCSI_HD_SUSPEND 0
#endif

#ifdef CONFIG_MP_SCSI_HD_SUSPEND_DEBUG
#define MP_SCSI_HD_SUSPEND_DEBUG 1
#else
#define MP_SCSI_HD_SUSPEND_DEBUG 0
#endif


#ifdef CONFIG_MP_SCSI_MULTI_LUN
#define MP_SCSI_MULTI_LUN 1
#else
#define MP_SCSI_MULTI_LUN 0
#endif

#ifdef CONFIG_MP_SCSI_MULTI_LUN_DEBUG
#define MP_SCSI_MULTI_LUN_DEBUG 1
#else
#define MP_SCSI_MULTI_LUN_DEBUG 0
#endif


//=========================== Module:ETHERNET=======================================
#ifdef CONFIG_MP_ETHERNET_MSTAR_ICMP_ENHANCE
#define MP_ETHERNET_MSTAR_ICMP_ENHANCE 1
#else
#define MP_ETHERNET_MSTAR_ICMP_ENHANCE 0
#endif

#ifdef CONFIG_MP_ETHERNET_MSTAR_ICMP_ENHANCE_DEBUG
#define MP_ETHERNET_MSTAR_ICMP_ENHANCE_DEBUG 1
#else
#define MP_ETHERNET_MSTAR_ICMP_ENHANCE_DEBUG 0
#endif


//=========================== Module:WIFI=======================================
#ifdef CONFIG_MP_WIFI_INC_DEFAULT_DMA_COHERENT_POOL_SIZE
#define MP_WIFI_INC_DEFAULT_DMA_COHERENT_POOL_SIZE 1
#else
#define MP_WIFI_INC_DEFAULT_DMA_COHERENT_POOL_SIZE 0
#endif

#ifdef CONFIG_MP_WIFI_INC_DEFAULT_DMA_COHERENT_POOL_SIZE_DEBUG
#define MP_WIFI_INC_DEFAULT_DMA_COHERENT_POOL_SIZE_DEBUG 1
#else
#define MP_WIFI_INC_DEFAULT_DMA_COHERENT_POOL_SIZE_DEBUG 0
#endif


//=========================== Module:CIFS=======================================
#ifdef CONFIG_MP_CIFS_UNUSE_NTLMSSP_DEFAULT
#define MP_CIFS_UNUSE_NTLMSSP_DEFAULT 1
#else
#define MP_CIFS_UNUSE_NTLMSSP_DEFAULT 0
#endif

#ifdef CONFIG_MP_CIFS_UNUSE_NTLMSSP_DEFAULT_DEBUG
#define MP_CIFS_UNUSE_NTLMSSP_DEFAULT_DEBUG 1
#else
#define MP_CIFS_UNUSE_NTLMSSP_DEFAULT_DEBUG 0
#endif


//=========================== Module:SCHED=======================================
#ifdef CONFIG_MP_SCHED_POLICY_PATCH
#define MP_SCHED_POLICY_PATCH 1
#else
#define MP_SCHED_POLICY_PATCH 0
#endif

#ifdef CONFIG_MP_SCHED_POLICY_PATCH_DEBUG
#define MP_SCHED_POLICY_PATCH_DEBUG 1
#else
#define MP_SCHED_POLICY_PATCH_DEBUG 0
#endif


#ifdef CONFIG_MP_SCHED_POLICY_CHANGED_AVOIDED
#define MP_SCHED_POLICY_CHANGED_AVOIDED 1
#else
#define MP_SCHED_POLICY_CHANGED_AVOIDED 0
#endif

#ifdef CONFIG_MP_SCHED_POLICY_CHANGED_AVOIDED_DEBUG
#define MP_SCHED_POLICY_CHANGED_AVOIDED_DEBUG 1
#else
#define MP_SCHED_POLICY_CHANGED_AVOIDED_DEBUG 0
#endif


//=========================== Module:PURE_SN=======================================
#ifdef CONFIG_MP_PURE_SN_32BIT
#define MP_PURE_SN_32BIT 1
#else
#define MP_PURE_SN_32BIT 0
#endif

#ifdef CONFIG_MP_PURE_SN_32BIT_DEBUG
#define MP_PURE_SN_32BIT_DEBUG 1
#else
#define MP_PURE_SN_32BIT_DEBUG 0
#endif


//=========================== Module:NEW_UTOPIA=======================================
#ifdef CONFIG_MP_NEW_UTOPIA_32BIT
#define MP_NEW_UTOPIA_32BIT 1
#else
#define MP_NEW_UTOPIA_32BIT 0
#endif

#ifdef CONFIG_MP_NEW_UTOPIA_32BIT_DEBUG
#define MP_NEW_UTOPIA_32BIT_DEBUG 1
#else
#define MP_NEW_UTOPIA_32BIT_DEBUG 0
#endif


//=========================== Module:DVFS=======================================
#ifdef CONFIG_MP_DVFS_FORCE_SET_TARGET_FREQ
#define MP_DVFS_FORCE_SET_TARGET_FREQ 1
#else
#define MP_DVFS_FORCE_SET_TARGET_FREQ 0
#endif

#ifdef CONFIG_MP_DVFS_FORCE_SET_TARGET_FREQ_DEBUG
#define MP_DVFS_FORCE_SET_TARGET_FREQ_DEBUG 1
#else
#define MP_DVFS_FORCE_SET_TARGET_FREQ_DEBUG 0
#endif


#ifdef CONFIG_MP_DVFS_FORCE_USE_ONE_FREQ
#define MP_DVFS_FORCE_USE_ONE_FREQ 1
#else
#define MP_DVFS_FORCE_USE_ONE_FREQ 0
#endif

#ifdef CONFIG_MP_DVFS_FORCE_USE_ONE_FREQ_DEBUG
#define MP_DVFS_FORCE_USE_ONE_FREQ_DEBUG 1
#else
#define MP_DVFS_FORCE_USE_ONE_FREQ_DEBUG 0
#endif


#ifdef CONFIG_MP_DVFS_FORCE_PINGO_TEST
#define MP_DVFS_FORCE_PINGO_TEST 1
#else
#define MP_DVFS_FORCE_PINGO_TEST 0
#endif

#ifdef CONFIG_MP_DVFS_FORCE_PINGO_TEST_DEBUG
#define MP_DVFS_FORCE_PINGO_TEST_DEBUG 1
#else
#define MP_DVFS_FORCE_PINGO_TEST_DEBUG 0
#endif


#ifdef CONFIG_MP_DVFS_FLOW_DEBUG_MESSAGE
#define MP_DVFS_FLOW_DEBUG_MESSAGE 1
#else
#define MP_DVFS_FLOW_DEBUG_MESSAGE 0
#endif

#ifdef CONFIG_MP_DVFS_FLOW_DEBUG_MESSAGE_DEBUG
#define MP_DVFS_FLOW_DEBUG_MESSAGE_DEBUG 1
#else
#define MP_DVFS_FLOW_DEBUG_MESSAGE_DEBUG 0
#endif


#ifdef CONFIG_MP_DVFS_VID_ONLY
#define MP_DVFS_VID_ONLY 1
#else
#define MP_DVFS_VID_ONLY 0
#endif

#ifdef CONFIG_MP_DVFS_VID_ONLY_DEBUG
#define MP_DVFS_VID_ONLY_DEBUG 1
#else
#define MP_DVFS_VID_ONLY_DEBUG 0
#endif


#ifdef CONFIG_MP_DVFS_CPUHOTPLUG
#define MP_DVFS_CPUHOTPLUG 1
#else
#define MP_DVFS_CPUHOTPLUG 0
#endif

#ifdef CONFIG_MP_DVFS_CPUHOTPLUG_DEBUG
#define MP_DVFS_CPUHOTPLUG_DEBUG 1
#else
#define MP_DVFS_CPUHOTPLUG_DEBUG 0
#endif


#ifdef CONFIG_MP_DVFS_CPUHOTPLUG_USE_ONLINE_CPU_MAX_LOAD
#define MP_DVFS_CPUHOTPLUG_USE_ONLINE_CPU_MAX_LOAD 1
#else
#define MP_DVFS_CPUHOTPLUG_USE_ONLINE_CPU_MAX_LOAD 0
#endif

#ifdef CONFIG_MP_DVFS_CPUHOTPLUG_USE_ONLINE_CPU_MAX_LOAD_DEBUG
#define MP_DVFS_CPUHOTPLUG_USE_ONLINE_CPU_MAX_LOAD_DEBUG 1
#else
#define MP_DVFS_CPUHOTPLUG_USE_ONLINE_CPU_MAX_LOAD_DEBUG 0
#endif


#ifdef CONFIG_MP_DVFS_CPUHOTPLUG_USE_ONLINE_CPU_AVERAGE_LOAD
#define MP_DVFS_CPUHOTPLUG_USE_ONLINE_CPU_AVERAGE_LOAD 1
#else
#define MP_DVFS_CPUHOTPLUG_USE_ONLINE_CPU_AVERAGE_LOAD 0
#endif

#ifdef CONFIG_MP_DVFS_CPUHOTPLUG_USE_ONLINE_CPU_AVERAGE_LOAD_DEBUG
#define MP_DVFS_CPUHOTPLUG_USE_ONLINE_CPU_AVERAGE_LOAD_DEBUG 1
#else
#define MP_DVFS_CPUHOTPLUG_USE_ONLINE_CPU_AVERAGE_LOAD_DEBUG 0
#endif


#ifdef CONFIG_MP_DVFS_ONDEMAND_HIGH_PERFORMANCE
#define MP_DVFS_ONDEMAND_HIGH_PERFORMANCE 1
#else
#define MP_DVFS_ONDEMAND_HIGH_PERFORMANCE 0
#endif

#ifdef CONFIG_MP_DVFS_ONDEMAND_HIGH_PERFORMANCE_DEBUG
#define MP_DVFS_ONDEMAND_HIGH_PERFORMANCE_DEBUG 1
#else
#define MP_DVFS_ONDEMAND_HIGH_PERFORMANCE_DEBUG 0
#endif


#ifdef CONFIG_MP_DVFS_ANTUTU_HOTPLUG
#define MP_DVFS_ANTUTU_HOTPLUG 1
#else
#define MP_DVFS_ANTUTU_HOTPLUG 0
#endif

#ifdef CONFIG_MP_DVFS_ANTUTU_HOTPLUG_DEBUG
#define MP_DVFS_ANTUTU_HOTPLUG_DEBUG 1
#else
#define MP_DVFS_ANTUTU_HOTPLUG_DEBUG 0
#endif


#ifdef CONFIG_MP_DVFS_INTERACTIVE_PATCH
#define MP_DVFS_INTERACTIVE_PATCH 1
#else
#define MP_DVFS_INTERACTIVE_PATCH 0
#endif

#ifdef CONFIG_MP_DVFS_INTERACTIVE_PATCH_DEBUG
#define MP_DVFS_INTERACTIVE_PATCH_DEBUG 1
#else
#define MP_DVFS_INTERACTIVE_PATCH_DEBUG 0
#endif


//=========================== Module:CACHE=======================================
#ifdef CONFIG_MP_CACHE_DROP
#define MP_CACHE_DROP 1
#else
#define MP_CACHE_DROP 0
#endif

#ifdef CONFIG_MP_CACHE_DROP_DEBUG
#define MP_CACHE_DROP_DEBUG 1
#else
#define MP_CACHE_DROP_DEBUG 0
#endif


//=========================== Module:ANTUTU=======================================
#ifdef CONFIG_MP_ANTUTU_MSTAR_HIDE_SCHED_POLICY
#define MP_ANTUTU_MSTAR_HIDE_SCHED_POLICY 1
#else
#define MP_ANTUTU_MSTAR_HIDE_SCHED_POLICY 0
#endif

#ifdef CONFIG_MP_ANTUTU_MSTAR_HIDE_SCHED_POLICY_DEBUG
#define MP_ANTUTU_MSTAR_HIDE_SCHED_POLICY_DEBUG 1
#else
#define MP_ANTUTU_MSTAR_HIDE_SCHED_POLICY_DEBUG 0
#endif


//=========================== Module:ZRAM=======================================
#ifdef CONFIG_MP_ZRAM_ZRAM_USING_CMA_PAGES
#define MP_ZRAM_ZRAM_USING_CMA_PAGES 1
#else
#define MP_ZRAM_ZRAM_USING_CMA_PAGES 0
#endif

#ifdef CONFIG_MP_ZRAM_ZRAM_USING_CMA_PAGES_DEBUG
#define MP_ZRAM_ZRAM_USING_CMA_PAGES_DEBUG 1
#else
#define MP_ZRAM_ZRAM_USING_CMA_PAGES_DEBUG 0
#endif


//=========================== Module:KERNEL_COMPAT=======================================
#ifdef CONFIG_MP_KERNEL_COMPAT_PATCH_FIX_INODE_CLUSTER_LIST
#define MP_KERNEL_COMPAT_PATCH_FIX_INODE_CLUSTER_LIST 1
#else
#define MP_KERNEL_COMPAT_PATCH_FIX_INODE_CLUSTER_LIST 0
#endif

#ifdef CONFIG_MP_KERNEL_COMPAT_PATCH_FIX_INODE_CLUSTER_LIST_DEBUG
#define MP_KERNEL_COMPAT_PATCH_FIX_INODE_CLUSTER_LIST_DEBUG 1
#else
#define MP_KERNEL_COMPAT_PATCH_FIX_INODE_CLUSTER_LIST_DEBUG 0
#endif


//=========================== Module:PAGE_GLOBAL_DIRECTORY=======================================
#ifdef CONFIG_MP_PAGE_GLOBAL_DIRECTORY_SPEEDUP
#define MP_PAGE_GLOBAL_DIRECTORY_SPEEDUP 1
#else
#define MP_PAGE_GLOBAL_DIRECTORY_SPEEDUP 0
#endif

#ifdef CONFIG_MP_PAGE_GLOBAL_DIRECTORY_SPEEDUP_DEBUG
#define MP_PAGE_GLOBAL_DIRECTORY_SPEEDUP_DEBUG 1
#else
#define MP_PAGE_GLOBAL_DIRECTORY_SPEEDUP_DEBUG 0
#endif


//=========================== Module:PCI_PATCH=======================================
#ifdef CONFIG_MP_PCI_PATCH_ADDR_TRANSLATE
#define MP_PCI_PATCH_ADDR_TRANSLATE 1
#else
#define MP_PCI_PATCH_ADDR_TRANSLATE 0
#endif

#ifdef CONFIG_MP_PCI_PATCH_ADDR_TRANSLATE_DEBUG
#define MP_PCI_PATCH_ADDR_TRANSLATE_DEBUG 1
#else
#define MP_PCI_PATCH_ADDR_TRANSLATE_DEBUG 0
#endif


//=========================== Module:PCI=======================================
#ifdef CONFIG_MP_PCI_MSTAR
#define MP_PCI_MSTAR 1
#else
#define MP_PCI_MSTAR 0
#endif

#ifdef CONFIG_MP_PCI_MSTAR_DEBUG
#define MP_PCI_MSTAR_DEBUG 1
#else
#define MP_PCI_MSTAR_DEBUG 0
#endif


//=========================== Module:DDI=======================================
#ifdef CONFIG_MP_DDI_64BIT_KERNEL_APPLY_32BIT_BINDER_API
#define MP_DDI_64BIT_KERNEL_APPLY_32BIT_BINDER_API 1
#else
#define MP_DDI_64BIT_KERNEL_APPLY_32BIT_BINDER_API 0
#endif

#ifdef CONFIG_MP_DDI_64BIT_KERNEL_APPLY_32BIT_BINDER_API_DEBUG
#define MP_DDI_64BIT_KERNEL_APPLY_32BIT_BINDER_API_DEBUG 1
#else
#define MP_DDI_64BIT_KERNEL_APPLY_32BIT_BINDER_API_DEBUG 0
#endif


//=========================== Module:XC_HDR=======================================
#ifdef CONFIG_MP_XC_HDR_1_4_0
#define MP_XC_HDR_1_4_0 1
#else
#define MP_XC_HDR_1_4_0 0
#endif

#ifdef CONFIG_MP_XC_HDR_1_4_0_DEBUG
#define MP_XC_HDR_1_4_0_DEBUG 1
#else
#define MP_XC_HDR_1_4_0_DEBUG 0
#endif


#ifdef CONFIG_MP_XC_HDR_1_4_2
#define MP_XC_HDR_1_4_2 1
#else
#define MP_XC_HDR_1_4_2 0
#endif

#ifdef CONFIG_MP_XC_HDR_1_4_2_DEBUG
#define MP_XC_HDR_1_4_2_DEBUG 1
#else
#define MP_XC_HDR_1_4_2_DEBUG 0
#endif


//=========================== Module:PRINTK=======================================
#ifdef CONFIG_MP_PRINTK_NO_CONSOLE_VERBOSE
#define MP_PRINTK_NO_CONSOLE_VERBOSE 1
#else
#define MP_PRINTK_NO_CONSOLE_VERBOSE 0
#endif

#ifdef CONFIG_MP_PRINTK_NO_CONSOLE_VERBOSE_DEBUG
#define MP_PRINTK_NO_CONSOLE_VERBOSE_DEBUG 1
#else
#define MP_PRINTK_NO_CONSOLE_VERBOSE_DEBUG 0
#endif


//=========================== Module:SEQLOCK=======================================
#ifdef CONFIG_MP_SEQLOCK_RCU_STALL
#define MP_SEQLOCK_RCU_STALL 1
#else
#define MP_SEQLOCK_RCU_STALL 0
#endif

#ifdef CONFIG_MP_SEQLOCK_RCU_STALL_DEBUG
#define MP_SEQLOCK_RCU_STALL_DEBUG 1
#else
#define MP_SEQLOCK_RCU_STALL_DEBUG 0
#endif


//=========================== Module:R2_STR=======================================
#ifdef CONFIG_MP_R2_STR_ENABLE
#define MP_R2_STR_ENABLE 1
#else
#define MP_R2_STR_ENABLE 0
#endif

#ifdef CONFIG_MP_R2_STR_ENABLE_DEBUG
#define MP_R2_STR_ENABLE_DEBUG 1
#else
#define MP_R2_STR_ENABLE_DEBUG 0
#endif


//=========================== Module:HRT_TIMER=======================================
#ifdef CONFIG_MP_HRT_TIMER_ENABLE
#define MP_HRT_TIMER_ENABLE 1
#else
#define MP_HRT_TIMER_ENABLE 0
#endif

#ifdef CONFIG_MP_HRT_TIMER_ENABLE_DEBUG
#define MP_HRT_TIMER_ENABLE_DEBUG 1
#else
#define MP_HRT_TIMER_ENABLE_DEBUG 0
#endif


