#
# Makefile for MStar sar drivers.
#

# general options
EXTRA_CFLAGS      +=  -Idrivers/mstar/include

# specific options
EXTRA_CFLAGS      +=  -DTITANIA
EXTRA_CFLAGS      +=  -DMSOS_TYPE_LINUX

# files
obj-$(CONFIG_MS_SAR)	+= mdrv_sar.o
