/* Copyright (C) 2014 Cadence Design Systems.  All rights reserved           */
/* THIS FILE IS AUTOMATICALLY GENERATED BY CADENCE BLUEPRINT, DO NOT EDIT    */
/*                                                                           */


#ifndef __REG_CDN_AXI_WRAPPER_IB_H__
#define __REG_CDN_AXI_WRAPPER_IB_H__

#include "cdn_axi_wrapper_ib_macro.h"

struct cdn_axi_wrapper_ib {
  volatile uint32_t addr0;                        /*        0x0 - 0x4        */
  volatile uint32_t addr1;                        /*        0x4 - 0x8        */
};

#endif /* __REG_CDN_AXI_WRAPPER_IB_H__ */
