#
# Makefile for MStar Utopia2K STR device drivers.
#

# general options
EXTRA_CFLAGS      +=  -Idrivers/mstar2/include
EXTRA_CFLAGS      +=  -Idrivers/mstar2/drv/utopia2k_str
EXTRA_CFLAGS      +=  -Idrivers/mstar2/include/sys/common
# specific options
EXTRA_CFLAGS      +=

# files
obj-$(CONFIG_MSTAR_UTOPIA2K_STR)	+= mdrv_utopia2k_str.o
mdrv-utopia2k-str-objs			+= mdrv_utopia2k_str.o