///////////////////////////////////////////////////////////////////////////////////////////////////
//
// * Copyright (c) 2008 - 2009 Mstar Semiconductor, Inc.
// This program is free software.
// You can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation;
// either version 2 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with this program;
// if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
//
///////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////
//
// @file   mdrv_mbx_io.h
// @brief  Mialbox KMD Driver Interface
// @author MStar Semiconductor Inc.
//
// Driver to initialize and access mailbox.
//     - Provide functions to initialize/de-initialize mailbox
//     - Provide mailbox functional access.
//////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef _MDRV_MBX_COMPAT_IO_H
#define _MDRV_MBX_COMPAT_IO_H

//=============================================================================
// Includs
//=============================================================================
#include "mdrv_mbx_compat_st.h"

//=============================================================================
// Defines
//=============================================================================
//IO Ctrl defines:
#define COMPAT_MDRV_MBX_IOC_INIT_NR				0
#define COMPAT_MDRV_MBX_IOC_DEINIT_NR			COMPAT_MDRV_MBX_IOC_INIT_NR+1
#define COMPAT_MDRV_MBX_IOC_REGISTERMSG_NR		COMPAT_MDRV_MBX_IOC_DEINIT_NR+1
#define COMPAT_MDRV_MBX_IOC_UNREGISTERMSG_NR	COMPAT_MDRV_MBX_IOC_REGISTERMSG_NR+1
#define COMPAT_MDRV_MBX_IOC_CLEARMSG_NR         COMPAT_MDRV_MBX_IOC_UNREGISTERMSG_NR+1
#define COMPAT_MDRV_MBX_IOC_SENDMSG_NR			COMPAT_MDRV_MBX_IOC_CLEARMSG_NR+1
#define COMPAT_MDRV_MBX_IOC_SENDMSGLOOPBACK_NR  COMPAT_MDRV_MBX_IOC_SENDMSG_NR+1
#define COMPAT_MDRV_MBX_IOC_RECVMSG_NR			COMPAT_MDRV_MBX_IOC_SENDMSGLOOPBACK_NR+1
#define COMPAT_MDRV_MBX_IOC_GETMSGQSTATUS_NR	COMPAT_MDRV_MBX_IOC_RECVMSG_NR+1
#define COMPAT_MDRV_MBX_IOC_MBXENABLE_NR		COMPAT_MDRV_MBX_IOC_GETMSGQSTATUS_NR+1
#define COMPAT_MDRV_MBX_IOC_SETINFORMATION_NR   COMPAT_MDRV_MBX_IOC_MBXENABLE_NR+1
#define COMPAT_MDRV_MBX_IOC_GETINFORMATION_NR   COMPAT_MDRV_MBX_IOC_SETINFORMATION_NR+1
#define COMPAT_MDRV_MBX_IOC_GETDRVSTATUS_NR     COMPAT_MDRV_MBX_IOC_GETINFORMATION_NR+1
#define COMPAT_MDRV_MBX_IOC_CHECKMSG_NR		    COMPAT_MDRV_MBX_IOC_GETDRVSTATUS_NR+1
#define COMPAT_MDRV_MBX_IOC_REMOVEMSG_NR		COMPAT_MDRV_MBX_IOC_CHECKMSG_NR+1
#define COMPAT_MDRV_PM_IOC_GET_BRICKTERMINATOR_INFO_NR       COMPAT_MDRV_MBX_IOC_REMOVEMSG_NR+1               
#define COMPAT_MDRV_PM_IOC_SET_BRICKTERMINATOR_INFO_NR       COMPAT_MDRV_PM_IOC_GET_BRICKTERMINATOR_INFO_NR+1      
#define COMPAT_MDRV_MBX_IOC_MAX_NR				COMPAT_MDRV_PM_IOC_SET_BRICKTERMINATOR_INFO_NR +1


// use 'm' as magic number
#define COMPAT_MDRV_MBX_IOC_MAGIC			  'm'
#define COMPAT_MDRV_MBX_IOC_INIT         	  _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_INIT_NR, COMPAT_MS_MBX_INIT_INFO)
#define COMPAT_MDRV_MBX_IOC_DEINIT			  _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_DEINIT_NR, COMPAT_MS_MBX_SET_BINFO)
#define COMPAT_MDRV_MBX_IOC_REGISTERMSG		  _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_REGISTERMSG_NR, COMPAT_MS_MBX_REGISTER_MSG)
#define COMPAT_MDRV_MBX_IOC_UNREGISTERMSG	  _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_UNREGISTERMSG_NR, COMPAT_MS_MBX_UNREGISTER_MSG)
#define COMPAT_MDRV_mBX_IOC_CLEARMSG          _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_CLEARMSG_NR, COMPAT_MS_MBX_CLEAR_MSG)
#define COMPAT_MDRV_MBX_IOC_SENDMSG			  _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_SENDMSG_NR, COMPAT_MS_MBX_SEND_MSG)
#define COMPAT_MDRV_MBX_IOC_RECVMSG			  _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_RECVMSG_NR, COMPAT_MS_MBX_RECV_MSG)
#define COMPAT_MDRV_MBX_IOC_CHECKMSG           _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_CHECKMSG_NR, COMPAT_MS_MBX_RECV_MSG)
#define COMPAT_MDRV_MBX_IOC_REMOVEMSG           _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_REMOVEMSG_NR, COMPAT_MS_MBX_SET_BINFO)
#define COMPAT_MDRV_MBX_IOC_GETMSGQSTATUS	  _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_GETMSGQSTATUS_NR, COMPAT_MS_MBX_GET_MSGQSTATUS)
#define COMPAT_MDRV_MBX_IOC_SENDMSGLOOPBACK   _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_SENDMSGLOOPBACK_NR, COMPAT_MS_MBX_SEND_MSG)
#define COMPAT_MDRV_MBX_IOC_MBXENABLE		  _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_MBXENABLE_NR, COMPAT_MS_MBX_SET_BINFO)
#define COMPAT_MDRV_MBX_IOC_SETINFORMATION	  _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_SETINFORMATION_NR, COMPAT_MS_MBX_CPROSYNC_INFORMATION)
#define COMPAT_MDRV_MBX_IOC_GETINFORMATION	  _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_GETINFORMATION_NR, COMPAT_MS_MBX_CPROSYNC_INFORMATION)
#define COMPAT_MDRV_MBX_IOC_GETDRVSTATUS      _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_MBX_IOC_GETDRVSTATUS_NR, COMPAT_MS_MBX_GET_DRVSTATUS)

#define COMPAT_MDRV_PM_IOC_GET_BRICKTERMINATOR_INFO    _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_PM_IOC_GET_BRICKTERMINATOR_INFO_NR, COMPAT_MS_PM_BRICK_TERMINATOR_INFO)    
#define COMPAT_MDRV_PM_IOC_SET_BRICKTERMINATOR_INFO    _IOWR(COMPAT_MDRV_MBX_IOC_MAGIC, COMPAT_MDRV_PM_IOC_SET_BRICKTERMINATOR_INFO_NR, COMPAT_MS_PM_BRICK_TERMINATOR_INFO)   

#endif //_MDRV_MBX_COMPAT_IO_H
