EXTRA_CFLAGS      +=  -Idrivers/mstar/include

obj-y += ms_chip.o atags_to_fdt.o 
obj-$(CONFIG_TI_CMEM_STUB) += cmemk_stub.o

obj-$(CONFIG_ARCH_CEDRIC) += cedric/
obj-$(CONFIG_ARCH_INFINITY) += infinity/
obj-$(CONFIG_ARCH_CHICAGO) += chicago/
obj-$(CONFIG_ARCH_INFINITY3) += infinity3/