/* Copyright (C) 2014 Cadence Design Systems.  All rights reserved           */
/* THIS FILE IS AUTOMATICALLY GENERATED BY CADENCE BLUEPRINT, DO NOT EDIT    */
/*                                                                           */


#ifndef __REG_PCIE_UDMA_ADDRMAP_MACRO_H__
#define __REG_PCIE_UDMA_ADDRMAP_MACRO_H__


/* macros for BlueprintGlobalNameSpace::pcie_udma_addrmap::udma_ch_ctrl_reg */
#ifndef __PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG_MACRO__
#define __PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG_MACRO__

/* macros for field go */
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__GO__SHIFT                        0
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__GO__WIDTH                        1
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__GO__MASK               0x00000001U
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__GO__READ(src) \
                    (uint32_t)(src)\
                    & 0x00000001U
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__GO__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0x00000001U)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__GO__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000001U) | ((uint32_t)(src) &\
                    0x00000001U)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__GO__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0x00000001U)))
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__GO__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000001U) | (uint32_t)(1)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__GO__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000001U) | (uint32_t)(0)

/* macros for field ob_not_ib */
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__OB_NOT_IB__SHIFT                 1
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__OB_NOT_IB__WIDTH                 1
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__OB_NOT_IB__MASK        0x00000002U
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__OB_NOT_IB__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000002U) >> 1)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__OB_NOT_IB__WRITE(src) \
                    (((uint32_t)(src)\
                    << 1) & 0x00000002U)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__OB_NOT_IB__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000002U) | (((uint32_t)(src) <<\
                    1) & 0x00000002U)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__OB_NOT_IB__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 1) & ~0x00000002U)))
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__OB_NOT_IB__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000002U) | ((uint32_t)(1) << 1)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__OB_NOT_IB__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000002U) | ((uint32_t)(0) << 1)

/* macros for field reserve_30 */
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__RESERVE_30__SHIFT                2
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__RESERVE_30__WIDTH               30
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__RESERVE_30__MASK       0xfffffffcU
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__RESERVE_30__READ(src) \
                    (((uint32_t)(src)\
                    & 0xfffffffcU) >> 2)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__TYPE                      uint32_t
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__READ                   0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG__WRITE                  0xffffffffU

#endif /* __PCIE_UDMA_ADDRMAP__UDMA_CH_CTRL_REG_MACRO__ */


/* macros for dma_ch0.channel_ctrl */
#define INST_DMA_CH0__CHANNEL_CTRL__NUM                                       1

/* macros for BlueprintGlobalNameSpace::pcie_udma_addrmap::udma_ch_sp_l_reg */
#ifndef __PCIE_UDMA_ADDRMAP__UDMA_CH_SP_L_REG_MACRO__
#define __PCIE_UDMA_ADDRMAP__UDMA_CH_SP_L_REG_MACRO__

/* macros for field ptr */
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_L_REG__PTR__SHIFT                       0
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_L_REG__PTR__WIDTH                      32
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_L_REG__PTR__MASK              0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_L_REG__PTR__READ(src) \
                    (uint32_t)(src)\
                    & 0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_L_REG__PTR__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0xffffffffU)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_L_REG__PTR__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0xffffffffU) | ((uint32_t)(src) &\
                    0xffffffffU)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_L_REG__PTR__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0xffffffffU)))
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_L_REG__TYPE                      uint32_t
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_L_REG__READ                   0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_L_REG__WRITE                  0xffffffffU

#endif /* __PCIE_UDMA_ADDRMAP__UDMA_CH_SP_L_REG_MACRO__ */


/* macros for dma_ch0.channel_sp_l */
#define INST_DMA_CH0__CHANNEL_SP_L__NUM                                       1

/* macros for BlueprintGlobalNameSpace::pcie_udma_addrmap::udma_ch_sp_u_reg */
#ifndef __PCIE_UDMA_ADDRMAP__UDMA_CH_SP_U_REG_MACRO__
#define __PCIE_UDMA_ADDRMAP__UDMA_CH_SP_U_REG_MACRO__

/* macros for field ptr */
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_U_REG__PTR__SHIFT                       0
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_U_REG__PTR__WIDTH                      32
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_U_REG__PTR__MASK              0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_U_REG__PTR__READ(src) \
                    (uint32_t)(src)\
                    & 0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_U_REG__PTR__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0xffffffffU)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_U_REG__PTR__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0xffffffffU) | ((uint32_t)(src) &\
                    0xffffffffU)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_U_REG__PTR__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0xffffffffU)))
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_U_REG__TYPE                      uint32_t
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_U_REG__READ                   0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_CH_SP_U_REG__WRITE                  0xffffffffU

#endif /* __PCIE_UDMA_ADDRMAP__UDMA_CH_SP_U_REG_MACRO__ */


/* macros for dma_ch0.channel_sp_u */
#define INST_DMA_CH0__CHANNEL_SP_U__NUM                                       1

/* macros for BlueprintGlobalNameSpace::pcie_udma_addrmap::udma_ch_attr_l_reg */
#ifndef __PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_L_REG_MACRO__
#define __PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_L_REG_MACRO__

/* macros for field attr */
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_L_REG__ATTR__SHIFT                    0
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_L_REG__ATTR__WIDTH                   32
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_L_REG__ATTR__MASK           0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_L_REG__ATTR__READ(src) \
                    (uint32_t)(src)\
                    & 0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_L_REG__ATTR__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0xffffffffU)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_L_REG__ATTR__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0xffffffffU) | ((uint32_t)(src) &\
                    0xffffffffU)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_L_REG__ATTR__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0xffffffffU)))
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_L_REG__TYPE                    uint32_t
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_L_REG__READ                 0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_L_REG__WRITE                0xffffffffU

#endif /* __PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_L_REG_MACRO__ */


/* macros for dma_ch0.channel_attr_l */
#define INST_DMA_CH0__CHANNEL_ATTR_L__NUM                                     1

/* macros for BlueprintGlobalNameSpace::pcie_udma_addrmap::udma_ch_attr_h_reg */
#ifndef __PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_H_REG_MACRO__
#define __PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_H_REG_MACRO__

/* macros for field attr */
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_H_REG__ATTR__SHIFT                    0
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_H_REG__ATTR__WIDTH                   32
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_H_REG__ATTR__MASK           0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_H_REG__ATTR__READ(src) \
                    (uint32_t)(src)\
                    & 0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_H_REG__ATTR__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0xffffffffU)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_H_REG__ATTR__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0xffffffffU) | ((uint32_t)(src) &\
                    0xffffffffU)
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_H_REG__ATTR__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0xffffffffU)))
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_H_REG__TYPE                    uint32_t
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_H_REG__READ                 0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_H_REG__WRITE                0xffffffffU

#endif /* __PCIE_UDMA_ADDRMAP__UDMA_CH_ATTR_H_REG_MACRO__ */


/* macros for dma_ch0.channel_attr_u */
#define INST_DMA_CH0__CHANNEL_ATTR_U__NUM                                     1

/* macros for BlueprintGlobalNameSpace::pcie_udma_addrmap::udma_int_regs */
#ifndef __PCIE_UDMA_ADDRMAP__UDMA_INT_REGS_MACRO__
#define __PCIE_UDMA_ADDRMAP__UDMA_INT_REGS_MACRO__

/* macros for field ch0_done_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_DONE_INT__SHIFT                 0
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_DONE_INT__WIDTH                 1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_DONE_INT__MASK        0x00000001U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_DONE_INT__READ(src) \
                    (uint32_t)(src)\
                    & 0x00000001U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_DONE_INT__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0x00000001U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_DONE_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000001U) | ((uint32_t)(src) &\
                    0x00000001U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_DONE_INT__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0x00000001U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_DONE_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000001U) | (uint32_t)(1)

/* macros for field ch1_done_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_DONE_INT__SHIFT                 1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_DONE_INT__WIDTH                 1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_DONE_INT__MASK        0x00000002U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_DONE_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000002U) >> 1)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_DONE_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 1) & 0x00000002U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_DONE_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000002U) | (((uint32_t)(src) <<\
                    1) & 0x00000002U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_DONE_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 1) & ~0x00000002U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_DONE_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000002U) | ((uint32_t)(1) << 1)

/* macros for field ch2_done_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_DONE_INT__SHIFT                 2
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_DONE_INT__WIDTH                 1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_DONE_INT__MASK        0x00000004U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_DONE_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000004U) >> 2)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_DONE_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 2) & 0x00000004U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_DONE_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000004U) | (((uint32_t)(src) <<\
                    2) & 0x00000004U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_DONE_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 2) & ~0x00000004U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_DONE_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000004U) | ((uint32_t)(1) << 2)

/* macros for field ch3_done_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_DONE_INT__SHIFT                 3
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_DONE_INT__WIDTH                 1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_DONE_INT__MASK        0x00000008U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_DONE_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000008U) >> 3)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_DONE_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 3) & 0x00000008U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_DONE_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000008U) | (((uint32_t)(src) <<\
                    3) & 0x00000008U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_DONE_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 3) & ~0x00000008U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_DONE_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000008U) | ((uint32_t)(1) << 3)

/* macros for field ch4_done_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_DONE_INT__SHIFT                 4
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_DONE_INT__WIDTH                 1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_DONE_INT__MASK        0x00000010U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_DONE_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000010U) >> 4)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_DONE_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 4) & 0x00000010U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_DONE_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000010U) | (((uint32_t)(src) <<\
                    4) & 0x00000010U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_DONE_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 4) & ~0x00000010U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_DONE_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000010U) | ((uint32_t)(1) << 4)

/* macros for field ch5_done_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_DONE_INT__SHIFT                 5
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_DONE_INT__WIDTH                 1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_DONE_INT__MASK        0x00000020U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_DONE_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000020U) >> 5)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_DONE_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 5) & 0x00000020U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_DONE_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000020U) | (((uint32_t)(src) <<\
                    5) & 0x00000020U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_DONE_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 5) & ~0x00000020U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_DONE_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000020U) | ((uint32_t)(1) << 5)

/* macros for field ch6_done_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_DONE_INT__SHIFT                 6
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_DONE_INT__WIDTH                 1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_DONE_INT__MASK        0x00000040U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_DONE_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000040U) >> 6)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_DONE_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 6) & 0x00000040U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_DONE_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000040U) | (((uint32_t)(src) <<\
                    6) & 0x00000040U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_DONE_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 6) & ~0x00000040U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_DONE_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000040U) | ((uint32_t)(1) << 6)

/* macros for field ch7_done_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_DONE_INT__SHIFT                 7
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_DONE_INT__WIDTH                 1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_DONE_INT__MASK        0x00000080U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_DONE_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000080U) >> 7)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_DONE_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 7) & 0x00000080U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_DONE_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000080U) | (((uint32_t)(src) <<\
                    7) & 0x00000080U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_DONE_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 7) & ~0x00000080U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_DONE_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000080U) | ((uint32_t)(1) << 7)

/* macros for field ch0_error_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_ERROR_INT__SHIFT                8
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_ERROR_INT__WIDTH                1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_ERROR_INT__MASK       0x00000100U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_ERROR_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000100U) >> 8)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_ERROR_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 8) & 0x00000100U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_ERROR_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000100U) | (((uint32_t)(src) <<\
                    8) & 0x00000100U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_ERROR_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 8) & ~0x00000100U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH0_ERROR_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000100U) | ((uint32_t)(1) << 8)

/* macros for field ch1_error_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_ERROR_INT__SHIFT                9
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_ERROR_INT__WIDTH                1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_ERROR_INT__MASK       0x00000200U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_ERROR_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000200U) >> 9)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_ERROR_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 9) & 0x00000200U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_ERROR_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000200U) | (((uint32_t)(src) <<\
                    9) & 0x00000200U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_ERROR_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 9) & ~0x00000200U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH1_ERROR_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000200U) | ((uint32_t)(1) << 9)

/* macros for field ch2_error_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_ERROR_INT__SHIFT               10
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_ERROR_INT__WIDTH                1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_ERROR_INT__MASK       0x00000400U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_ERROR_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000400U) >> 10)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_ERROR_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 10) & 0x00000400U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_ERROR_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000400U) | (((uint32_t)(src) <<\
                    10) & 0x00000400U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_ERROR_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 10) & ~0x00000400U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH2_ERROR_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000400U) | ((uint32_t)(1) << 10)

/* macros for field ch3_error_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_ERROR_INT__SHIFT               11
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_ERROR_INT__WIDTH                1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_ERROR_INT__MASK       0x00000800U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_ERROR_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000800U) >> 11)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_ERROR_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 11) & 0x00000800U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_ERROR_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000800U) | (((uint32_t)(src) <<\
                    11) & 0x00000800U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_ERROR_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 11) & ~0x00000800U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH3_ERROR_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000800U) | ((uint32_t)(1) << 11)

/* macros for field ch4_error_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_ERROR_INT__SHIFT               12
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_ERROR_INT__WIDTH                1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_ERROR_INT__MASK       0x00001000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_ERROR_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00001000U) >> 12)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_ERROR_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 12) & 0x00001000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_ERROR_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00001000U) | (((uint32_t)(src) <<\
                    12) & 0x00001000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_ERROR_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 12) & ~0x00001000U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH4_ERROR_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00001000U) | ((uint32_t)(1) << 12)

/* macros for field ch5_error_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_ERROR_INT__SHIFT               13
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_ERROR_INT__WIDTH                1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_ERROR_INT__MASK       0x00002000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_ERROR_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00002000U) >> 13)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_ERROR_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 13) & 0x00002000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_ERROR_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00002000U) | (((uint32_t)(src) <<\
                    13) & 0x00002000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_ERROR_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 13) & ~0x00002000U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH5_ERROR_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00002000U) | ((uint32_t)(1) << 13)

/* macros for field ch6_error_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_ERROR_INT__SHIFT               14
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_ERROR_INT__WIDTH                1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_ERROR_INT__MASK       0x00004000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_ERROR_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00004000U) >> 14)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_ERROR_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 14) & 0x00004000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_ERROR_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00004000U) | (((uint32_t)(src) <<\
                    14) & 0x00004000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_ERROR_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 14) & ~0x00004000U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH6_ERROR_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00004000U) | ((uint32_t)(1) << 14)

/* macros for field ch7_error_int */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_ERROR_INT__SHIFT               15
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_ERROR_INT__WIDTH                1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_ERROR_INT__MASK       0x00008000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_ERROR_INT__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00008000U) >> 15)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_ERROR_INT__WRITE(src) \
                    (((uint32_t)(src)\
                    << 15) & 0x00008000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_ERROR_INT__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00008000U) | (((uint32_t)(src) <<\
                    15) & 0x00008000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_ERROR_INT__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 15) & ~0x00008000U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__CH7_ERROR_INT__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00008000U) | ((uint32_t)(1) << 15)

/* macros for field reserve_16 */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__RESERVE_16__SHIFT                  16
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__RESERVE_16__WIDTH                  16
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__RESERVE_16__MASK          0xffff0000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__RESERVE_16__READ(src) \
                    (((uint32_t)(src)\
                    & 0xffff0000U) >> 16)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__TYPE                         uint32_t
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__READ                      0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__WRITE                     0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_INT_REGS__WOCLR                     0x0000ffffU

#endif /* __PCIE_UDMA_ADDRMAP__UDMA_INT_REGS_MACRO__ */


/* macros for dma_common.common_udma_int */
#define INST_DMA_COMMON__COMMON_UDMA_INT__NUM                                 1

/* macros for BlueprintGlobalNameSpace::pcie_udma_addrmap::udma_int_ena_regs */
#ifndef __PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS_MACRO__
#define __PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS_MACRO__

/* macros for field ch0_done_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_DONE_ENA__SHIFT             0
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_DONE_ENA__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_DONE_ENA__MASK    0x00000001U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_DONE_ENA__READ(src) \
                    (uint32_t)(src)\
                    & 0x00000001U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_DONE_ENA__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0x00000001U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_DONE_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000001U) | ((uint32_t)(src) &\
                    0x00000001U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_DONE_ENA__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0x00000001U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_DONE_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000001U) | (uint32_t)(1)

/* macros for field ch1_done_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_DONE_ENA__SHIFT             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_DONE_ENA__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_DONE_ENA__MASK    0x00000002U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_DONE_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000002U) >> 1)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_DONE_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 1) & 0x00000002U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_DONE_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000002U) | (((uint32_t)(src) <<\
                    1) & 0x00000002U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_DONE_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 1) & ~0x00000002U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_DONE_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000002U) | ((uint32_t)(1) << 1)

/* macros for field ch2_done_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_DONE_ENA__SHIFT             2
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_DONE_ENA__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_DONE_ENA__MASK    0x00000004U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_DONE_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000004U) >> 2)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_DONE_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 2) & 0x00000004U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_DONE_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000004U) | (((uint32_t)(src) <<\
                    2) & 0x00000004U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_DONE_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 2) & ~0x00000004U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_DONE_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000004U) | ((uint32_t)(1) << 2)

/* macros for field ch3_done_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_DONE_ENA__SHIFT             3
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_DONE_ENA__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_DONE_ENA__MASK    0x00000008U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_DONE_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000008U) >> 3)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_DONE_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 3) & 0x00000008U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_DONE_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000008U) | (((uint32_t)(src) <<\
                    3) & 0x00000008U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_DONE_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 3) & ~0x00000008U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_DONE_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000008U) | ((uint32_t)(1) << 3)

/* macros for field ch4_done_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_DONE_ENA__SHIFT             4
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_DONE_ENA__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_DONE_ENA__MASK    0x00000010U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_DONE_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000010U) >> 4)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_DONE_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 4) & 0x00000010U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_DONE_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000010U) | (((uint32_t)(src) <<\
                    4) & 0x00000010U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_DONE_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 4) & ~0x00000010U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_DONE_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000010U) | ((uint32_t)(1) << 4)

/* macros for field ch5_done_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_DONE_ENA__SHIFT             5
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_DONE_ENA__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_DONE_ENA__MASK    0x00000020U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_DONE_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000020U) >> 5)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_DONE_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 5) & 0x00000020U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_DONE_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000020U) | (((uint32_t)(src) <<\
                    5) & 0x00000020U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_DONE_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 5) & ~0x00000020U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_DONE_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000020U) | ((uint32_t)(1) << 5)

/* macros for field ch6_done_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_DONE_ENA__SHIFT             6
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_DONE_ENA__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_DONE_ENA__MASK    0x00000040U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_DONE_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000040U) >> 6)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_DONE_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 6) & 0x00000040U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_DONE_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000040U) | (((uint32_t)(src) <<\
                    6) & 0x00000040U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_DONE_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 6) & ~0x00000040U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_DONE_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000040U) | ((uint32_t)(1) << 6)

/* macros for field ch7_done_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_DONE_ENA__SHIFT             7
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_DONE_ENA__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_DONE_ENA__MASK    0x00000080U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_DONE_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000080U) >> 7)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_DONE_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 7) & 0x00000080U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_DONE_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000080U) | (((uint32_t)(src) <<\
                    7) & 0x00000080U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_DONE_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 7) & ~0x00000080U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_DONE_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000080U) | ((uint32_t)(1) << 7)

/* macros for field ch0_error_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_ERROR_ENA__SHIFT            8
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_ERROR_ENA__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_ERROR_ENA__MASK   0x00000100U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_ERROR_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000100U) >> 8)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_ERROR_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 8) & 0x00000100U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_ERROR_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000100U) | (((uint32_t)(src) <<\
                    8) & 0x00000100U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_ERROR_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 8) & ~0x00000100U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH0_ERROR_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000100U) | ((uint32_t)(1) << 8)

/* macros for field ch1_error_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_ERROR_ENA__SHIFT            9
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_ERROR_ENA__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_ERROR_ENA__MASK   0x00000200U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_ERROR_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000200U) >> 9)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_ERROR_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 9) & 0x00000200U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_ERROR_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000200U) | (((uint32_t)(src) <<\
                    9) & 0x00000200U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_ERROR_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 9) & ~0x00000200U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH1_ERROR_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000200U) | ((uint32_t)(1) << 9)

/* macros for field ch2_error_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_ERROR_ENA__SHIFT           10
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_ERROR_ENA__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_ERROR_ENA__MASK   0x00000400U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_ERROR_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000400U) >> 10)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_ERROR_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 10) & 0x00000400U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_ERROR_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000400U) | (((uint32_t)(src) <<\
                    10) & 0x00000400U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_ERROR_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 10) & ~0x00000400U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH2_ERROR_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000400U) | ((uint32_t)(1) << 10)

/* macros for field ch3_error_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_ERROR_ENA__SHIFT           11
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_ERROR_ENA__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_ERROR_ENA__MASK   0x00000800U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_ERROR_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000800U) >> 11)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_ERROR_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 11) & 0x00000800U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_ERROR_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000800U) | (((uint32_t)(src) <<\
                    11) & 0x00000800U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_ERROR_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 11) & ~0x00000800U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH3_ERROR_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000800U) | ((uint32_t)(1) << 11)

/* macros for field ch4_error_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_ERROR_ENA__SHIFT           12
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_ERROR_ENA__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_ERROR_ENA__MASK   0x00001000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_ERROR_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00001000U) >> 12)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_ERROR_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 12) & 0x00001000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_ERROR_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00001000U) | (((uint32_t)(src) <<\
                    12) & 0x00001000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_ERROR_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 12) & ~0x00001000U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH4_ERROR_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00001000U) | ((uint32_t)(1) << 12)

/* macros for field ch5_error_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_ERROR_ENA__SHIFT           13
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_ERROR_ENA__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_ERROR_ENA__MASK   0x00002000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_ERROR_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00002000U) >> 13)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_ERROR_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 13) & 0x00002000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_ERROR_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00002000U) | (((uint32_t)(src) <<\
                    13) & 0x00002000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_ERROR_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 13) & ~0x00002000U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH5_ERROR_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00002000U) | ((uint32_t)(1) << 13)

/* macros for field ch6_error_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_ERROR_ENA__SHIFT           14
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_ERROR_ENA__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_ERROR_ENA__MASK   0x00004000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_ERROR_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00004000U) >> 14)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_ERROR_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 14) & 0x00004000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_ERROR_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00004000U) | (((uint32_t)(src) <<\
                    14) & 0x00004000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_ERROR_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 14) & ~0x00004000U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH6_ERROR_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00004000U) | ((uint32_t)(1) << 14)

/* macros for field ch7_error_ena */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_ERROR_ENA__SHIFT           15
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_ERROR_ENA__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_ERROR_ENA__MASK   0x00008000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_ERROR_ENA__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00008000U) >> 15)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_ERROR_ENA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 15) & 0x00008000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_ERROR_ENA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00008000U) | (((uint32_t)(src) <<\
                    15) & 0x00008000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_ERROR_ENA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 15) & ~0x00008000U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__CH7_ERROR_ENA__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00008000U) | ((uint32_t)(1) << 15)

/* macros for field reserve_16 */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__RESERVE_16__SHIFT              16
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__RESERVE_16__WIDTH              16
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__RESERVE_16__MASK      0xffff0000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__RESERVE_16__READ(src) \
                    (((uint32_t)(src)\
                    & 0xffff0000U) >> 16)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__TYPE                     uint32_t
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__READ                  0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__WRITE                 0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS__WOCLR                 0x0000ffffU

#endif /* __PCIE_UDMA_ADDRMAP__UDMA_INT_ENA_REGS_MACRO__ */


/* macros for dma_common.common_udma_int_ena */
#define INST_DMA_COMMON__COMMON_UDMA_INT_ENA__NUM                             1

/* macros for BlueprintGlobalNameSpace::pcie_udma_addrmap::udma_int_dis_regs */
#ifndef __PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS_MACRO__
#define __PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS_MACRO__

/* macros for field ch0_done_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_DONE_DIS__SHIFT             0
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_DONE_DIS__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_DONE_DIS__MASK    0x00000001U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_DONE_DIS__READ(src) \
                    (uint32_t)(src)\
                    & 0x00000001U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_DONE_DIS__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0x00000001U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_DONE_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000001U) | ((uint32_t)(src) &\
                    0x00000001U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_DONE_DIS__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0x00000001U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_DONE_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000001U) | (uint32_t)(1)

/* macros for field ch1_done_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_DONE_DIS__SHIFT             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_DONE_DIS__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_DONE_DIS__MASK    0x00000002U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_DONE_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000002U) >> 1)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_DONE_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 1) & 0x00000002U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_DONE_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000002U) | (((uint32_t)(src) <<\
                    1) & 0x00000002U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_DONE_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 1) & ~0x00000002U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_DONE_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000002U) | ((uint32_t)(1) << 1)

/* macros for field ch2_done_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_DONE_DIS__SHIFT             2
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_DONE_DIS__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_DONE_DIS__MASK    0x00000004U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_DONE_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000004U) >> 2)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_DONE_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 2) & 0x00000004U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_DONE_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000004U) | (((uint32_t)(src) <<\
                    2) & 0x00000004U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_DONE_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 2) & ~0x00000004U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_DONE_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000004U) | ((uint32_t)(1) << 2)

/* macros for field ch3_done_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_DONE_DIS__SHIFT             3
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_DONE_DIS__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_DONE_DIS__MASK    0x00000008U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_DONE_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000008U) >> 3)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_DONE_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 3) & 0x00000008U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_DONE_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000008U) | (((uint32_t)(src) <<\
                    3) & 0x00000008U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_DONE_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 3) & ~0x00000008U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_DONE_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000008U) | ((uint32_t)(1) << 3)

/* macros for field ch4_done_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_DONE_DIS__SHIFT             4
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_DONE_DIS__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_DONE_DIS__MASK    0x00000010U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_DONE_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000010U) >> 4)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_DONE_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 4) & 0x00000010U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_DONE_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000010U) | (((uint32_t)(src) <<\
                    4) & 0x00000010U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_DONE_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 4) & ~0x00000010U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_DONE_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000010U) | ((uint32_t)(1) << 4)

/* macros for field ch5_done_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_DONE_DIS__SHIFT             5
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_DONE_DIS__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_DONE_DIS__MASK    0x00000020U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_DONE_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000020U) >> 5)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_DONE_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 5) & 0x00000020U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_DONE_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000020U) | (((uint32_t)(src) <<\
                    5) & 0x00000020U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_DONE_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 5) & ~0x00000020U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_DONE_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000020U) | ((uint32_t)(1) << 5)

/* macros for field ch6_done_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_DONE_DIS__SHIFT             6
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_DONE_DIS__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_DONE_DIS__MASK    0x00000040U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_DONE_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000040U) >> 6)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_DONE_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 6) & 0x00000040U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_DONE_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000040U) | (((uint32_t)(src) <<\
                    6) & 0x00000040U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_DONE_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 6) & ~0x00000040U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_DONE_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000040U) | ((uint32_t)(1) << 6)

/* macros for field ch7_done_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_DONE_DIS__SHIFT             7
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_DONE_DIS__WIDTH             1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_DONE_DIS__MASK    0x00000080U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_DONE_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000080U) >> 7)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_DONE_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 7) & 0x00000080U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_DONE_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000080U) | (((uint32_t)(src) <<\
                    7) & 0x00000080U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_DONE_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 7) & ~0x00000080U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_DONE_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000080U) | ((uint32_t)(1) << 7)

/* macros for field ch0_error_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_ERROR_DIS__SHIFT            8
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_ERROR_DIS__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_ERROR_DIS__MASK   0x00000100U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_ERROR_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000100U) >> 8)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_ERROR_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 8) & 0x00000100U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_ERROR_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000100U) | (((uint32_t)(src) <<\
                    8) & 0x00000100U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_ERROR_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 8) & ~0x00000100U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH0_ERROR_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000100U) | ((uint32_t)(1) << 8)

/* macros for field ch1_error_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_ERROR_DIS__SHIFT            9
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_ERROR_DIS__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_ERROR_DIS__MASK   0x00000200U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_ERROR_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000200U) >> 9)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_ERROR_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 9) & 0x00000200U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_ERROR_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000200U) | (((uint32_t)(src) <<\
                    9) & 0x00000200U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_ERROR_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 9) & ~0x00000200U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH1_ERROR_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000200U) | ((uint32_t)(1) << 9)

/* macros for field ch2_error_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_ERROR_DIS__SHIFT           10
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_ERROR_DIS__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_ERROR_DIS__MASK   0x00000400U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_ERROR_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000400U) >> 10)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_ERROR_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 10) & 0x00000400U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_ERROR_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000400U) | (((uint32_t)(src) <<\
                    10) & 0x00000400U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_ERROR_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 10) & ~0x00000400U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH2_ERROR_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000400U) | ((uint32_t)(1) << 10)

/* macros for field ch3_error_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_ERROR_DIS__SHIFT           11
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_ERROR_DIS__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_ERROR_DIS__MASK   0x00000800U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_ERROR_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000800U) >> 11)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_ERROR_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 11) & 0x00000800U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_ERROR_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000800U) | (((uint32_t)(src) <<\
                    11) & 0x00000800U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_ERROR_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 11) & ~0x00000800U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH3_ERROR_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000800U) | ((uint32_t)(1) << 11)

/* macros for field ch4_error_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_ERROR_DIS__SHIFT           12
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_ERROR_DIS__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_ERROR_DIS__MASK   0x00001000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_ERROR_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00001000U) >> 12)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_ERROR_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 12) & 0x00001000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_ERROR_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00001000U) | (((uint32_t)(src) <<\
                    12) & 0x00001000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_ERROR_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 12) & ~0x00001000U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH4_ERROR_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00001000U) | ((uint32_t)(1) << 12)

/* macros for field ch5_error_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_ERROR_DIS__SHIFT           13
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_ERROR_DIS__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_ERROR_DIS__MASK   0x00002000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_ERROR_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00002000U) >> 13)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_ERROR_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 13) & 0x00002000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_ERROR_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00002000U) | (((uint32_t)(src) <<\
                    13) & 0x00002000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_ERROR_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 13) & ~0x00002000U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH5_ERROR_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00002000U) | ((uint32_t)(1) << 13)

/* macros for field ch6_error_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_ERROR_DIS__SHIFT           14
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_ERROR_DIS__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_ERROR_DIS__MASK   0x00004000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_ERROR_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00004000U) >> 14)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_ERROR_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 14) & 0x00004000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_ERROR_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00004000U) | (((uint32_t)(src) <<\
                    14) & 0x00004000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_ERROR_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 14) & ~0x00004000U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH6_ERROR_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00004000U) | ((uint32_t)(1) << 14)

/* macros for field ch7_error_dis */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_ERROR_DIS__SHIFT           15
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_ERROR_DIS__WIDTH            1
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_ERROR_DIS__MASK   0x00008000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_ERROR_DIS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00008000U) >> 15)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_ERROR_DIS__WRITE(src) \
                    (((uint32_t)(src)\
                    << 15) & 0x00008000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_ERROR_DIS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00008000U) | (((uint32_t)(src) <<\
                    15) & 0x00008000U)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_ERROR_DIS__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 15) & ~0x00008000U)))
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__CH7_ERROR_DIS__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00008000U) | ((uint32_t)(1) << 15)

/* macros for field reserve_16 */
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__RESERVE_16__SHIFT              16
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__RESERVE_16__WIDTH              16
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__RESERVE_16__MASK      0xffff0000U
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__RESERVE_16__READ(src) \
                    (((uint32_t)(src)\
                    & 0xffff0000U) >> 16)
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__TYPE                     uint32_t
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__READ                  0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__WRITE                 0xffffffffU
#define PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS__WOSET                 0x0000ffffU

#endif /* __PCIE_UDMA_ADDRMAP__UDMA_INT_DIS_REGS_MACRO__ */


/* macros for dma_common.common_udma_int_dis */
#define INST_DMA_COMMON__COMMON_UDMA_INT_DIS__NUM                             1

/* macros for BlueprintGlobalNameSpace::pcie_udma_addrmap::udma_ecc_regs */
#ifndef __PCIE_UDMA_ADDRMAP__UDMA_ECC_REGS_MACRO__
#define __PCIE_UDMA_ADDRMAP__UDMA_ECC_REGS_MACRO__

/* macros for field total */
#define PCIE_UDMA_ADDRMAP__UDMA_ECC_REGS__TOTAL__SHIFT                        0
#define PCIE_UDMA_ADDRMAP__UDMA_ECC_REGS__TOTAL__WIDTH                       16
#define PCIE_UDMA_ADDRMAP__UDMA_ECC_REGS__TOTAL__MASK               0x0000ffffU
#define PCIE_UDMA_ADDRMAP__UDMA_ECC_REGS__TOTAL__READ(src) \
                    (uint32_t)(src)\
                    & 0x0000ffffU

/* macros for field reserve_16 */
#define PCIE_UDMA_ADDRMAP__UDMA_ECC_REGS__RESERVE_16__SHIFT                  16
#define PCIE_UDMA_ADDRMAP__UDMA_ECC_REGS__RESERVE_16__WIDTH                  16
#define PCIE_UDMA_ADDRMAP__UDMA_ECC_REGS__RESERVE_16__MASK          0xffff0000U
#define PCIE_UDMA_ADDRMAP__UDMA_ECC_REGS__RESERVE_16__READ(src) \
                    (((uint32_t)(src)\
                    & 0xffff0000U) >> 16)
#define PCIE_UDMA_ADDRMAP__UDMA_ECC_REGS__TYPE                         uint32_t
#define PCIE_UDMA_ADDRMAP__UDMA_ECC_REGS__READ                      0xffffffffU

#endif /* __PCIE_UDMA_ADDRMAP__UDMA_ECC_REGS_MACRO__ */


/* macros for dma_common.common_udma_ib_ecc_uncorrectable_errors */
#define INST_DMA_COMMON__COMMON_UDMA_IB_ECC_UNCORRECTABLE_ERRORS__NUM         1

/* macros for dma_common.common_udma_ib_ecc_correctable_errors */
#define INST_DMA_COMMON__COMMON_UDMA_IB_ECC_CORRECTABLE_ERRORS__NUM           1

/* macros for dma_common.common_udma_ob_ecc_uncorrectable_errors */
#define INST_DMA_COMMON__COMMON_UDMA_OB_ECC_UNCORRECTABLE_ERRORS__NUM         1

/* macros for dma_common.common_udma_ob_ecc_correctable_errors */
#define INST_DMA_COMMON__COMMON_UDMA_OB_ECC_CORRECTABLE_ERRORS__NUM           1

/* macros for BlueprintGlobalNameSpace::pcie_udma_addrmap::udma_cap_ver_regs */
#ifndef __PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS_MACRO__
#define __PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS_MACRO__

/* macros for field min_ver */
#define PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS__MIN_VER__SHIFT                  0
#define PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS__MIN_VER__WIDTH                  8
#define PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS__MIN_VER__MASK         0x000000ffU
#define PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS__MIN_VER__READ(src) \
                    (uint32_t)(src)\
                    & 0x000000ffU

/* macros for field maj_ver */
#define PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS__MAJ_VER__SHIFT                  8
#define PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS__MAJ_VER__WIDTH                  8
#define PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS__MAJ_VER__MASK         0x0000ff00U
#define PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS__MAJ_VER__READ(src) \
                    (((uint32_t)(src)\
                    & 0x0000ff00U) >> 8)

/* macros for field reserve_16 */
#define PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS__RESERVE_16__SHIFT              16
#define PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS__RESERVE_16__WIDTH              16
#define PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS__RESERVE_16__MASK      0xffff0000U
#define PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS__RESERVE_16__READ(src) \
                    (((uint32_t)(src)\
                    & 0xffff0000U) >> 16)
#define PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS__TYPE                     uint32_t
#define PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS__READ                  0xffffffffU

#endif /* __PCIE_UDMA_ADDRMAP__UDMA_CAP_VER_REGS_MACRO__ */


/* macros for dma_common.common_udma_cap_ver */
#define INST_DMA_COMMON__COMMON_UDMA_CAP_VER__NUM                             1

/* macros for BlueprintGlobalNameSpace::pcie_udma_addrmap::udma_config_regs */
#ifndef __PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS_MACRO__
#define __PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS_MACRO__

/* macros for field num_channels */
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__NUM_CHANNELS__SHIFT              0
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__NUM_CHANNELS__WIDTH              4
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__NUM_CHANNELS__MASK     0x0000000fU
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__NUM_CHANNELS__READ(src) \
                    (uint32_t)(src)\
                    & 0x0000000fU

/* macros for field num_partitions */
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__NUM_PARTITIONS__SHIFT            4
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__NUM_PARTITIONS__WIDTH            4
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__NUM_PARTITIONS__MASK   0x000000f0U
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__NUM_PARTITIONS__READ(src) \
                    (((uint32_t)(src)\
                    & 0x000000f0U) >> 4)

/* macros for field partition_size */
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__PARTITION_SIZE__SHIFT            8
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__PARTITION_SIZE__WIDTH            4
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__PARTITION_SIZE__MASK   0x00000f00U
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__PARTITION_SIZE__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000f00U) >> 8)

/* macros for field sys_aw_gt_32 */
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__SYS_AW_GT_32__SHIFT             12
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__SYS_AW_GT_32__WIDTH              1
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__SYS_AW_GT_32__MASK     0x00001000U
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__SYS_AW_GT_32__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00001000U) >> 12)
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__SYS_AW_GT_32__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00001000U) | ((uint32_t)(1) << 12)
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__SYS_AW_GT_32__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00001000U) | ((uint32_t)(0) << 12)

/* macros for field sys_tw_gt_32 */
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__SYS_TW_GT_32__SHIFT             13
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__SYS_TW_GT_32__WIDTH              1
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__SYS_TW_GT_32__MASK     0x00002000U
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__SYS_TW_GT_32__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00002000U) >> 13)
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__SYS_TW_GT_32__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00002000U) | ((uint32_t)(1) << 13)
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__SYS_TW_GT_32__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00002000U) | ((uint32_t)(0) << 13)

/* macros for field ext_aw_gt_32 */
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__EXT_AW_GT_32__SHIFT             14
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__EXT_AW_GT_32__WIDTH              1
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__EXT_AW_GT_32__MASK     0x00004000U
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__EXT_AW_GT_32__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00004000U) >> 14)
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__EXT_AW_GT_32__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00004000U) | ((uint32_t)(1) << 14)
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__EXT_AW_GT_32__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00004000U) | ((uint32_t)(0) << 14)

/* macros for field ext_tw_gt_32 */
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__EXT_TW_GT_32__SHIFT             15
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__EXT_TW_GT_32__WIDTH              1
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__EXT_TW_GT_32__MASK     0x00008000U
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__EXT_TW_GT_32__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00008000U) >> 15)
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__EXT_TW_GT_32__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00008000U) | ((uint32_t)(1) << 15)
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__EXT_TW_GT_32__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00008000U) | ((uint32_t)(0) << 15)

/* macros for field reserve_16 */
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__RESERVE_16__SHIFT               16
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__RESERVE_16__WIDTH               16
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__RESERVE_16__MASK       0xffff0000U
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__RESERVE_16__READ(src) \
                    (((uint32_t)(src)\
                    & 0xffff0000U) >> 16)
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__TYPE                      uint32_t
#define PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS__READ                   0xffffffffU

#endif /* __PCIE_UDMA_ADDRMAP__UDMA_CONFIG_REGS_MACRO__ */


/* macros for dma_common.common_udma_config */
#define INST_DMA_COMMON__COMMON_UDMA_CONFIG__NUM                              1
#define RFILE_INST_DMA_CH0__NUM                                               1
#define RFILE_INST_DMA_CH1__NUM                                               1
#define RFILE_INST_DMA_COMMON__NUM                                            1

#endif /* __REG_PCIE_UDMA_ADDRMAP_MACRO_H__ */
