/* Copyright (C) 2014 Cadence Design Systems.  All rights reserved           */
/* THIS FILE IS AUTOMATICALLY GENERATED BY CADENCE BLUEPRINT, DO NOT EDIT    */
/*                                                                           */


#ifndef __REG_CDN_AXI_WRAPPER_OB_MACRO_H__
#define __REG_CDN_AXI_WRAPPER_OB_MACRO_H__


/* macros for BlueprintGlobalNameSpace::cdn_axi_wrapper_ob::axiw_ob_region_ad0 */
#ifndef __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0_MACRO__
#define __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0_MACRO__

/* macros for field num_bits */
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__NUM_BITS__SHIFT               0
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__NUM_BITS__WIDTH               6
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__NUM_BITS__MASK      0x0000003fU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__NUM_BITS__READ(src) \
                    (uint32_t)(src)\
                    & 0x0000003fU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__NUM_BITS__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0x0000003fU)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__NUM_BITS__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x0000003fU) | ((uint32_t)(src) &\
                    0x0000003fU)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__NUM_BITS__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0x0000003fU)))

/* macros for field rsvd */
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__RSVD__SHIFT                   6
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__RSVD__WIDTH                   2
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__RSVD__MASK          0x000000c0U
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__RSVD__READ(src) \
                    (((uint32_t)(src)\
                    & 0x000000c0U) >> 6)

/* macros for field data */
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__DATA__SHIFT                   8
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__DATA__WIDTH                  24
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__DATA__MASK          0xffffff00U
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__DATA__READ(src) \
                    (((uint32_t)(src)\
                    & 0xffffff00U) >> 8)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__DATA__WRITE(src) \
                    (((uint32_t)(src)\
                    << 8) & 0xffffff00U)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__DATA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0xffffff00U) | (((uint32_t)(src) <<\
                    8) & 0xffffff00U)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__DATA__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 8) & ~0xffffff00U)))
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__TYPE                   uint32_t
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__READ                0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0__WRITE               0xffffffffU

#endif /* __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD0_MACRO__ */


/* macros for addr0 */
#define INST_ADDR0__NUM                                                       1

/* macros for BlueprintGlobalNameSpace::cdn_axi_wrapper_ob::axiw_ob_region_ad1 */
#ifndef __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD1_MACRO__
#define __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD1_MACRO__

/* macros for field data */
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD1__DATA__SHIFT                   0
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD1__DATA__WIDTH                  32
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD1__DATA__MASK          0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD1__DATA__READ(src) \
                    (uint32_t)(src)\
                    & 0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD1__DATA__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0xffffffffU)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD1__DATA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0xffffffffU) | ((uint32_t)(src) &\
                    0xffffffffU)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD1__DATA__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0xffffffffU)))
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD1__TYPE                   uint32_t
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD1__READ                0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD1__WRITE               0xffffffffU

#endif /* __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_AD1_MACRO__ */


/* macros for addr1 */
#define INST_ADDR1__NUM                                                       1

/* macros for BlueprintGlobalNameSpace::cdn_axi_wrapper_ob::axiw_ob_region_dr0 */
#ifndef __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR0_MACRO__
#define __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR0_MACRO__

/* macros for field data */
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR0__DATA__SHIFT                   0
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR0__DATA__WIDTH                  32
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR0__DATA__MASK          0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR0__DATA__READ(src) \
                    (uint32_t)(src)\
                    & 0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR0__DATA__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0xffffffffU)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR0__DATA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0xffffffffU) | ((uint32_t)(src) &\
                    0xffffffffU)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR0__DATA__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0xffffffffU)))
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR0__TYPE                   uint32_t
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR0__READ                0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR0__WRITE               0xffffffffU

#endif /* __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR0_MACRO__ */


/* macros for desc0 */
#define INST_DESC0__NUM                                                       1

/* macros for BlueprintGlobalNameSpace::cdn_axi_wrapper_ob::axiw_ob_region_dr1 */
#ifndef __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR1_MACRO__
#define __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR1_MACRO__

/* macros for field data */
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR1__DATA__SHIFT                   0
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR1__DATA__WIDTH                  32
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR1__DATA__MASK          0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR1__DATA__READ(src) \
                    (uint32_t)(src)\
                    & 0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR1__DATA__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0xffffffffU)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR1__DATA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0xffffffffU) | ((uint32_t)(src) &\
                    0xffffffffU)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR1__DATA__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0xffffffffU)))
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR1__TYPE                   uint32_t
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR1__READ                0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR1__WRITE               0xffffffffU

#endif /* __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR1_MACRO__ */


/* macros for desc1 */
#define INST_DESC1__NUM                                                       1

/* macros for BlueprintGlobalNameSpace::cdn_axi_wrapper_ob::axiw_ob_region_dr2 */
#ifndef __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR2_MACRO__
#define __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR2_MACRO__

/* macros for field data */
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR2__DATA__SHIFT                   0
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR2__DATA__WIDTH                  32
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR2__DATA__MASK          0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR2__DATA__READ(src) \
                    (uint32_t)(src)\
                    & 0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR2__DATA__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0xffffffffU)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR2__DATA__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0xffffffffU) | ((uint32_t)(src) &\
                    0xffffffffU)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR2__DATA__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0xffffffffU)))
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR2__TYPE                   uint32_t
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR2__READ                0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR2__WRITE               0xffffffffU

#endif /* __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR2_MACRO__ */


/* macros for desc2 */
#define INST_DESC2__NUM                                                       1

/* macros for BlueprintGlobalNameSpace::cdn_axi_wrapper_ob::axiw_ob_region_dr3 */
#ifndef __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR3_MACRO__
#define __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR3_MACRO__

/* macros for field data */
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR3__DATA__SHIFT                   0
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR3__DATA__WIDTH                  32
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR3__DATA__MASK          0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR3__DATA__READ(src) \
                    (uint32_t)(src)\
                    & 0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR3__TYPE                   uint32_t
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR3__READ                0xffffffffU

#endif /* __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_DR3_MACRO__ */


/* macros for desc3 */
#define INST_DESC3__NUM                                                       1

/* macros for BlueprintGlobalNameSpace::cdn_axi_wrapper_ob::axiw_ob_region_ctrl */
#ifndef __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL_MACRO__
#define __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL_MACRO__

/* macros for field serialization */
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__SERIALIZATION__SHIFT         0
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__SERIALIZATION__WIDTH         1
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__SERIALIZATION__MASK \
                    0x00000001U
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__SERIALIZATION__READ(src) \
                    (uint32_t)(src)\
                    & 0x00000001U
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__SERIALIZATION__WRITE(src) \
                    ((uint32_t)(src)\
                    & 0x00000001U)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__SERIALIZATION__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000001U) | ((uint32_t)(src) &\
                    0x00000001U)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__SERIALIZATION__VERIFY(src) \
                    (!(((uint32_t)(src)\
                    & ~0x00000001U)))
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__SERIALIZATION__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000001U) | (uint32_t)(1)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__SERIALIZATION__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000001U) | (uint32_t)(0)

/* macros for field blocking */
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__BLOCKING__SHIFT              1
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__BLOCKING__WIDTH              1
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__BLOCKING__MASK     0x00000002U
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__BLOCKING__READ(src) \
                    (((uint32_t)(src)\
                    & 0x00000002U) >> 1)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__BLOCKING__WRITE(src) \
                    (((uint32_t)(src)\
                    << 1) & 0x00000002U)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__BLOCKING__MODIFY(dst, src) \
                    (dst) = ((dst) &\
                    ~0x00000002U) | (((uint32_t)(src) <<\
                    1) & 0x00000002U)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__BLOCKING__VERIFY(src) \
                    (!((((uint32_t)(src)\
                    << 1) & ~0x00000002U)))
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__BLOCKING__SET(dst) \
                    (dst) = ((dst) &\
                    ~0x00000002U) | ((uint32_t)(1) << 1)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__BLOCKING__CLR(dst) \
                    (dst) = ((dst) &\
                    ~0x00000002U) | ((uint32_t)(0) << 1)

/* macros for field reserved */
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__RESERVED__SHIFT              2
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__RESERVED__WIDTH             30
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__RESERVED__MASK     0xfffffffcU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__RESERVED__READ(src) \
                    (((uint32_t)(src)\
                    & 0xfffffffcU) >> 2)
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__TYPE                  uint32_t
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__READ               0xffffffffU
#define CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL__WRITE              0xffffffffU

#endif /* __CDN_AXI_WRAPPER_OB__AXIW_OB_REGION_CTRL_MACRO__ */


/* macros for ctrl */
#define INST_CTRL__NUM                                                        1

#endif /* __REG_CDN_AXI_WRAPPER_OB_MACRO_H__ */
