/* Copyright (C) 2014 Cadence Design Systems.  All rights reserved           */
/* THIS FILE IS AUTOMATICALLY GENERATED BY CADENCE BLUEPRINT, DO NOT EDIT    */
/*                                                                           */


#ifndef __REG_PCIE_TOP_H__
#define __REG_PCIE_TOP_H__

#include "pcie_top_macro.h"

struct pcie_PF_addrmap__regf_pcie_base {
  volatile uint32_t i_vendor_id_device_id;        /*        0x0 - 0x4        */
  volatile uint32_t i_command_status;             /*        0x4 - 0x8        */
  volatile uint32_t i_revision_id_class_code;     /*        0x8 - 0xc        */
  volatile uint32_t i_bist_header_latency_cache_line;
                                                  /*        0xc - 0x10       */
  volatile uint32_t i_base_addr_0;                /*       0x10 - 0x14       */
  volatile uint32_t i_base_addr_1;                /*       0x14 - 0x18       */
  volatile uint32_t i_base_addr_2;                /*       0x18 - 0x1c       */
  volatile uint32_t i_base_addr_3;                /*       0x1c - 0x20       */
  volatile uint32_t i_base_addr_4;                /*       0x20 - 0x24       */
  volatile uint32_t i_base_addr_5;                /*       0x24 - 0x28       */
  volatile uint32_t rsvd_0A;                      /*       0x28 - 0x2c       */
  volatile uint32_t i_subsystem_vendor_id_subsystem_i;
                                                  /*       0x2c - 0x30       */
  volatile uint32_t rsvd_0C;                      /*       0x30 - 0x34       */
  volatile uint32_t i_capabilities_pointer;       /*       0x34 - 0x38       */
  volatile uint32_t rsvd_0E;                      /*       0x38 - 0x3c       */
  volatile uint32_t i_intrpt_line_intrpt_pin;     /*       0x3c - 0x40       */
  volatile uint32_t rsvd_010_01F[16];             /*       0x40 - 0x80       */
};

struct pcie_PF_addrmap__regf_power_mgmt_cap_struct {
  volatile uint32_t i_pwr_mgmt_cap;               /*        0x0 - 0x4        */
  volatile uint32_t i_pwr_mgmt_ctrl_stat_rep;     /*        0x4 - 0x8        */
  volatile uint32_t rsvd_022_023[2];              /*        0x8 - 0x10       */
};

struct pcie_PF_addrmap__regf_MSI_cap_struct {
  volatile uint32_t i_msi_ctrl_reg;               /*        0x0 - 0x4        */
  volatile uint32_t i_msi_msg_low_addr;           /*        0x4 - 0x8        */
  volatile uint32_t i_msi_msg_hi_addr;            /*        0x8 - 0xc        */
  volatile uint32_t i_msi_msg_data;               /*        0xc - 0x10       */
  volatile uint32_t i_msi_mask;                   /*       0x10 - 0x14       */
  volatile uint32_t i_msi_pending_bits;           /*       0x14 - 0x18       */
  volatile uint32_t rsvd_02A_02B[2];              /*       0x18 - 0x20       */
};

struct pcie_PF_addrmap__regf_PCIE_cap_struct {
  volatile uint32_t i_pcie_cap_list;              /*        0x0 - 0x4        */
  volatile uint32_t i_pcie_dev_cap;               /*        0x4 - 0x8        */
  volatile uint32_t i_pcie_dev_ctrl_status;       /*        0x8 - 0xc        */
  volatile uint32_t i_link_cap;                   /*        0xc - 0x10       */
  volatile uint32_t i_link_ctrl_status;           /*       0x10 - 0x14       */
  volatile uint32_t rsvd_035;                     /*       0x14 - 0x18       */
  volatile uint32_t rsvd_036;                     /*       0x18 - 0x1c       */
  volatile uint32_t rsvd_037_038[2];              /*       0x1c - 0x24       */
  volatile uint32_t i_pcie_dev_cap_2;             /*       0x24 - 0x28       */
  volatile uint32_t i_pcie_dev_ctrl_status_2;     /*       0x28 - 0x2c       */
  volatile uint32_t i_link_cap_2_reg;             /*       0x2c - 0x30       */
  volatile uint32_t i_link_ctrl_status_2;         /*       0x30 - 0x34       */
  volatile uint32_t rsvd_03D_03F[3];              /*       0x34 - 0x40       */
};

struct pcie_PF_addrmap__regf_AER_cap_struct {
  volatile uint32_t i_AER_enhanced_cap_hdr;       /*        0x0 - 0x4        */
  volatile uint32_t i_uncorr_err_status;          /*        0x4 - 0x8        */
  volatile uint32_t i_uncorr_err_mask;            /*        0x8 - 0xc        */
  volatile uint32_t i_uncorr_err_severity;        /*        0xc - 0x10       */
  volatile uint32_t i_corr_err_status;            /*       0x10 - 0x14       */
  volatile uint32_t i_corr_err_mask;              /*       0x14 - 0x18       */
  volatile uint32_t i_advcd_err_cap_ctrl;         /*       0x18 - 0x1c       */
  volatile uint32_t i_hdr_log_0;                  /*       0x1c - 0x20       */
  volatile uint32_t i_hdr_log_1;                  /*       0x20 - 0x24       */
  volatile uint32_t i_hdr_log_2;                  /*       0x24 - 0x28       */
  volatile uint32_t i_hdr_log_3;                  /*       0x28 - 0x2c       */
  volatile uint32_t rsvd_04B_04D[3];              /*       0x2c - 0x38       */
};

struct pcie_PF_addrmap__regf_device_serial_num_cap_struct {
  volatile uint32_t i_dev_ser_num_cap_hdr;        /*        0x0 - 0x4        */
  volatile uint32_t i_dev_ser_num_0;              /*        0x4 - 0x8        */
  volatile uint32_t i_dev_ser_num_1;              /*        0x8 - 0xc        */
  volatile uint32_t rsvd_057;                     /*        0xc - 0x10       */
};

struct pcie_PF_addrmap__regf_TPH_cap_struct {
  volatile uint32_t i_TPH_req_ext_cap_header_reg; /*        0x0 - 0x4        */
  volatile uint32_t i_TPH_req_cap_reg;            /*        0x4 - 0x8        */
  volatile uint32_t i_TPH_req_ctrl_reg;           /*        0x8 - 0xc        */
  volatile uint32_t i_TPH_tab_0;                  /*        0xc - 0x10       */
  volatile uint32_t i_TPH_tab_1;                  /*       0x10 - 0x14       */
  volatile uint32_t i_TPH_tab_2;                  /*       0x14 - 0x18       */
  volatile uint32_t i_TPH_tab_3;                  /*       0x18 - 0x1c       */
};

struct pcie_PF_addrmap {
  struct pcie_PF_addrmap__regf_pcie_base i_pcie_base;
                                                  /*        0x0 - 0x80       */
  struct pcie_PF_addrmap__regf_power_mgmt_cap_struct i_power_mgmt_cap_struct;
                                                  /*       0x80 - 0x90       */
  struct pcie_PF_addrmap__regf_MSI_cap_struct i_MSI_cap_struct;
                                                  /*       0x90 - 0xb0       */
  volatile char pad__0[0x10];                     /*       0xb0 - 0xc0       */
  struct pcie_PF_addrmap__regf_PCIE_cap_struct i_PCIE_cap_struct;
                                                  /*       0xc0 - 0x100      */
  struct pcie_PF_addrmap__regf_AER_cap_struct i_AER_cap_struct;
                                                  /*      0x100 - 0x138      */
  volatile char pad__1[0x18];                     /*      0x138 - 0x150      */
  struct pcie_PF_addrmap__regf_device_serial_num_cap_struct i_device_serial_num_cap_struct;
                                                  /*      0x150 - 0x160      */
  volatile char pad__2[0x114];                    /*      0x160 - 0x274      */
  struct pcie_PF_addrmap__regf_TPH_cap_struct i_TPH_cap_struct;
                                                  /*      0x274 - 0x290      */
};

struct pcie_LM_addrmap__regf_lm_pcie_base {
  volatile uint32_t i_pl_config_0_reg;            /*        0x0 - 0x4        */
  volatile uint32_t i_pl_config_1_reg;            /*        0x4 - 0x8        */
  volatile uint32_t i_dll_tmr_config_reg;         /*        0x8 - 0xc        */
  volatile uint32_t i_rcv_cred_lim_0_reg;         /*        0xc - 0x10       */
  volatile uint32_t i_rcv_cred_lim_1_reg;         /*       0x10 - 0x14       */
  volatile uint32_t i_transm_cred_lim_0_reg;      /*       0x14 - 0x18       */
  volatile uint32_t i_transm_cred_lim_1_reg;      /*       0x18 - 0x1c       */
  volatile uint32_t i_transm_cred_update_int_config_0_reg;
                                                  /*       0x1c - 0x20       */
  volatile uint32_t i_transm_cred_update_int_config_1_reg;
                                                  /*       0x20 - 0x24       */
  volatile uint32_t i_L0S_timeout_limit_reg;      /*       0x24 - 0x28       */
  volatile uint32_t i_transmit_tlp_count_reg;     /*       0x28 - 0x2c       */
  volatile uint32_t i_transmit_tlp_payload_dword_count_reg;
                                                  /*       0x2c - 0x30       */
  volatile uint32_t i_receive_tlp_count_reg;      /*       0x30 - 0x34       */
  volatile uint32_t i_receive_tlp_payload_dword_count_reg;
                                                  /*       0x34 - 0x38       */
  volatile uint32_t i_compln_tmout_lim_0_reg;     /*       0x38 - 0x3c       */
  volatile uint32_t i_compln_tmout_lim_1_reg;     /*       0x3c - 0x40       */
  volatile uint32_t i_L1_st_reentry_delay_reg;    /*       0x40 - 0x44       */
  volatile uint32_t i_vendor_id_reg;              /*       0x44 - 0x48       */
  volatile uint32_t i_aspm_L1_entry_tmout_delay_reg;
                                                  /*       0x48 - 0x4c       */
  volatile uint32_t i_pme_turnoff_ack_delay_reg;  /*       0x4c - 0x50       */
  volatile char pad__0[0x24];                     /*       0x50 - 0x74       */
  volatile uint32_t i_sris_control_reg;           /*       0x74 - 0x78       */
  volatile char pad__1[0x88];                     /*       0x78 - 0x100      */
  volatile uint32_t i_shdw_hdr_log_0_reg;         /*      0x100 - 0x104      */
  volatile uint32_t i_shdw_hdr_log_1_reg;         /*      0x104 - 0x108      */
  volatile uint32_t i_shdw_hdr_log_2_reg;         /*      0x108 - 0x10c      */
  volatile uint32_t i_shdw_hdr_log_3_reg;         /*      0x10c - 0x110      */
  volatile uint32_t i_shdw_func_num_reg;          /*      0x110 - 0x114      */
  volatile uint32_t i_shdw_ur_err_reg;            /*      0x114 - 0x118      */
  volatile char pad__2[0xe8];                     /*      0x118 - 0x200      */
  volatile uint32_t i_negotiated_lane_map_reg;    /*      0x200 - 0x204      */
  volatile uint32_t i_receive_fts_count_reg;      /*      0x204 - 0x208      */
  volatile uint32_t i_debug_mux_control_reg;      /*      0x208 - 0x20c      */
  volatile uint32_t i_local_error_status_register;
                                                  /*      0x20c - 0x210      */
  volatile uint32_t i_local_intrpt_mask_reg;      /*      0x210 - 0x214      */
  volatile uint32_t i_lcrc_err_count_reg;         /*      0x214 - 0x218      */
  volatile uint32_t i_ecc_corr_err_count_reg;     /*      0x218 - 0x21c      */
  volatile char pad__3[0x8];                      /*      0x21c - 0x224      */
  volatile uint32_t i_pme_service_timeout_delay_reg;
                                                  /*      0x224 - 0x228      */
  volatile uint32_t i_root_port_requestor_id_reg; /*      0x228 - 0x22c      */
  volatile uint32_t i_ep_bus_device_number_reg;   /*      0x22c - 0x230      */
  volatile char pad__4[0x10];                     /*      0x230 - 0x240      */
  volatile uint32_t i_pf_0_BAR_config_0_reg;      /*      0x240 - 0x244      */
  volatile uint32_t i_pf_0_BAR_config_1_reg;      /*      0x244 - 0x248      */
  volatile char pad__5[0x78];                     /*      0x248 - 0x2c0      */
  volatile uint32_t i_pf_config_reg;              /*      0x2c0 - 0x2c4      */
  volatile char pad__6[0x3c];                     /*      0x2c4 - 0x300      */
  volatile uint32_t i_rc_BAR_config_reg;          /*      0x300 - 0x304      */
};

struct pcie_LM_addrmap {
  struct pcie_LM_addrmap__regf_lm_pcie_base i_regf_lm_pcie_base;
                                                  /*        0x0 - 0x304      */
};

struct pcie_VF_addrmap {
  volatile uint32_t i_VF_generic_reserved_reg;    /*        0x0 - 0x4        */
};

struct pcie_RC_addrmap__regf_rc_pcie_base {
  volatile uint32_t i_vendor_id_device_id;        /*        0x0 - 0x4        */
  volatile uint32_t i_command_status;             /*        0x4 - 0x8        */
  volatile uint32_t i_revision_id_class_code;     /*        0x8 - 0xc        */
  volatile uint32_t i_bist_header_latency_cache_line;
                                                  /*        0xc - 0x10       */
  volatile uint32_t i_RC_BAR_0;                   /*       0x10 - 0x14       */
  volatile uint32_t i_RC_BAR_1;                   /*       0x14 - 0x18       */
  volatile uint32_t i_pcie_bus_numbers;           /*       0x18 - 0x1c       */
  volatile uint32_t i_pcie_io_base_limit;         /*       0x1c - 0x20       */
  volatile uint32_t i_pcie_mem_base_limit;        /*       0x20 - 0x24       */
  volatile uint32_t i_pcie_prefetch_base_limit;   /*       0x24 - 0x28       */
  volatile uint32_t i_pcie_prefetch_base_upper;   /*       0x28 - 0x2c       */
  volatile uint32_t i_pcie_prefetch_limit_upper;  /*       0x2c - 0x30       */
  volatile uint32_t i_pcie_io_base_limit_upper;   /*       0x30 - 0x34       */
  volatile uint32_t i_capabilities_pointer;       /*       0x34 - 0x38       */
  volatile uint32_t rsvd_0e;                      /*       0x38 - 0x3c       */
  volatile uint32_t i_intrpt_line_intrpt_pin;     /*       0x3c - 0x40       */
  volatile uint32_t rsvd_010_01F[16];             /*       0x40 - 0x80       */
  volatile uint32_t i_pwr_mgmt_cap;               /*       0x80 - 0x84       */
  volatile uint32_t i_pwr_mgmt_ctrl_stat_rep;     /*       0x84 - 0x88       */
  volatile uint32_t rsvd_22_2F[14];               /*       0x88 - 0xc0       */
  volatile uint32_t i_pcie_cap_list;              /*       0xc0 - 0xc4       */
  volatile uint32_t i_pcie_cap;                   /*       0xc4 - 0xc8       */
  volatile uint32_t i_pcie_dev_ctrl_status;       /*       0xc8 - 0xcc       */
  volatile uint32_t i_link_cap;                   /*       0xcc - 0xd0       */
  volatile uint32_t i_link_ctl_stat;              /*       0xd0 - 0xd4       */
  volatile uint32_t rsvd_35;                      /*       0xd4 - 0xd8       */
  volatile uint32_t i_slot_ctrl_status;           /*       0xd8 - 0xdc       */
  volatile uint32_t i_root_ctrl_cap;              /*       0xdc - 0xe0       */
  volatile uint32_t i_root_status;                /*       0xe0 - 0xe4       */
  volatile uint32_t i_pcie_cap_2;                 /*       0xe4 - 0xe8       */
  volatile uint32_t i_pcie_dev_ctrl_status_2;     /*       0xe8 - 0xec       */
  volatile uint32_t i_link_cap_2;                 /*       0xec - 0xf0       */
  volatile uint32_t i_link_ctl_stat_2;            /*       0xf0 - 0xf4       */
  volatile uint32_t rsvd_3D_3F[3];                /*       0xf4 - 0x100      */
  volatile uint32_t i_AER_enhncd_cap;             /*      0x100 - 0x104      */
  volatile uint32_t i_uncorr_err_status;          /*      0x104 - 0x108      */
  volatile uint32_t i_uncorr_err_mask;            /*      0x108 - 0x10c      */
  volatile uint32_t i_uncorr_err_severity;        /*      0x10c - 0x110      */
  volatile uint32_t i_corr_err_status;            /*      0x110 - 0x114      */
  volatile uint32_t i_corr_err_mask;              /*      0x114 - 0x118      */
  volatile uint32_t i_adv_err_cap_ctl;            /*      0x118 - 0x11c      */
  volatile uint32_t i_hdr_log_0;                  /*      0x11c - 0x120      */
  volatile uint32_t i_hdr_log_1;                  /*      0x120 - 0x124      */
  volatile uint32_t i_hdr_log_2;                  /*      0x124 - 0x128      */
  volatile uint32_t i_hdr_log_3;                  /*      0x128 - 0x12c      */
  volatile uint32_t i_root_err_cmd;               /*      0x12c - 0x130      */
  volatile uint32_t i_root_err_stat;              /*      0x130 - 0x134      */
  volatile uint32_t i_err_src_id;                 /*      0x134 - 0x138      */
  volatile uint32_t rsvd_4E_53[6];                /*      0x138 - 0x150      */
  volatile uint32_t i_dev_ser_num_cap_hdr;        /*      0x150 - 0x154      */
  volatile uint32_t i_dev_ser_num_0;              /*      0x154 - 0x158      */
  volatile uint32_t i_dev_ser_num_1;              /*      0x158 - 0x15c      */
  volatile uint32_t rsvd_57_BF[105];              /*      0x15c - 0x300      */
};

struct pcie_RC_addrmap {
  struct pcie_RC_addrmap__regf_rc_pcie_base i_rc_pcie_base;
                                                  /*        0x0 - 0x300      */
};

struct pcie_top {
  struct pcie_PF_addrmap i_pcie_PF;               /*        0x0 - 0x294      */
  volatile char pad__0[0x16c];                    /*      0x294 - 0x400      */
  struct pcie_LM_addrmap i_pcie_LM;               /*      0x400 - 0x800      */
  struct pcie_VF_addrmap i_pcie_VF;               /*      0x800 - 0x804      */
  volatile char pad__1[0x3fc];                    /*      0x804 - 0xc00      */
  struct pcie_RC_addrmap i_pcie_RC;               /*      0xc00 - 0x1000     */
};

#endif /* __REG_PCIE_TOP_H__ */
